### ISSUE TITLE
Fehler in xStream

### ISSUE THREAD

**Issue by DWH-WFC** [streamxstream/plugin.video.xstream#1]
Cinemaxx.cc not avilable in xstream (Site Online)
Kinox.to Site names
Alle Serien streams not avilable in xstream (Site Online)Bsp.: Knallerfrauen
Metahandler ist active then crash serienstream section search from A to Z

**Comment by anis3** [comment]
Hallo DWH-WFC
Cinemaxx.cc geht nicht bin dran
alleserien.com ja bin auch dran
serienstream kann ich nicht nachvollziehn bitte mehr infos
genauso kinox was meinst du mit Site names????
die domains aktuallisieren wo ich gemacht habe aktuell????
LG Anis

**Comment by DWH-WFC** [comment]
Erstmal danke für eure Arbeit 

Guten Morgen 

Ja bei Kinox die Domain Namen. Bitte auch in der Settings.xml.

In Serienstream der Fehler.
Ist der Metahandler nicht aktiv in xStream funktioniert alles problemlos. Wird dieser aktiviert dann funktioniert Serienstream nicht mehr und zwar wenn man z.B über die A-Z Suche rein geht eine Serie auswählt und den Stream starten will. Dann kommt eine Fehlermeldung. Und es wird keine Stream übergeben.

Von meinem iPhone gesendet

**Comment by anis3** [comment]
ok bei Serienstream kann ich den fehler nicht nachvollziehn
das problem wird temporär sein ist bei der seite ab und zu so

alleserien müsste jetzt gehn

cinemaxx.cc dauert ein bischen liegt am ddos schutz(blazingfast)
LG Anis

**Comment by anis3** [comment]
ok bei Serienstream kann ich den fehler nicht nachvollziehn
das problem wird temporär sein ist bei der seite ab und zu so

alleserien müsste jetzt gehn

cinemaxx.cc dauert ein bischen liegt am ddos schutz(blazingfast)

zu kinox die Settings.xml aktuallisiert sich in xStream von selbst

danke für die hinweiße
LG Anis

**Comment by DWH-WFC** [comment]
Ich danke 🙏 für eure Arbeit erstmal. Das Problem mit dem Metahandler und Serienstream besteht aber schon länger 🤪.

**Comment by anis3** [comment]
sorry ich kann nix fixen wo ich nicht nachstellen kann
darum bitte was nutzt du android,windows usw.
welche kodi version und einstellungen in metahandler
denke standard nur auf deutsch umgestellt???
und dann wo bei Serienstream a-z hast du das problem
bin bis e alles durchgegangen(windows) mit aktiven metahandler
und habe keine probleme festgestellt
LG Anis

**Comment by DWH-WFC** [comment]
Ich werd es mal Filmen wenn Zeit ist. 
Dankeschön erstmal für deine Mühe.

**Comment by DWH-WFC** [comment]
Sorry das es so lange gedauert hat. Ist nicht immer leicht Zeit zu finden als alleinerziehender Vater.
Hab mal für den Test Kodi frisch installiert hier zum Beispiel auf Windows. Auf den Plattformen UWP und Android ist der selbe Fehler.

[http://wrp-world.net/wrp/video/Meta.html](url)

**Comment by DWH-WFC** [comment]
[https://bit.ly/30cO6GU](url)

**Comment by DWH-WFC** [comment]
Danke mit der angehängten Metahandler.py funktioniert es tadellos.

**Comment by DWH-WFC** [comment]
Noch eine Bitte hätte ich, dies hat auch Zeit Anis vielleicht kannst in Serienstream bei den Links die SD und HD Anzeige anpassen. Der Unterschied ist im Code zwar deklariert aber ohne Funktion und HD Streams werden als SD Streams angezeigt. Weis nicht ob bei allen Serien aber bei denen die ich zuletzt gesehen habe ist mir das aufgefallen. Wie gesagt Ist nur ne Info vielleicht willst es auch nicht ändern 🤪

**Comment by anis3** [comment]
ok s.to hoster Qualy gefixt
