### ISSUE TITLE
Feature Anfrage

### ISSUE THREAD

**Issue by mczero80** [streamxstream/plugin.video.xstream#10]
Es wäre praktisch einen Suchverlauf in der Suche zu haben. Gerade wenn man mühselig etwas mit einer einfachen Fernbedienung eingibt und dann der Stream abstürzt und man von vorne anfängt alles einzugeben, wünscht man sich doch einen Suchverlauf, um nochmal nach dem gleichen Titel zu suchen.

**Comment by DWH-WFC** [comment]
Nein das wollen wir nicht integrieren. Wenn du in Verbindung mit dem TMDb Helper, xStream nutzt, hast du die Funktion dabei.
