### ISSUE TITLE
[Bug] Installation nicht möglich, da `script.module.pydevd` fehlt

### ISSUE THREAD

**Issue by MartinX3** [streamxstream/plugin.video.xstream#100]
Seit dem release ist leider die alte XStream-Version aus Kodi verschwunden.
Die neue lässt sich nicht installieren, da Kodi auf LibreElec die Abhängigkeit `script.module.pydevd` nicht findet.

Soweit ich es verstehe ist diese nur für Entwickler zum debuggen, daher verstehe ich nicht, wieso sie zwingend von Kodi verlangt wird.

Hier ist sie gelistet:
https://github.com/streamxstream/xStreamRepo/blob/master/addons.xml#L11

**Comment by DWH-WFC** [comment]
Danke für dein Info den Fehler werden wir schnellst möglichst beheben.

**Comment by DWH-WFC** [comment]
Fehler wurde behoben bitte in der Repository „Aktualisierungen suchen“ ausführen dann sollte es problemlos installierbar sein.

**Comment by MartinX3** [comment]
Danke, das Modul ist jetzt weg.
Allerdings sagt er immernoch, dass die Installation fehlschlägt.

Ich gucke mal, dass ich irgendwie logs erstelle.
