### ISSUE TITLE
JDownloader2-, MyJDownloader Handler.py, myjdapi.py

### ISSUE THREAD

**Issue by Sysdocalex** [streamxstream/plugin.video.xstream#103]
Die Handler in plugin.video.xstream/resources/lib/handler bedürfen einer Überprüfung und evtl. eine Anpassung der API Daten für das Downloaden über JDownloader.
Einen Ansatz für die entsprechenden Files habe ich hier gefunden:
https://files.pythonhosted.org/packages/6a/79/082c2054dd0a15c54bdbb9e9f5538f0f1f415257b22eaf68d46da88fc1dd/myjdapi-1.1.4.tar.gz

**Comment by Heptamer** [comment]
Danke, ich hab mir das mal angeschaut, scheint das der Token der zurück kommt vom jdownloader Probleme macht. Leider findet sich nichts dazu in der api doku. Habe deswegen daher Mal einen Dev vom Jdownloader Team angeschrieben. Wenn ich Antwort habe geht's weiter.

**Comment by DWH-WFC** [comment]
Funktion wurde in der Nightly repariert.
