### ISSUE TITLE
Globale suche crashed bei Sonderzeichen

### ISSUE THREAD

**Issue by MartinX3** [streamxstream/plugin.video.xstream#104]
Ich suchte nach `Star Trek: Discovery` und bekam "RuntimeError: can't start new thread, t.start()"

Ich musste den Raspi neu starten, da die Suche danach nicht mehr funktionierte.
Deaktivieren und aktivieren von des Add-ons hatte leider nicht geholfen.

Allerdings muss ich den `:` angeben, denn ohne korrekte Zeichenfolge gibt es keine Suchergebnisse.

Vllt wäre es gut nicht nach der exakten Folge zu gucken, sondern nach Ergebnissen die diese Werte in beliebiger Reihenfolge enthalten.
Über die Webseiten dieser Dienste klappt das auch ohne `:`.

**Comment by Heptamer** [comment]
Gerade auf dem Handy mit KODi 19 und A12 probiert, geht ohne Probleme.

Von daher, ohne Nennung der Kodi- und xstream Version sowie dem Betriebssystem schauen wir uns das nicht weiter an.

**Comment by MartinX3** [comment]
Dann seid bitte Intelligent und erstellt ein "Issue Template".
Das propagiert Github regelrecht, man kann sowas nicht übersehen.

Außerdem, Ich nutze Kodi 19.4 und 3.5.34. Es gibt sowas wie Autoupdate.

**Comment by Heptamer** [comment]
Und für den Kommentar ist hier Feierabend, dann sei bitte so intelligent und fix dein Problem selber. Beleidigen lassen müssen wir uns hier nicht.
