### ISSUE TITLE
kein einziger hoster funktioniert mehr

### ISSUE THREAD

**Issue by IkariDevGIT** [streamxstream/plugin.video.xstream#109]
im log steht immer nur: skipping unplayable item

**Comment by IkariDevGIT** [comment]
vor allem bei anicloud, da funzt garnichts

**Comment by Heptamer** [comment]
Da bei mir alles funktioniert, wären mal mehr Informationen und ein Log file angebracht, Glaskugel ist leider in der Werkstatt.

**Comment by IkariDevGIT** [comment]
lol, hier mein log: https://pastebin.com/A6RSsL2A

**Comment by Heptamer** [comment]
Xstream Version ist bei dir 3.5.29, aktuell sind wir bei 3.5.35. Musst dich daher nicht wundern wenn irgendwann nichts mehr läuft. Resolveurl ist auch steinalt, und xstream hast du auch nicht aus unserer repo installiert.

Von daher, Problem liegt bei dir. Besorg dir xstream aus unserer Originalrepo, aktualisiere auf die neueste Version, dann läuft wieder alles. Ich mach dann mal zu.

**Comment by IkariDevGIT** [comment]
nope, habe alles neu installiert(dieses mal mit der originalen repo, und nach anweisungen im faq)
immer  noch das gleiche. Hier mein neuer log: https://pastebin.com/RmPStEqD

**Comment by Heptamer** [comment]
Ich habe jetzt mal den Beispiel von SW S2E7 genommen, und konte sowohl unter Windows 10, Android und Linux die Folge mit den Hostern Voe, Dood und Streamtape abspielen. Ein problem innerhalb xstream liegt definitiv nicht vor.

Da wir nun sicher sein können das Du eine aktuelle version hast, ist mit im Log noch folgendes aufgefallen:
"
2022-08-07 21:09:21.614 T:11556   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.xstream/?site=anicloud_io&function=showHosters&title=2+-+Trying+Out+a+Party&trumb=https://aniworld.to//public/img/cover/my-isekai-life-stream-cover-nncM6ElxRDkVvcc2LyGzn1Lazm7jbr50_220x330.jpg&TVShowTitle=My+Isekai+Life&sSeason=1&sThumbnail=https%3A%2F%2Faniworld.to%2F%2Fpublic%2Fimg%2Fcover%2Fmy-isekai-life-stream-cover-nncM6ElxRDkVvcc2LyGzn1Lazm7jbr50_220x330.jpg&sUrl=https%3A%2F%2Faniworld.to%2F%2Fanime%2Fstream%2Fmy-isekai-life%2Fstaffel-1%2Fepisode-
"

Das bedeutet das entweder auf Deinem Windowsrechner Codecs fehlen, Du evtl. mit irgendwelchen Optimierungstools rumgespielt und Dir was zerlegt hast oder Du ein VPN benutzt dessern Server vom Anbieter geblockt werden. Mehr kanni ch dazu leider nicht sagen, das Problem ist aber rein bei Dir zu suchen.

**Comment by IkariDevGIT** [comment]
also der stand ist so: alle hoster funzen bei allen seiten AUßER Aniworld(anicloud) nur da funzt kein einziger hoster, könntest du das mal prüfen?

**Comment by Heptamer** [comment]
Moin, gerade mit Overlord S1E1 getestet, VOE und Streamtape laufen zum Beispiel, den Rest nicht ausprobiert aber wird genauso laufen.

Kontodaten hast du eingetragen in xstream für Aniworld? Kontrolliere das mal.

**Comment by IkariDevGIT** [comment]
hat absolut nichts geändert

**Comment by DWH-WFC** [comment]
Liegt meist an den Kontodaten. Überprüfe deine Daten nochmal unter addon_data/….xStream/settings.xml und teste das sie richtig sind ohne Leerzeichen. Versuch dich bitte mal im Browser damit nochmal anzumelden und über den Browser eine Serie zu starten.

**Comment by IkariDevGIT** [comment]
mit kontodaten ist alles ok, habe die 7 mal neu eingegeben. Funzt immer noch nichts.

**Comment by DWH-WFC** [comment]
Hast du diese im Browser überprüft laufen sie da auch?

**Comment by IkariDevGIT** [comment]
Ja geht alles im browser, habe dazu xstream nochmal 3 Mal neu installiert also kann es nicht daran liegen.
