### ISSUE TITLE
Kodi 19 Matrix now uses Python3...

### ISSUE THREAD

**Issue by darkestDark** [streamxstream/plugin.video.xstream#11]
so this Python2 Version doesnt work anymore...

**Comment by DWH-WFC** [comment]
Soweit bekannt wird an einem Upgrade für KODI 19 gearbeitet.

**Comment by streamxstream** [comment]
Ja es wird daran gearbeite, jedoch ist die aktuelle Kodi Stable noch immer Kodi18. Spätestetn wenn Kodi 19 Final erscheint, sollte auch xStream angepasst sein. Bis dahin bitte um Verständnis dass es zur Zeit nicht möglich ist

**Comment by darkestDark** [comment]
Bei einem developer branch würd ich auch ein paar scripte umschreiben und per pr einbringen...

**Comment by streamxstream** [comment]
Wenn dein angebot noch gilt, würde ich dich bitten einfach den PR in der nightly zu machen

**Comment by goceti** [comment]
Gibt es hier irgendwie Fortschritt? Bald kommt die erste Alpha von Kodi 19.

Es gibt auch Tools die das automatisch machen
https://python-future.org/futurize.html
https://python-future.org/futurize.html

**Comment by goceti** [comment]
`ResolveURL` has now also been made compatible with Python 3 using the `six` Python module. This could possibly also be an option for xStream.

https://github.com/jsergio123/script.module.resolveurl/commit/9e2f8e2b34d358084d6684dfe625088ce811fff1

@anis3 hast du vor xStream kompatibel mit Kodi 19 zu machen oder wirst du das Addon aufgeben?

**Comment by anis3** [comment]
@goceti

**Comment by anis3** [comment]
@goceti 
ja habe vor xStream kompatibel mit Kodi 19 zu machen
mir fehlt nur die zeit ich arbeite aber immer in hintergrund
daran weiß bis jetzt nicht was das beste ist py23(mit six)
oder ne 2te version nur python3 direkt mal sehn arbeite jedenfalls
an beide versionen denke aber es wird 2 versionen geben weil
der support mit py2 zu ende ist warum dann unnötig code???

LG Anis

**Comment by anis3** [comment]
hallo wer zeit lust & ahnung hat bitte testet
xStream mit kodi19
danke
LG Anis
