### ISSUE TITLE
Serienstream funktioniert nicht mehr seit nightly2. Und leider - auch wenn es funzt immer nur 1-2 Tage!!!

### ISSUE THREAD

**Issue by vigilant4u** [streamxstream/plugin.video.xstream#110]
Serienstream funktioniert nicht mehr seit nightly2. Un leider auch wenn es funzt immer nur 1-2 Tage!!!
Seit dem Zusammenspiel mit script.module.resolveurl funzt Serienstream fast gar nicht mehr.
Das automatische Update, das seit .35 eingebaut wurde findet immer so gut wie nie ein update, obwohl auf der offiziellen Resolver Seite: https://github.com/Gujal00/ResolveURL längst ein neuer fix bereit steht, den man dann manuell einspielen darf, damit Serienstream wieder funzt. 
Kurze Zeit  später gibt es dann ein neues "nightly" und schon funzt Serienstream erneut wieder nicht.
DAS IST GRAUENERREGEND NERVIG, weil die Lebensenergie von XSTREAM sich für die meisten gefühlt aus dem funktionieren von SERIENSTREAM speist. EXGREM NERVIG LEUTE. Kann man das nicht ein für alle Mal in den Griff bekommen?

**Comment by MartinX3** [comment]
Mir fehlt in xstream eine Diagnose Seite, die einen Test mit jedem gespeicherten Hoster durchführt und auflistet, welche gerade nicht funktionieren.

Oder als nächtlicher GitHub actions job über dessen Ergebnis wäre in der App abrufbar.

Am besten wäre es zusätzlich, wenn auf jedem Fehlerdialog ein Button zu dieser Diagnose Anzeige existieren würde.

So könnte man insgesamt automatisiert für die Entwickler und transparent für die Nutzer aufzeigen, wo es gerade hakt.

**Comment by Heptamer** [comment]
Ich finde so Beiträge wie deinen grauenerregend nervig. Von daher regst du dich jetzt erst mal ab und dann schreibst du in einem vernünftigen Ton, und vor allem mit Beispielen (welche Settings in xstream, welche Hoster getestet und alles andere was relevant ist) einen neuen Beitrag mit einer verständlichen Überschrift. Und dann schauen wir uns mal das generelle Problem, was komischerweise keinen anderen betrifft, mal an.
