### ISSUE TITLE
updatemamager kodi 18

### ISSUE THREAD

**Issue by herrdemo** [streamxstream/plugin.video.xstream#112]
offiziell unterstützt ihr zwar kein kodi 18 mehr
aber mit dieser kleinen änderung läuft auch das
update für den Resolver wieder ohne fehler

file: updatemamager - funktion: updateresolve

aktuell
shutil.unpack_archive(ADDON_PATH + '.zip', INSTALL_PATH)

new
if sys.version_info[0] == 2:
arc = zipfile.ZipFile(ADDON_PATH + '.zip')
arc.extractall(INSTALL_PATH)
arc.close()
else:
shutil.unpack_archive(ADDON_PATH + '.zip', INSTALL_PATH)

vielen dank im vorraus

**Comment by harryberlin** [comment]
mach doch eine PR.
generell kann man das sys.version_info[0] == 2 als Konstante deklarieren, zB.:
`PY2 = sys.version_info[0] == 2
.
.
if PY2:
    arc = zipfile.ZipFile(ADDON_PATH + '.zip')
    arc.extractall(INSTALL_PATH)
    arc.close()
else:
    shutil.unpack_archive(ADDON_PATH + '.zip', INSTALL_PATH)
.
.
`

**Comment by herrdemo** [comment]
hallo harry, 
ich habe mich nur dem quellqode angepasst und die function shutil.unpack_archive gibt es in kodi 18 leider nicht.

if sys.version_info[0] == 2:
    ADDON_DIR = translatePath(os.path.join('special://userdata/addon_data/', '%s') % resolve_id).decode('utf-8')
else:
    ADDON_DIR = translatePath(os.path.join('special://userdata/addon_data/', '%s') % resolve_id)

**Comment by DWH-WFC** [comment]
Werde mir das die Tage mal auf Kodi 18 ansehen. Bedenkt bitte aber das wir eigentlich kein Kodi 18 mehr supporten. da wir irgendwann dann auf Kodi 20 umsteigen.

**Comment by DWH-WFC** [comment]
3.5.36~nightly7
  14.10.22
  -[Movie4k]Domain Fix für Suchfunktion
			Qualität Anzeige hinzugefügt
  -[updatemanager.py] Fix Py2
