### ISSUE TITLE
[Feature Request] Weniger Benachrichtigungen beim Start

### ISSUE THREAD

**Issue by peat80** [streamxstream/plugin.video.xstream#115]
Wäre es evtl. möglich eine Option zum deaktivieren oder verringern der Startbenachrichtigungen zu xStream hinzuzufügen?

Ideal wäre wahrscheinlich wie Kodi selbst es mit den Updates beim Start macht.
Es wird im Hintergrund gesucht & dann erscheint nur eine Benachrichtigung wenn tatsächlich etwas aktualisiert wird.

Mit anderen Worten:
Nur Benachrichtigungen anzeigen wenn eine Aktualisierung erfolgt ist (oder ein Fehler beim Update auftritt) und die eigentliche Suche im Hintergrund durchführen.

Ist natürlich nur eine Anregung, kein Muss.
Danke dass dieses tolle Addon weiter gepflegt wird.
Die neue Nexus-Version find ich klasse.
Vielen Dank für eure Mühen. 😎👍

**Comment by DWH-WFC** [comment]
Könnte man als Option einbauen. Ob Benachrichtigung einfach oder voll angezeigt werden soll. Wird aber wenn dann nur in die neue Version übernommen wenn diese fertig ist, ist sie dann eh für Matrix und Nexus

**Comment by DWH-WFC** [comment]
In der Version 4.0.0~nightly2 jetzt enthalten. 
Bitte mal testen und Info per PN im Gitter Chat.
