### ISSUE TITLE
(Enhancement) 
Download-Freigabe für SMB Share

### ISSUE THREAD

**Issue by Sysdocalex** [streamxstream/plugin.video.xstream#117]

**Comment by kasi45** [comment]
Das ist ein Kodi internes Problem!
in den Settings mit der "folder" Option und dem daraus sich öffnenden Auswahldialog werden nfs und smb Share nicht gefunden.
in den settings ersetzen durch "text" Option!

![Unbenannt](https://user-images.githubusercontent.com/18262216/218579157-11436e4b-81ca-4ddc-a61a-ee0564121c49.JPG)


![Unbenannt](https://user-images.githubusercontent.com/18262216/218579346-f5479731-7a5a-40ef-bee9-84d1636d17cd.JPG)

**Comment by Sysdocalex** [comment]
Wenn im Dateimanager von Kodi die Netzwerkfreigabe deklariert wird, wird sie als Quelle gespeichert und für Kodi verfügbar gemacht. Im Xship Addon z.B. , wenn ich den Pfad auf das SMB Share setze, funktioniert der Download problemlos. Im TMDb Helper kann ich ebenso meine Bibliothek auf das Netzwerk auslagern.
Ich kann mir daher nicht vorstellen, dass es ein Kodi Problem sein kann

**Comment by kasi45** [comment]
Auswahlfenster im Dateimanager und die Auswahl in den settings bei folder option verhalten sich beide unterschiedlich.
Auch zwischen Android und Windoof ist das Verhalten unterschiedlich.
Immer ein Wechselspiel zwischen Client und Server. (OS)
In Kodi unter Settings/Services/ mal schauen welche Client Konfiguration für euren Server am besten passt.

In xStream muss auch mindestens eine Zeile im Code geändert werden.

PS: du weist wer den Code von xShip geschrieben hat? ;-)

**Comment by DWH-WFC** [comment]
Kasi THX für deine Unterstützung.
Problem in der nächsten Nightly gefixt.

**Comment by Sysdocalex** [comment]
Logisch weiß ich wer Xship geschrieben hat 😉 Es ist auch nach wie vor ein priorisiertes, nützliches Addon bei mir. Danke für deine Unterstützung!

PS: Sorry für die Diskrepanzen zwischen uns von damals...
