### ISSUE TITLE
Add freihafen.in support

### ISSUE THREAD

**Issue by rorar** [streamxstream/plugin.video.xstream#118]

**Comment by Bender2403** [comment]
Have looked at the page find because only downloads no streams

**Comment by MartinX3** [comment]
Without streams it's probably impossible to add

**Comment by DWH-WFC** [comment]
No Streams

**Comment by rorar** [comment]
Hi, happy new year folks 🎉
1. Open a movie page
2. Click on one of the download buttons - links are encrypted with encryption services.
3. For filecrypt.co there's most likely no captcha - for keeplinks.org you need to solve a Google ReCaptcha V3
4. Click on one of the https://userscloud.com/ Links
5. There you'll find the stream.

usercloud offers the best quality for archived video content in terms of stream quality I have ever seen, it's worth a look and hopefully an implementation :)

**Comment by DWH-WFC** [comment]
xStream funktioniert so nicht. Und somit ist es zu umständlich es wegen einer Seite umzusetzen.
