### ISSUE TITLE
Select Hoster 

### ISSUE THREAD

**Issue by Lod3355** [streamxstream/plugin.video.xstream#119]
Moin und erstmal ein Frohes neues Jahr wünsche ich dem Team. Ich habe da mal ne Frage, ich nutze bei xStream eigentlich immer die Automatische Hosterwahl. Habe manchmal aber  nen Hoster der nicht geht. Nun habe ich normal wie früher (xStream 3.5.....) das Kontextmenü geöffnet und suche vergebens den Menüpunkt "Select Hoster".
Ist dieser verschwunden? Wenn ja, ist es möglich diesen wieder hinzuzufügen??

Lieben Gruß und danke für eure Arbeit. Euer Team ist absolut genial.

**Comment by DWH-WFC** [comment]
Fixed in xStream 4.0.2~nightly2
