### ISSUE TITLE
[Feature] Compatibility with older Kodi

### ISSUE THREAD

**Issue by BenutzerEinsZweiDrei** [streamxstream/plugin.video.xstream#12]
Old phones and android boxes would be nice with this app.
Kodi is available with older versions for older phones.
But this plugin doesnt work no longer with Jarvis or Isengard.
Because of dependencie module.certifi

**Comment by streamxstream** [comment]
Das ist leider nicht möglich. Kodi wird ständig weiter entwickelt und das muss auch bei xStream sein, ansonst würde es mit neueren Versionen nicht mehr funktionieren. 
Da nicht unzählig viele Kodiversionen unterstütze werden können ist es daher leider nicht möglich xStream für ältere Kodiversionen anzupassen
