### ISSUE TITLE
Hoster Priorität setzen

### ISSUE THREAD

**Issue by eXim82** [streamxstream/plugin.video.xstream#122]
Wäre toll, wenn man, ähnlich wie im urlresolver, prioritäten von Hoster setzen kann. Beispiel möchte ich, dass Filemoon ganz am schluss kommt, da er bei mir oft nach vorn springt. Oder dass man andere bevorzugen kann. Vielen Dank.

**Comment by Heptamer** [comment]
Die FAQ Punkt 2.6 bzgl. Autoplay und Priorisierung hattest du gelesen?

**Comment by eXim82** [comment]
Ja, habe ich. Autoplay ist aktiviert, im URLResolver habe ich den Doodstream einen höheren Wert als 100 gegeben, da er niedriger priorisiert werden soll, ABER das wird komplett ignoriert. Auch wenn ich andere hoster einen niedrigeren Wert als 100 gebe, greifft das nicht. Resolver und Addon sind die Nightlys drauf.

**Comment by Heptamer** [comment]
Du musst die anderen Hoster niedriger priorisieren als 100.

**Comment by eXim82** [comment]
Ich habe mal Streamtape auf 10 gemacht im resolver. Es wird ignoriert.
Filemoon wird automatisch als erster genommen.

Heptamer ***@***.***> schrieb am Sa., 21. Jan. 2023, 10:42:

**Comment by Heptamer** [comment]
Ok dann erzähl mal welche KODi Version , xstream Version, ResolveUrl Version du hast und auf welchem Gerät/Betriebssystem KODi läuft.

**Comment by eXim82** [comment]
Kodi 20, xstream 4.0.2 nightly2, resolveurl 5.1.89 nightly2, sony
kd55xg8505, android tv 9

Probleme bestehen auch mit kodi 19 und den release builds von xstream und
resolveurl. Soeben getestet.

Heptamer ***@***.***> schrieb am Sa., 21. Jan. 2023, 18:23:
