### ISSUE TITLE
Hosterliste prüfen und sortieren geht nicht

### ISSUE THREAD

**Issue by eXim82** [streamxstream/plugin.video.xstream#123]
Sobald die Option aktiviert ist, kann man den Hoster micht mehr manuell auswählen. Die Hoster-Auswahl "Dialog" und "Listenansicht" funktioniert auch nicht mehr. Aktuellstes xstream und resolveurl nightly mit Kodi 20. War auch mit den vorherigen release so. Eventuell hat es einen Zusammenhang mit dem Issue bezüglich Prioritätenliste, welches ich schon platzierte.

**Comment by Heptamer** [comment]
Mit dem neuesten Nightly behoben
