### ISSUE TITLE
Abspielstatus wird bei manueller Hosterauswahl nicht gespeichert

### ISSUE THREAD

**Issue by eXim82** [streamxstream/plugin.video.xstream#124]
Danke für das absolut tolle plugin. Ich melde fehler, weil ich das plugin so mag und nicht umgekehrt :-)

**Beschreibe den Fehler**
Es wird nicht gespeichert wo die letzte Position des abgespielten Streams war oder ob schon abgespielt. Das passiert nur bei der manuellen Hosterauswahl. Beim automatischen abspielen oder Dialogansicht funktioniert das. (Listeansicht geht nicht mehr)

**Zum Reproduzieren**
Schritte um den Fehler Nachtzustellen:
1. Menüauswahl des Streams öffnen. Am besten eine Serie und die Ansicht auf 'WideList'
2. Kilcke auf 'Bitte Hoster Auswählen'
3. Hoster auswählen
4. Auf einer Stelle in der mitte des Streams springen oder kurz vor dem ende des streams,
5. Stream stoppen

**Erwartetes Verhalten**
Es müsste bei der WideList ansicht nun ein statusicon stehen, ob gesehen (Haken) oder noch nicht (Halbkreis)

**TV (Bitte die folgenden Infos vervollständigen):**
 - Android TV 9
 - Kodi 20
 - xStream 4.0.2 nightly6
 - ResolveURL 5.1.89 nightly6

**Zusätzliche Informationen**
Problem war schon mit den älteren nightleys vorhanden und Kodi 19. Weiss nicht ab wann es nicht mehr funktionierte.

**Comment by Heptamer** [comment]
Welchen Skin benutzt du, weil du schreibst dass Listenansicht nicht funktioniert?

**Comment by eXim82** [comment]
Ich benutze den vorinstallierten Skin. Estuary glaube ich heisst er.

Heptamer ***@***.***> schrieb am Do., 26. Jan. 2023, 08:10:

**Comment by DWH-WFC** [comment]
Also in Estuary und 3 anderen Skins habe ich gerade die Listenansicht getestet. Geht ohne Probleme auf Win wie Android.

**Comment by DWH-WFC** [comment]
Serie Listenansicht
<img width="960" alt="1" src="https://user-images.githubusercontent.com/45105289/214875506-f8e0e010-fb8b-4983-b88d-9377d6db0fd6.png">
 gesehen Status geht auch

**Comment by DWH-WFC** [comment]
Serie Dialogansicht 
<img width="960" alt="1" src="https://user-images.githubusercontent.com/45105289/214876250-83803dee-b1c0-49de-9cac-08cc4c38d538.png">

**Comment by DWH-WFC** [comment]
Serie automatisch geht auch
<img width="960" alt="1" src="https://user-images.githubusercontent.com/45105289/214877161-9807aac2-18ac-4f97-8b70-0f028bd7d655.png">

**Comment by eXim82** [comment]
Das funktioniert. Aber versuch mal, wenn du den Hoster manuell auswählst.
Bei mir wird der Status dann nicht gespeichert.

Am Do., 26. Jan. 2023 um 16:30 Uhr schrieb DWH-WFC ***@***.***

**Comment by eXim82** [comment]
Die Listenansicht geht nun wieder. Aber zum eigentlichen problem: Ich gehe
zu einer serie, halte menü oder OK taste gedrückt halten, "bitte hoster
auswählen", einen auswählen und schauen. Wenn nun der stream zu ende ist,
markiert es nicht als "abgespielt" oder merkt sich meine letzte position
nicht. Bei automatisch abspielen klappt das oder bei der
dialoauswahl/listenauswahl.

DWH-WFC ***@***.***> schrieb am Do., 26. Jan. 2023, 20:49:

**Comment by Heptamer** [comment]
Das was du da beschreibt gibt es nicht. Bitte Screenshot!

**Comment by eXim82** [comment]
Heptamer ***@***.***> schrieb am Fr., 27. Jan. 2023, 00:18:

**Comment by DWH-WFC** [comment]
Ich glaube er meint das Kontextmenü. Dieser Hoster Zusatz ist für Playlisten und hat nichts damit zu tun. Geh mal bitte auf wiedergeben und wähle dann eine Hoster wenn das Popup erscheint

**Comment by Heptamer** [comment]
Im Kontextmenü habe ich das auch nicht gefunden, wäre auch neu das man darüber Hoster auswählen kann.

**Comment by DWH-WFC** [comment]
Doch ist im Kontextmenü das war früher zum Abspielen für Playlisten die Funktion funktioniert auch aber da wird kein Haken gesetzt das ist mit Absicht so gemacht wurden. 

Wenn er auf Wiedergeben klickt dann funktioniert auch alles was er möchte 👍 
Deswegen kann es auch "Closed" werden

**Comment by Heptamer** [comment]
Dann machen wir hier mal zu
