### ISSUE TITLE
Feature Anfrage: Option in den Einstellungen bezüglich Sortierung oder Ausblendung nicht deutschsprachiger "Hoster"

### ISSUE THREAD

**Issue by papandy** [streamxstream/plugin.video.xstream#125]
Ich wollte fragen ob es möglich wäre eine Option in den Einstellungen einzufügen, mit der man nicht deutschsprachige Streams entweder ausblenden oder alternativ ganz nach "hinten" sortieren kann.
Das wäre bei von Vorteil bei der Nutzung der Autoplay-Funktion mit Hostersortierung wenn deutsch und z.bsp. Englisch auf dem gleichen Hoster liegen. Wenn der deutsche Steam ein "Problem" hat wird sonst der englische gestartet und man muss abstoppen und Autoplay deaktivieren um manuell den nächsten deutschen Stream zu wählen.

Beispiel: Serienstream: meistens Streamtape, Doodstream, Voe je einmal deutsch und einmal englisch.

**Comment by DWH-WFC** [comment]
Funktioniert schon bei einigen Siteplugins die die sLang Funktion nutzen das man in den Einstellungen die gewünschte Sprache setzen kann. Ist aber bei s.to noch nicht enthalten.

**Comment by papandy** [comment]
Das hört sich doch gut an. Vielen Dank für eure Mühen. Ihr seid echt Gold wert!

**Comment by DWH-WFC** [comment]
Ein Auswahl der Sprache des wenn du in den Einstellungen Deutsch wählst auch nur deutsche Links angezeigt werden, ist in Arbeit. Aber das alle Hoster in der Sprache als Prio ausgegeben werden ist nicht in Planung.
Nur wenn du eine Sprache wählst und diese verfügbar ist wird dir der Hoster auch angezeigt.

**Comment by papandy** [comment]
Perfekt! Vielen Dank.

**Comment by DWH-WFC** [comment]
Kommt mit der nächsten Nightly von daher Closed
