### ISSUE TITLE
"Anicloud" Deutsche Subs Folgen werden nicht angezeigt

### ISSUE THREAD

**Issue by Kekd570** [streamxstream/plugin.video.xstream#126]
Auf der Anicloud-Seite ist es möglich, Folgen mit japanischem Dub mit deutschen Untertiteln anzusehen (Untertitel ist in der Folge, also kein Add-on oderso), aber genau diese Folgen werden auf Xstream in der Liste nicht angezeigt.

**Comment by MirkoMettendorf** [comment]
Doch die sind nur falsch beschriftet, sind die english mit sub Folgen

**Comment by Heptamer** [comment]
Und wenn man jetzt noch die ganzen Infos wie Versionen, Schritte zum reproduzieren etc hätte könnte man da auch mal reinschauen.

Bitte das Template zum Fehler melden nutzen und auch ausfüllen, und nicht einfach was - schreiben. Hat seinen Grund das wir das alles wissen wollen, eben um so nachfragen wie jetzt zu vermeiden. Daher ist hier nun zu.
