### ISSUE TITLE
Fehler Melden: Aniworld Hostersprache

### ISSUE THREAD

**Issue by MirkoMettendorf** [streamxstream/plugin.video.xstream#128]
**Beschreibe den Fehler**
Bei Aniworld ist die Beschriftung der Sprache in der Hosterliste falsch. 
Dort wird Deutsch, Englisch und Englisch mit Untertitel angezeigt.

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Stelle in Settings Hosterauswahl auf nicht automatisch
2. Klicke beliebige Serienfolge in Aniworld an.
3. warte bis Hosterliste angezeigt wird.

**Erwartetes Verhalten**
Die angezeigten Sprachen sollten Deutsch, Japanisch mit englischem Untertitel und Japanisch mit deutschem Untertitel lauten.

**Screenshots**
![2023-02-04 16_20_29-Kodi](https://user-images.githubusercontent.com/48807598/216775385-5e7773c0-a7f0-4564-95be-5b85b1dc66fe.png)
![2023-02-04 16_21_21-Episode 1 Staffel 1 von Chainsaw Man _ AniWorld to - Animes gratis legal online ](https://user-images.githubusercontent.com/48807598/216775408-fee787d2-0daa-43f2-b088-004512d6a76d.png)

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: [Mi Tv 4k Stick, Android TV 11]
 - Kodi Version: [Kodi 20]
 - Xstream Version: [z.B. 4.0.3~nightly3]
 - Resolver Version: [z.B. 5.1.88]

**Comment by Heptamer** [comment]
Danke für die Fehlermeldung, sehr vorbildlich ausgefüllt!

**Comment by DWH-WFC** [comment]
Sehr schön damit kann man was anfangen.
Aniworld wurde damals nur als Ableger für s.to geschrieben.
Da wurden auch nur die Hoster Funktionen Deutsch und English mit übernommen.

**Comment by DWH-WFC** [comment]
Gibt es dort auch Animes mit Englischer Sprache?
Oder nur 
Deutsch
Japanisch mit deutschem Untertitel
Japanisch mit englischem Untertitel

**Comment by MirkoMettendorf** [comment]
Nein mit englischer Sprache gibt es nicht

**Comment by DWH-WFC** [comment]
[aniworld.zip](https://github.com/streamxstream/plugin.video.xstream/files/10610608/aniworld.zip)

Teste mal bitte die Datei ob es jetzt hinhaut.

**Comment by MirkoMettendorf** [comment]
Deutscher Untertitel und englischer Untertitel sind vertauscht, ansonsten passt es.

**Comment by MirkoMettendorf** [comment]
und es müsste glaub ich "japanisch mit deutschem" und "japanisch mit englischem" Untertitel heißen.

**Comment by DWH-WFC** [comment]
vertauscht?

**Comment by DWH-WFC** [comment]
Ach hast Recht ja ändere ich noch

**Comment by DWH-WFC** [comment]
Zwecks Ausdruck n oder m war ich mir auch noch nicht sicher. Auf Aniwold in den Einstellungen des Accounts steht es mit n.

**Comment by DWH-WFC** [comment]
[aniworld.zip](https://github.com/streamxstream/plugin.video.xstream/files/10610678/aniworld.zip)

So jetzt sollte es aber richtig sein.

**Comment by MirkoMettendorf** [comment]
> Zwecks Ausdruck n oder m war ich mir auch noch nicht sicher. Auf Aniwold in den Einstellungen des Accounts steht es mit n.

Ja das ist weil das dort als plural steht.

**Comment by MirkoMettendorf** [comment]
> [aniworld.zip](https://github.com/streamxstream/plugin.video.xstream/files/10610678/aniworld.zip)
> 
> So jetzt sollte es aber richtig sein.

Ja jetzt passt alles. Danke

**Comment by DWH-WFC** [comment]
ok dann kommt es in die Nightly und kann hier closed werden.
