### ISSUE TITLE
Feature Anfrage weitere Prioeinstellung für Hostersprache

### ISSUE THREAD

**Issue by MirkoMettendorf** [streamxstream/plugin.video.xstream#129]
**Bezieht sich die Feature-Anfrage auf ein Problem? Bitte beschreiben**
Würde gerne immer die Automatische Hosterauswahl nutzen, aber dazu fehlen mir ein paar Einstellungen um die Priorisierung zu steuern.

**Beschreibe eine Lösung die du gerne haben möchteste**
Die möglichkeit einzustellen, das englisch mit Untertitel vor Englisch genommen wird, wenn die preferred language nicht vorhanden.
Bzw.  einfach einstellpunkt für 2. preferred language. 

Wenn in den resolversettings die Prio für ein Hoster höher gestellt ist, aber der Hoster nicht die preferred language hat, wird der Hoster trotzdem priorisiert. Eine Einstellmöglichkeit die die sprache prio über der Hosterpriorisierung stellt wäre praktisch.

**Comment by DWH-WFC** [comment]
Das ist nicht so einfach weil es sich meines erachtens nicht auslesen lässt. Du kannst den Hoster priorisieren aber die Sprache nicht. Wenn der Hoster expliziert die Sprache wieder gibt so wie zum Beispiel bei Aniworld und s.to dann ist (wenn die Funktion implementiert wird) wenn deutsch eingestellt er nur deutsche Links mit Hoster Prio in der Reihenfolgen ablegt und den rest ausblendet.

**Comment by MirkoMettendorf** [comment]
Hab mir den Code mal angeschaut, die hosterprio passiert ja in der __getPriorities(). Und da ist ja die Hosterliste drin, wo die Hoster in der Form {'link': sUrl, 'name': sName, 'displayedName': '%s %s %s' % (sName, sQualy, sLang)} sind. Da könnte man das sLang doch theoretisch auslesen (so wie der hostername in der stream methode) und dann die sortierung der Hosterliste über die Sprache und die Hosterprio machen.

**Comment by DWH-WFC** [comment]
pass auf ich hab es jetzt so.
In den Einstellungen kannst du die Sprache einstellen.
Wählst du deutsch werden dir nur deutsche Links angezeigt. 
Die Prio der Hoster machst du ja in den ResolveURL Einstellungen.
Stellst du es auf Japanisch werden dir nur die Japanischen Links ausgegeben.
Die Auswahl ob mit englischen oder japanischen Untertiteln gibt es nicht bzw. ist nicht geplant bzw ob überhaupt sinnvoll

**Comment by MirkoMettendorf** [comment]
ok, ja das versteh ich, aber grade bei aniworld, weiß nicht wie oft andere Seiten noch Untertitel haben, fände es aber praktischer wenn man in den settings  einstellen könnte das nach Deutsch, Japanisch mit deutschem Untertitel in der Hosterreihenfolge kommt, bei anderen Seiten dann halt Englisch mit deutschem Untertitel. Dann ist auch die hosterliste übersichtlicher. Im Moment ist das ja nach Hoster sortiert und die Sprachen sind durcheinander. Und nicht durch die gewählte Sprache alle anderen ausgeblendet werden, weil wenn ich deinen 2. letzten Satz richtig verstehe, wird dann im moment wenn ich zum beispiel auf deutsch stelle und es gibt kein Deutsch gar nichts angezeigt? Und für den Fall wäre ein 2ter Filter praktisch, bzw. eine Sortierung.

**Comment by DWH-WFC** [comment]
ja dem ist gerade so wenn deutsch dann nur deutsche Links.
oder man stellt auf alle Sprachen.

**Comment by DWH-WFC** [comment]
[plugin.video.xstream.zip](https://github.com/streamxstream/plugin.video.xstream/files/10611041/plugin.video.xstream.zip)


Bitte mal testen. Neustart ist von nöten da neue Sprachinhalte dazu kamen  und Sprach IDS wurden geändert.

**Comment by MirkoMettendorf** [comment]
ja die preferred language funktioniert. Würde es gehen, das man einfach fest die reihenfolge von Japanisch mit englischem Untertitel und japanisch mit deutschem Untertitel tauscht? in der aniworld.py showHoster() vor dem return ? Das würde mir erstmal reichen.

**Comment by DWH-WFC** [comment]
Nein da er ja den Code nacheinander weg liest. Dafür müsste man sie nach dem auslesen erst neu anordnen und dann nochmal in der Liste anzeigen.

**Comment by MirkoMettendorf** [comment]
ah ja stimmt, da hab ich nicht dran gedacht. ok dann würde nur ganz weglassen von englisch sub funktionieren.

**Comment by MirkoMettendorf** [comment]
hab jetzt mal etwas rumprobiert also so wird nach sprache und dann nach hosterprio sortiert und japanisch mit englisch und deutsch hab ich auch noch getauscht. 

aniworld.py
`def showHosters():
    hosters = []
    params = ParameterHandler()
    # Spracheinstellung aus der settings.xml
    sLanguage = cConfig().getSetting('prefLanguage')
    if sLanguage == '1':  # 1 = Deutsch
        sLangCode = '1'
    elif sLanguage == '3':	# 3 = Japanisch mit EN Sub
        sLangCode = '2'
    elif sLanguage == '3':	# 3 = Japanisch mit DE Sub
        sLangCode = '3'
    else:
        sLangCode = '0' # 0 = Alle Sprachen
    params.setParam('sLanguage', sLangCode)
    sUrl = ParameterHandler().getValue('sUrl')
    sHtmlContent = cRequestHandler(sUrl).request()
    pattern = '<li[^>]*data-lang-key="([^"]+).*?data-link-target="([^"]+).*?<h4>([^<]+)<([^>]+)'
    # data-lang-key="1" Deutsch
    # data-lang-key="2" Japanisch mit englischen Untertitel
    # data-lang-key="3" Japanisch mit deutschen Untertitel
    isMatch, aResult = cParser.parse(sHtmlContent, pattern)
    if isMatch:
        for sLangCode, sUrl, sName, sQualy in aResult:
            sLanguage = cConfig().getSetting('prefLanguage')
            # Deutsch
            if sLanguage == '1':
                if '2' in sLangCode:
                    continue
                if '3' in sLangCode:
                    continue
                if sLangCode == '1':
                    sLang = 'Deutsch' 
            # Englisch
            if sLanguage == '2':
                    continue                      
            # Japanisch        
            if sLanguage == '3':
                if '1' in sLangCode:
                    continue
                if sLangCode == '2':
                    sLangCode = '3'
                    sLang = 'Japanisch mit englischen Untertitel'
                elif sLangCode == '3':
                    sLangCode = '2'
                    sLang = 'Japanisch mit deutschen Untertitel'
            # Alle Sprachen
            if sLanguage == '0': 
                if sLangCode == '1':
                    sLang = 'Deutsch'
                if sLangCode == '2':
                    sLangCode = '3'
                    sLang = 'Japanisch mit englischen Untertitel'
                elif sLangCode == '3':
                    sLangCode = '2'
                    sLang = 'Japanisch mit deutschen Untertitel'
            # Qualität        
            if 'HD' == sQualy:
                sQualy = 'HD'
            else:
                sQualy = 'SD'
            hoster = {'link': sUrl, 'name': sName, 'displayedName': '%s %s %s' % (sName, sQualy, sLang),
                      'languageCode': sLangCode}
            hosters.append(hoster)
        if hosters:
            hosters.append('getHosterUrl')
        if not hosters:
            cGui().showLanguage()
        return hosters`

hoster.py
`#After sorting Quality, we sort for Hoster-Priority :) -Hep 24.01.23
        ranking = sorted(ranking, key=lambda ranking: (ranking[1]["languageCode"],ranking[0]))`

![2023-02-05 16_34_05-Kodi](https://user-images.githubusercontent.com/48807598/216828837-c5bf9fd9-e1ad-4a86-afea-e31937431b9d.png)

**Comment by DWH-WFC** [comment]
Hehe den gleichen Gedanke hatte ich vorhin auch.
Werde das noch für s.to mit fertig machen und dann in die Nightly schieben

**Comment by DWH-WFC** [comment]
deine Prio der sprache verursacht bei alles anderen Siteplugins einen Fehler da diese keine Funktion haben

**Comment by MirkoMettendorf** [comment]
Ah ja mach sinn. Weil in der hoster.py 
Über den 'languagecode' sortiert wird und der ist ja nur in aniworld drin. Da müsste man das noch über ein if statement abfangen wenn das nicht da ist und dann nur über die hosterprio sortieren.
Bin Grad nicht Zuhause kanns also nicht ausprobieren

**Comment by DWH-WFC** [comment]
Da ab morgen meine Arbeitswoche wieder beginnt mach ich erstmal alles fertig ohne Lang Prio.

**Comment by MirkoMettendorf** [comment]
[hoster.zip](https://github.com/streamxstream/plugin.video.xstream/files/10614032/hoster.zip) Damit geht es.

Kein Stress. Sobald du wieder Zeit hast kannst du es ja hinzufügen.

**Comment by DWH-WFC** [comment]
Kurz getestet bringt bei Dokus4me einen Fehler in Bezug auf deinen Code.
Vielleicht kannst du nochmal drüber schauen hab leider keine Zeit dafür.
Nur so kann ich es erstmal nicht freigeben.

**Comment by MirkoMettendorf** [comment]
[hoster.zip](https://github.com/streamxstream/plugin.video.xstream/files/10668603/hoster.zip)

**Comment by DWH-WFC** [comment]
In xStream 4.0.3~nightly6 enthalten.
