### ISSUE TITLE
Feat. Anfrage | Adding streamkiste.tv

### ISSUE THREAD

**Issue by X-Nightmare-X** [streamxstream/plugin.video.xstream#13]
Ich würde mir wünschen, dass ihr noch die Seite streamkiste.tv hinzufügt, sowie bs.to.
Bin mir gerade nicht sicher ob bs.to schon drin ist.
Aber streamkiste.tv wäre absolut traumhaft.

Bisher keine so eine gute Seite wie diese gesehen.
Vor allem, alles auf Deutsch und einfach aufzurufen.
Ohne großartigen Schnick-Schnack.
Ich würde es ja selber rein programmieren, aber dafür hab ich davon zu wenig Ahnung.

**Comment by DWH-WFC** [comment]
Hat eine Captcha Abfrage und somit ist es derzeit nicht möglich die Seite aufzunehmen.
