### ISSUE TITLE
Fehler Melden Jahreszahl in Titel bei s.to wird nicht angezeigt

### ISSUE THREAD

**Issue by MirkoMettendorf** [streamxstream/plugin.video.xstream#131]
**Beschreibe den Fehler**
Die Serientitel bei s.to haben manchmal eine Jahreszahl in Klammer noch hintendran. Diese wird bei den Suchergebnissen einfach weggelassen

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Gehe zu serienstream
2. Suche nach "Baki"
3. Zeigt 2 Ergebnise mit Baki an

**Erwartetes Verhalten**
Sollte Baki und Baki (2018) anzeigen

**Screenshots**
![2023-02-11 10_55_36-Serien _ ❤ S to - Serien Online gratis ansehen   streamen – Mozilla Firefox](https://user-images.githubusercontent.com/48807598/218252047-db8d3f67-eb89-4ab0-a123-7322ff60f5fa.png)

![2023-02-11 10_56_53-Kodi](https://user-images.githubusercontent.com/48807598/218252059-c3921d1c-5253-467a-b802-c54a01794285.png)

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: [Windows 11]
 - Kodi Version: [Kodi 20]
 - Xstream Version: [neueste nightly]

**Zusätzliche Informationen**
Das Problem ist warscheinlich, dass das  Regex Klammern rausfiltert.

**Comment by DWH-WFC** [comment]
Danke für die Info. wir werden das überprüfen.

**Comment by kasi45** [comment]
meinst du so?
![Unbenannt](https://user-images.githubusercontent.com/18262216/218515887-7a9bdbb0-9f3b-49cc-aabe-fa5feecc5205.JPG)

**Comment by MirkoMettendorf** [comment]
Das zweite, also nicht immer, sondern nur wenn es auch bei s.to im Titel steht

**Comment by DWH-WFC** [comment]
Thx @ Kasi für die Lösung wird in der nächsten Nightly mit veröffentlicht.

**Comment by DWH-WFC** [comment]
Dann stimmt der Rest der Siteplugin s aber nicht

![AFCFD958-EB70-4A4C-9185-634AB088C7D6](https://user-images.githubusercontent.com/45105289/218553938-156e3683-7b17-4ce0-b766-a710ca112899.jpeg)

**Comment by kasi45** [comment]
globale suche sieht bei mir so aus:

![Unbenannt](https://user-images.githubusercontent.com/18262216/218564199-3c827b23-6624-4d44-85f9-4eea38b71f74.JPG)

ich teste gleich noch mal mit der aktuellen nightly version

**Comment by kasi45** [comment]
leeres kodi 19 mit aktueller nightly xstream (download als zip) installiert.
einzige Änderung nach der Installation in guiElement.py:

        if self._sYear: self.__sTitle = self.__sTitle.strip() + ' (' + self._sYear + ')'
        return self.__sTitle.strip()
![Unbenannt](https://user-images.githubusercontent.com/18262216/218567438-62d5e893-7cd6-4dbe-9686-b2dfbbe4bd6c.JPG)

Bildhintergrund blau - Kodi20
Bildhintergrund braun - Kodi19

**Comment by DWH-WFC** [comment]
Ok ich check es nochmal

**Comment by DWH-WFC** [comment]
Ich bitte um Verzeihung du hast recht irgendwas hat in meinem Dev nicht hingehaut jetzt wird es richtig angezeigt.
