### ISSUE TITLE
Fehler Melden

### ISSUE THREAD

**Issue by Stivan101** [streamxstream/plugin.video.xstream#133]
Es werden Bei serienstream keine hoster mit der Deutschen syncro angezeigt sondern nur noch Englische 

Alles funktioniert es ist nur so das man nur  noch die Episoden in englisch zur Auswahl  angezeigt werden.

**Comment by DWH-WFC** [comment]
Stande groß und breit mit roter Farbe im Changelog.

https://raw.githubusercontent.com/streamxstream/plugin.video.xstream/matrix/changelog.txt

stand in allen Versionen ob Nightly oder Release.
