### ISSUE TITLE
Streams von Serienstream lassen sich nicht abspielen

### ISSUE THREAD

**Issue by Loaweo** [streamxstream/plugin.video.xstream#134]
**Beschreibe den Fehler**
Erstmal sorry, weil ich vermute das es nicht direkt am Plugin liegt und kein globales Problem ist, allerdings habe ich auch keine Lösung nach mehreren neuinstallationen und weiteren Recherchen gefunden.
Es lassen sich bei mir keine Streams von Serienstreams abspielen. Bei anderen Plattformen funktioniert es teilweise, wobei auch dort manchmal der Fehler auftritt. Habe erstmal die Vermutung gehabt das es an bestimmten Hostern liegt oder die Datei down ist. Allerdings ist dies nicht der Fall. Der gleiche Hoster funktioniert auf anderen Plattformen, während er auf Serienstream nicht funktioniert. Vielleicht liegt das irgendwie an der Datei das der FireTV damit Probleme hat oder irgendein Codec fehlt. Dabei konnte ich allerdings nichts finden wie ich das löse.

Hab Kodi und das Plugin nach der Anleitung von Kodi Tipps installiert.

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Über Serienstream direkt gesucht oder die Globale Suche benutzt, hab aber auch ohne Suche mich einfach durch die Empfehlungen geklickt.
2. Bin alle Hoster durchgegangen

**Erwartetes Verhalten**
Es wird entweder ein Fenster angezeigt mit Playback failed und das man den Log Prüfen soll oder es wird garnichts angezeigt und man bleibt einfach im Menü. Der Fehler im Log bleibt aber trotzdem gleich

**Screenshots**
Siehe Log, hab den Debbug Modus auch aktiviert.
[kodi.log](https://github.com/streamxstream/plugin.video.xstream/files/10741696/kodi.log)

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: Fire TV Stick 4K (Aktuellstes Modell)
 - Kodi Version: Kodi v20
 - Xstream Version: 4.0.3
 - Resolver Version: resolveurl v5.1.91

**Comment by DWH-WFC** [comment]
Hast du ein Konto für Serienstream.to angelegt und die Kontodaten auch in xStream abgelegt?

Hier sind nochmal unsere FAQ zum nachlesen.

https://github.com/streamxstream/xStream-FAQ/blob/master/xStream_Anleitung_FAQ.md

**Comment by DWH-WFC** [comment]
Welche Sprache hast du in den xStream Einstellungen gesetzt?

**Comment by Loaweo** [comment]
Zum ersten: Ich nutze einen VPN bei dem FireTV Stick. Hab es jetzt auch mal mit ner anderen DNS Einstellung versucht um auszuschließen das es am VPN liegt. Gleiches Problem.
Zum zweiten: Kontodaten sind abgelegt
Zum dritten: bei der Contentsprache habe ich "all", bei TMDB habe ich "German"

**Comment by DWH-WFC** [comment]
Ich sehe gerade gestern hast du VOE genutzt. Stelle mal bitte zum Test in den xStream Einstellungen den Resolver auf Nightly. Starte Kodi neu und rechts oben sollte dann angezeigt werden das der Nightly Resolver installiert wurde. und teste dann bitte maal eine Serienstream Serie. Mit Streamtape oder VOE

**Comment by Loaweo** [comment]
Hab es soeben getestet. Leider funktioniert dies auch nicht. Hab auch gleich mal die Nightly Version von xStream getestet. Das gleiche Ergebnis. Vielen Dank dir übrigens für die Geduld bei der Hilfe.

**Comment by DWH-WFC** [comment]
Funktionieren alle Hoster nicht? Welchen Internet Anbieter hast du denn hast du ohne VPN mal probiert?

**Comment by Loaweo** [comment]
Über Serienstream funktionieren alle Hoster nicht. Über Kinox zum Beispiel funktionieren die Hoster. Zum Beispiel Streamtape funktioniert auf Kinox, auf Serienstream allerdings nicht obwohl die Streams nicht down sind. Sie haben auch das gleiche Format (mkv.mp4).
Hab es auch ohne VPN probiert und den DNS Eintrag auf Cloudflare geändert, da mein Provider mitglied der CUII ist und dementsprechend über deren DNS blockt.

**Comment by DWH-WFC** [comment]
dann ist es ein Account Problem. Erstelle mal bitte über s.to einen neuen Account. Geht fast jede Fake Email.

**Comment by DWH-WFC** [comment]
Gibt es Erfolge zu deinem Problem???
