### ISSUE TITLE
Fehler Melden

### ISSUE THREAD

**Issue by Priv-P** [streamxstream/plugin.video.xstream#135]
Film springt bei abspielen vor (ca 5-10sek würde ich schätzen)

Nvidia shield
Kodi 20 Nexus
Xstream 4.04 nightly 1
Resolver url 5.1.91
Xstream repo 1.2.0

ich habe einen Film (gib dem Affen Zucker) bei xstream über die globale Suche gesucht.
Habe den Film dann gestartet über den Hoster Cinemathek 1 ( sonst gab es nurnoch cinemathek 2 ,aber da kommt ein Fehler). Der Film startet auch aber er springt immer ein Stückchen nach vorne,d.h. Man würde nicht 1 std den Film schauen sondern er wäre nach ca 30 min schon zu Ende.

dsnke und Gruß
Sev

**Comment by DWH-WFC** [comment]
Bitte aus Stream 2 ausweichen. Filemoon macht bei vielen Probleme vielleicht liegt es am Codec. Wir haben wie gesagt kein Einfluss darauf. Du kannnst dies gerne bei Guial als Issue einreichen.

https://github.com/Gujal00/ResolveURL/issues/new/choose

Vielleicht gibt es da weitere Erkenntnisse zu deinem Problem.
