### ISSUE TITLE
AniWorld und funktioniert bei mir nicht

### ISSUE THREAD

**Issue by Huti123** [streamxstream/plugin.video.xstream#136]
Wenn ich bei Aniworld versuche eine serie zu gucken kommt unten rechts immmer eine Meldung, dass es keinen Eintrag in der ausgewählten sprache gibt.

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Gehe zu 'AniWorld'
2. Klicke auf 'Beliebte Serien'
3. Scrolle hinunter bis 'BlueLock, Staffel 1, Ep 19'
4. siehe Fehler

**Erwartetes Verhalten**
Davor kam immer eine Hoster auswahl.

**Technische Informationen**
 - Hardware und Betriebssystem: [Android 13]
 - Kodi Version: [Kodi 20]
 - Xstream Version: [4.0.4~nightly4]
 - Resolver Version: [5.1.9.3~nightly5]

**Video**
https://user-images.githubusercontent.com/125929547/220209058-bc1f5c3a-ab10-4b6c-9872-0d6f1adec7c8.mp4

**Comment by DWH-WFC** [comment]
Stelle bitte in den Einstellungen von xStream die Sprache von Englisch auf Deutsch oder alle Sprachen um.

**Comment by Huti123** [comment]
Das hat geholfen Danke.
