### ISSUE TITLE
Filmpalast: Kategorie FILME öffnet nicht

### ISSUE THREAD

**Issue by TitanME** [streamxstream/plugin.video.xstream#137]
**Beschreibe den Fehler**
Auf der Startseite ´von Filmpalast öffnet die Kategorie "Filme" nicht!

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Gehe zu 'Filmpalast'
2. Klicke auf 'Filme'

**Erwartetes Verhalten**
Nichts passiert!

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: [Windows & Android
 - Kodi Version: [Kodi 19.5 & Kodi 20.0]
 - Xstream Version: [4.0.4~nightly4]
 - Resolver Version: [5.1.92]

[kodi.log](https://github.com/streamxstream/plugin.video.xstream/files/10788272/kodi.log)
]

**Comment by DWH-WFC** [comment]
Welche Spracheistellung in xStream nutzt du denn?

**Comment by Heptamer** [comment]
Problem wurde mit nightly5 behoben
