### ISSUE TITLE
Filmpalast: Genre [Komödie] mit Fehlermeldung

### ISSUE THREAD

**Issue by TitanME** [streamxstream/plugin.video.xstream#138]
**Beschreibe den Fehler**
Auf Filmpalast wird bei der Auswahl Genre "Komödie" ein Fehler ausgeworfen

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
Filmpalast > Filme > Genre > Komödie

**Erwartetes Verhalten**
Fehlermeldung!

**Screenshots**
Siehe unten

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: Windows & Android
 - Kodi Version: Matrix & Nexus
 - Xstream Version: 4.0.4~nightly5
 - Resolver Version: 5.1.92

![A1](https://user-images.githubusercontent.com/65415236/220470336-8b45832f-a002-4fff-9b44-5875291d458b.jpg)

**Comment by Heptamer** [comment]
Wurde heute mit nightly6 gefixt
