### ISSUE TITLE
Unplayable item bei aniworld

### ISSUE THREAD

**Issue by Maxxxel** [streamxstream/plugin.video.xstream#139]
Egal welchen Stream ich bei Aniworld starten möchte, es erscheint immer die Fehlermeldung "skipping unplayable item: 0

Xstream 4.0.4-nightly6
Philips (Android TV) mit Kodi 20
Resolveurl v5.1.93-nightly5
Account habe ich schon mehrfach überprüft
Stream läuft im Browser 

Foto:
![](https://i.imgur.com/VsMtn8P.jpeg)

**Comment by Heptamer** [comment]
Hi, Du hast den Resolver auf nightly stehen in den Einstellungen, sollte man nur machen wenn etwas nicht läuft, weil dort nur temporäre fixes drin sind. Bei mir steht du auf Release, Version 5.1.9.2, und damit läuft deine Serie bei allen Hostern.

**Comment by Maxxxel** [comment]
Ich hab ihn extra auf Nightly gestellt, weil es vorher auch nicht funktioniert hatte :/

Werde es heute Abend noch Mal probieren und berichten.

**Comment by DWH-WFC** [comment]
Teste mal bitte einen 2. Account. Bitte keine Accounts sharen und teilen. Hatte auch das Problem mal das mein 1. Account temporär Probleme hatte.

**Comment by Maxxxel** [comment]
Den Account habe ich gestern erst erstellt 😅. Ich teste später nochmal. Noch einen Account zu erstellen Schaffe ich heute nicht. Hat gestern schon 2h gedauert bis die Bestätigung kam.

**Comment by Heptamer** [comment]
Ich mach mal zu weil hier kein Programmfehler vorliegt. kann aber weiter diskutiert werden falls notwendig.

**Comment by Maxxxel** [comment]
Funzt jetzt alles, woran es genau lag kann ich nicht sagen.

Hab account entfernt und neu angelegt.
Dann gab's noch ein plugin Update.
Hab beides auf Release anstatt Nightly.
