### ISSUE TITLE
Netzkino Scraper funktioniert nicht mehr

### ISSUE THREAD

**Issue by peat80** [streamxstream/plugin.video.xstream#140]
**Beschreibe den Fehler**

Hallo liebes xStream-Team, 
Der Netzkino-Scraper spielt leider nichts mehr ab.
Egal was man auswählt es kommt nur
"Allgemeiner Fehler bei der Wiedergabe" 
Im Log steht dann bei jedem Aufruf
Http Error 400

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Gehe zu 'Netzkino'
2. Klicke auf 'Beliebigen Film'
3. siehe Fehler oben

**Erwartetes Verhalten**

Stream sollte starten

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**

 - Hardware / OS: Nvidia Shield, Android TV 11
 - Kodi Version: Kodi 20
 - Xstream Version: 4.0.4~nightly6
 - Resolver Version: 5.1.93

**Zusätzliche Informationen**
Kodi-Version oder Hardware scheinen egal zu sein.
Vermutlich eine Änderung an der Netzkino-Webseite.

**Comment by DWH-WFC** [comment]
Ist bekannt und muss komplett überarbeitet werden. Login Funktion usw.

**Comment by mascarena** [comment]
@DWH-WFC 
Der Abspielfehler hängt nicht mit der Loginfunktion zusammen, sondern die verwendete StreamUrl im Netzkino-Plugin ist obsolete !
Die Loginfunktion bei Netzkino ist nur für die sog. Plusinhalte (Pay) zuständig und das dürfte für xStream wohl uninteressant sein ?!

Da Netzkino ca. seit 8 Monaten nur noch einen -**mp4-Stream**- anbietet, muss die StreamUrl etwas angepasst werden.
Das betrifft die Zeilen 116+117 in der neuen "netzkino.py":
Aus:
`            if 'Streaming' in item['custom_fields'] and item['custom_fields']['Streaming'][0]:                                 
                urls += 'http://netzkino_and-vh.akamaihd.net/i/%s.mp4/master.m3u8' % item['custom_fields']['Streaming'][0]`
wird:
`            if 'Streaming' in item['custom_fields'] and item['custom_fields']['Streaming'][0]:                                 
                urls += 'https://pmd.netzkino-seite.netzkino.de/%s.mp4' % item['custom_fields']['Streaming'][0]`

Mit dieser Änderung sollte das Plugin wieder einsatzfähig sein.:wink:

**Comment by DWH-WFC** [comment]
Danke für eure Hilfe werden wir testen und einfügen
