### ISSUE TITLE
Fehler/Probleme akt. Nightly7-Version

### ISSUE THREAD

**Issue by TitanME** [streamxstream/plugin.video.xstream#141]
Ich werd' jetzt mal bewusst das vorgefertigte Formular nicht nutzen, da es mMn bei dieser Art der Fehler-Meldung keinen Sinn macht.

**Gesammelte Fehler-Meldungen aus verschiedenen FB-Gruppen:**

1. Indexseiten lassen sich nicht mehr deaktivieren bzw. sind nach Neustart wieder aktiviert

2. Globale Suche funktioniert nicht mehr

**zu 1** Kann ich bestätigen. Das eigenständige Deaktivieren von Indexseiten und deren Deaktivierung bezüglich der Globalen Suche wird zwar in die settings.xml im addon_data-Ordner von xStream übernommen, bei Kodi-Neustart aber wieder überschrieben _(Windows & Android, Matrix & Nexus)_

**zu 2** Die Globale Suche in xStream startet zwar...hängt dann aber ca. 3 Minuten ohne jegliche Bewegung im Fortschrittsbalken...und läuft erst dann weiter bis zum Ende durch (inkl. Ergebnisse). Diese 3 Minuten wartet kaum ein User ab, daher kommt es zu obiger Aussage _(Windows & Android, Matrix & Nexus)_

**Comment by DWH-WFC** [comment]
1. ist in Arbeit 
2. kann ich persönlich bei keinem der getesteten Plattformen feststellen. 
Globale Suche mit Deadpool und Ohne HTML Cache Win 11 mit 43 Ergebnissen in 7,78 Sekunden.
Aber es kann wie bei 2 anderen Usern die mit Kinofox ein SSL Problem haben zusammenhängen, das die Seite den
Prozess verlangsamt. Ohne beigefügten Log von dir lässt sich das nur hellsehen.
Wir arbeiten an einer Lösung vielleicht ist es bei deinen Usern das selbe Problem.

**Comment by TitanME** [comment]
Beispiele für auffällig lange Suchen;
- Avatar
- Top Gun

Log kommt dann nach der Arbeit ;-)

**Comment by Heptamer** [comment]
Zu 1. Erst mal behoben, schauen wir uns aber noch mal an

Zu 2. Zwei Plugins machen da Probleme, habe ich erst mal deaktiviert in der Globalen Suche. (Nein, das sieht man nicht in den Einstellungen, ist eine übergreifende Funktion im Scraper die ich letztes jahr mal geschrieben habe)

Falls noch was auffällt, ich lass das hier noch bis morgen offen.
