### ISSUE TITLE
Fehler Melden

### ISSUE THREAD

**Issue by reddexx** [streamxstream/plugin.video.xstream#142]
**Beschreibe den Fehler**
Bei Aniworld kommt der Fehler seit heute wenn man ein Video abspielt das es keinen hoster für die Sprache gefunden werden kann, nach den Fehler kommt noch ein Fehler "host link nicht verfügbar". 

das bei alle Videos bei aniworld

Andere streamseiten wie beispiel serienstream funktionieren noch ohne probleme

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
- Hardware: raspberrypi 
- system: libreelec mit kodi 19.4
- xstream version: 4.0.4 nightly8
- resolveurl: 5.1.93
- repository: 1.2.0

**Comment by DWH-WFC** [comment]
Wie schon mehrmals erwähnt. Und auch im Changelog nachlesbar. Bitte in den xStream Einstellungen die Sprache einstellen.

**Comment by reddexx** [comment]
Ist auf alle Sprachen eingestellt, liegt an der nighty Version bin auf stable gewechselt
