### ISSUE TITLE
Die neuen Site-Plugins Streamcloud und -kiste übergeben keine Medieninformationen


### ISSUE THREAD

**Issue by Sysdocalex** [streamxstream/plugin.video.xstream#143]
- Weder noch die Bewertungen

- Erweiterte Informationen einzuholen über TMDb bleibt auch erfolglos

- Auch die Suche nach weiteren Quellen - negativ

- Der Hoster: Goodstream.Uno (Streamkiste) funktioniert nicht

- Streamkiste: Menü/Sortierung "Land" = "ValueError : unknown url type"

Kodi Version: Nexus-20.0 und Matrix-19.4
Platform: Android und Linux-Libreelec
xStream: 4.0.4

**Comment by Heptamer** [comment]
Danke für die Hinweise.  Das mit den Beschreibungen liegt an den Seiten, da bin ich noch dran.

Goodstream.uno - muss ich prüfen, ging bei Release, ebenso die Länderauswahl.

**Comment by DWH-WFC** [comment]
Der Hoster: Goodstream.Uno (Streamkiste) funktioniert nicht
Lag bzw vielleicht liegt es am Resolver. 
Da es keine Links gibt zum testen ist es natürlich unvorteilhaft.

**Comment by Heptamer** [comment]
TMDb Handler soweit erst mal gefixt, das Goodstream.uno nicht geht liegt am Resolver, habe das mal weiter geleitet.
