### ISSUE TITLE
('HTTPError: HTTP Error 404: Not Found', File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/py line 649, in http_error_default')

### ISSUE THREAD

**Issue by Stivan101** [streamxstream/plugin.video.xstream#144]
Dieser Fehler wird mir angezeigt wenn ich bei serienstream einen hoster auswähle

Geräteinformationen:

Kodi-Version: 19.1 (Code-Version: 19.1.0)

System Plattform: Android

XStream-Version: plugin.video.xstream - 4.0.4

ResolveURL-Version: script.module.resolveurl - 5.1.96-nightly2

XStream-Repository:

Repository.xstream - 1.2.0

**Comment by Heptamer** [comment]
Xstream Version nicht aktuell, und der Resolver sollte nicht auf nightly stehen in den Einstellungen, sondern auf Release, dann klappt das auch

**Comment by Stivan101** [comment]
> Xstream Version nicht aktuell, und der Resolver sollte nicht auf nightly stehen in den Einstellungen, sondern auf Release, dann klappt das auch

Bei mir wird angezeigt das 4.0.4 das neuste ist und das vom xStream Repository

Und in den Einstellungen finde ich nichts über Urlresolver wo ich es von nightly auf release einstellen könnte. 

Und danke für die schnelle Antwort.

**Comment by Heptamer** [comment]
Dann solltest du einfach Mal in Ruhe schauen. Xstream Einstellungen/Aktualisierungen

**Comment by DWH-WFC** [comment]
Gehe bitte in xStream nach unten auf Einstellungen / XStream Einstellungen und dann Links auf Aktualisierungen. Dann steht alles weitere da

**Comment by Stivan101** [comment]
> Dann solltest du einfach Mal in Ruhe schauen. Xstream Einstellungen/Aktualisierungen
> 
> Xstream Update auf nightly stellen, ResolveUrl auf Release

Habe alles gemacht aber geht immernoch nicht


Geräte-Informationen:

Kodi Version: 19.1 (Code Version: 19.1.0) System Plattform: Android

Plugin-Informationen:

XStream Version: plugin.video.xstream - 4.0.5-nightly7

ResolveURL Version: script.module.resolveurl -5.1.95 

XStream Repository: repository.xstream - 1.2.0

**Comment by Heptamer** [comment]
Dann solltest du vielleicht mal erwähnen im Detail erwähnen welche Serie und welcher Hoster

**Comment by Stivan101** [comment]
> Dann solltest du vielleicht mal im Detail erwähnen welche Serie und welcher Hoster

Keine Serie funktioniert z.b. the last of us folge 1-3 da gibt es nur Voe, mandalorian staffel 1 folge 1-3 auch da nur Voe oder Tulsa King folge 1-3.

Habe bemerkt das bei voe eine Fehlermeldung kommt und bei den anderen hoster gar nichts passiert auch keine Fehlermeldung.

**Comment by Heptamer** [comment]
Hab das gerade getestet, die Serien die du genannt hast funktionieren. Also wird das Problem entweder an deinem Provider liegen, oder zb hast ein VPN am laufen was stört. Von unserer Seite her geht alles.

**Comment by DWH-WFC** [comment]
Lese mal die FAQ mit DNS vielleicht hilft das
