### ISSUE TITLE
Suchanfragen speichern 

### ISSUE THREAD

**Issue by Fidelityyy** [streamxstream/plugin.video.xstream#145]
Ich habe auf xStream ähnlichen Plattformen, wie The Crew und Ezra, gesehen, dass die Möglichkeit besteht, Suchanfragen zu speichern. Dies sieht dann wie folgendermaßen aus:
- Man sucht eine Serie / Film
- Man bekommt die Ergebnisse angezeigt
- Das nächste Mal, wenn man auf "suchen" geht, sieht man die vorher eingebebene Serie / Film und man kann erneut drauf drücken, um die gleiche Suchanfrage durchzuführen

Ich denke, dass das eine sinnvolle Erweiterung für das Plugin wäre, und einem besonders, wenn man keine Lust hat, jedes Mal den selben Titel einzugeben, das Leben echt erweitern, und das Plugin noch ein wenig verbessern würde.

**Comment by DWH-WFC** [comment]
Hatten wir schon bei der Teambesprechung und sehen aber keinen Mehrwert darin dies zu integrieren.

**Comment by Heptamer** [comment]
Und deswegen mach ich auch mal zu hier 😏
