### ISSUE TITLE
Fehler bei der Anzeige von Seriennamen

### ISSUE THREAD

**Issue by smokyy12** [streamxstream/plugin.video.xstream#146]
Es gibt bei manchen Seiten einen Fehler bei der Anzeige von Seriennamen:

Ich suche zum Beispiel Serie A über Serienstream, ich finde sie dort und kann sie ganz normal wiedergeben. Der Serienname wird statt "A" jedoch als "False" angezeigt. Wenn ich nun die gleiche Serie nicht über die Suchfunktion aufrufe, sondern über einen anderen Reiter wie zB "Beliebt", besteht das Problem nicht und der Serienname wir ganz normal als "A" angezeigt. Da die TMDB Player alle über die Suchfunktion der jeweiligen Seite laufen, wird der Serienname grundsätzlich als "False" angezeigt. Dadurch wird in Verbindung mit Trakt egal welche Serie man sich ansieht, immer eine Serie Namens „False Flag“ getriggert und nicht das was man eigentlich ansieht. Filme sind nicht betroffen.
Das Problem lies sich auf verschiedenen Kodi Versionen und Geräten reproduzieren.

Es sind nicht alle Seiten betroffen, bei den neueren wie Cinemathek und Streamen zum Beispiel wir der Name immer richtig angezeigt.
Bei Serienstream und Filmpalast besteht das Problem immer.

![screenshot00000](https://user-images.githubusercontent.com/125290857/234930233-67293562-effe-4b8f-aca7-7ca97994e9c9.png)

Hier einmal ausgewählt bei Serienstream über "Beliebte Serien" --> Serienname wird angezeigt

![screenshot00002](https://user-images.githubusercontent.com/125290857/234930459-24653e60-9ffa-4a84-bb00-4a1a05cbb760.png)

Hier die gleiche Serie, über die Suchfunktion von Serienstream --> Serienname "False"

Die Screenshots sind im Arctic Horizon 2 Skin entstanden, im Standard Kodi Skin verhält es sich genauso, der Serienname ist nur nicht so präsent angezeigt.

Vielleicht hat ja mal jemand Lust sich das anzusehen.

**Comment by smokyy12** [comment]
Ah super, wusste nicht dass das Problem schon bekannt ist und dachte mir ich eröffnen mal ein Issue :) 
Läuft ja auch nicht weg, ist ja ein reines Komfortproblem

**Comment by DWH-WFC** [comment]
Wir können es ruhig offen lassen weil keine Ahnung wann jemand von uns dazu kommt es umzusetzen.

**Comment by Cubikon** [comment]
Vllt hilft das:  Das passiert nur wenn man über die Suche die Serie anklickt. Geht man über "all Series", "Popular Series" oder "From A-Z" dann ist der Titel bei der gleichen Serie normal da.

**Comment by Heptamer** [comment]
Und danke für die gute und ausführliche Dokumentation, so muss das sein!

**Comment by Heptamer** [comment]
Fix eingespielt. Danke!
