### ISSUE TITLE
Aniworld streaming Seiten sind broken

### ISSUE THREAD

**Issue by reddexx** [streamxstream/plugin.video.xstream#148]
**Beschreibe den Fehler**
Aniworld spielt keinen stream ab, es kommt auch keine fehlermeldung

**Erwartetes Verhalten**
Es soll einen Video abspielen 

**Screenshots**
Wenn möglich füge ein oder mehrere Screenshots hinzu um den Fehler zu erklären

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: raspberrypi / openelec
 - Kodi Version: Kodi20
 - Xstream Version: stable und nightly versucht 
 - Resolver Version: stable und nightly

**Comment by Heptamer** [comment]
Kann ich so nicht bestätigen, hab einige Streams getestet, laufen alle. Nimm einfach mal einen anderen Hoster oder schreib mal welche Serie, Staffel und Episode mit weichem Hoster nicht funktionieren.

**Comment by DWH-WFC** [comment]
Welche DNS Einstellungen?
Aktuellen Resolver ? 
Hast ja keine Versionsnummern angegeben

**Comment by reddexx** [comment]
Welche DNS Einstellungen?
8.8.8.8
192.168.179.1(pihole - nein Abfrage wird nicht geblockt ) 

Aktuellen Resolver ? Latest nightly

**Comment by reddexx** [comment]
> Kann ich so nicht bestätigen, hab einige Streams getestet, laufen alle. Nimm einfach mal einen anderen Hoster oder schreib mal welche Serie, Staffel und Episode mit welchem Hoster nicht funktionieren.

Alle hoster funktionieren nicht

**Comment by Heptamer** [comment]
Wie gesagt bei mir geht's, also liegt das Problem an dir. Da du meine Fragen anscheinend nicht beantworten willst können wir hier dann auch zu machen.

**Comment by reddexx** [comment]
> Kann ich so nicht bestätigen, hab einige Streams getestet, laufen alle. Nimm einfach mal einen anderen Hoster oder schreib mal welche Serie, Staffel und Episode mit welchem Hoster nicht funktionieren.

Welche Frage 🤣

2ten wenn ich sage aniworld dann ist das komplett aniworld egal ob serie/staffel/...

Witziger Weise geht Serienstream mit den gleichen hoster....

**Comment by Heptamer** [comment]
OK dann nicht...
