### ISSUE TITLE
Keine Verbindung zum Repository

### ISSUE THREAD

**Issue by Hermit6202** [streamxstream/plugin.video.xstream#15]
**Beschreibe den Fehler**
Habe xStream Repository von github ohne Fehlermeldung installiert. Allerdings musste ich die Adresse der Repoquelle (.../xStreamRepoWeb/) Case Sensitive und mit Slash am Ende eingeben (ist das normal, oder ist bei mir in Kodi etwas verstellt?). Wenn ich aber das Plugin aus dem Repository installieren will kommt der Fehler: "Die Verbindung zum Repository kann nicht hergestellt werden."

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Gehe zu 'Aus Repository installieren'
2. Klicke auf 'xStream Repository'
3. siehe Fehler

**Erwartetes Verhalten**
xStream sollte aus der Videosektion installiert werden.
Ä

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: 
 - Amazon Fire Tv Stick 4K Max Fire OS 8.1.1.9
 - Kodi Version: Kodi 18.9
 - Xstream Repository Version: 1.2.3
 - Resolver Version: keine, da Installation nicht möglich

**Zusätzliche Informationen**
Habe erst vor ca. 2 Monaten xStream installiert, da hat alles wunderbar funktioniert.

**Screenshots**

![20241106_154333](https://github.com/user-attachments/assets/be902758-6971-4c42-a9a7-c473d04a727c)
![20241106_154320](https://github.com/user-attachments/assets/ec70dc3a-7968-4d72-9c3c-1ce8de7f7a23)

**Comment by DWH-WFC** [comment]
Kodi 18 in Python 2 wird nicht mehr supported. xStream wird derzeit nur noch ab Python 3 supported also ab Kodi 19-21 derzeit.

**Comment by Hermit6202** [comment]
Das ist schlecht, weil ab ver. 19 Kodi keine Verbindung vom Fire Tv stick
zu meinem Netzwerk herstellen kann (und ich habe buchstäblich seit v19.1
bis heute mit recherchieren verbracht, ohne eine Lösung zu finden. Hab es
übrigens testweise mit der aktuellen Version probiert, die zwar das Repo
öffnen konnte, aber xStream nicht installieren konnte weil die
Abhängigkeiten fehlen und sich auch nicht installieren lassen.  Muss auch
ohne xStream gehen. Die Verbindung zu Pc und Netzwerkplatte ist für mich
wichtiger.

DWH-WFC ***@***.***> schrieb am Fr., 8. Nov. 2024, 21:51:

**Comment by DWH-WFC** [comment]
Bei anderen funktioniert es doch auch. Dein Network ist ja nicht Kodi Versions Abhängig. Du benötigst doch nur die entsprechenden Programme dafür.

**Comment by damnms** [comment]
Ich habe den gleichen Fehler unter Libreelec nightly - habe per Hand das Repo als auch xstream aktualisiert, aber der Fehler erscheint weiterhin. Ich kann auch nicht in das Repo "browsen" wenn ich via "Addon vom Repo installieren" versuch drauf zuzugreifen

**Comment by DWH-WFC** [comment]
Die Nightly ist bestimmt Kodi 22 Alpha. Wir unterstützen aber nur Release Versionen von Kodi. Das ist derzeit die Version 19-21.x

**Comment by damnms** [comment]
Ja, ist 22 alpha (Starting Kodi (22.0-ALPHA1 (21.90.700)), ich finds aber trotzdem komisch, weil das lief die letzten Monate problemlos und von heute auf morgen kommt der Fehler. Downgrade ist aktuell leider nicht möglich. 
Liegt das am python? Python-Version: 3.12.7
Ich find im Log einige Einträge, die so aussehen, als hätte es da syntaktische Änderungen gegeben:
```
2024-11-12 15:19:26.967 T:46602    info <general>: [xStream] -> [einschalten]: {'site': 'einschalten', 'function': 'showHosters', 'title': 'Weihnachten im Bramble Haus (2017)', 'trumb': '/storage/.kodi/a
ddons/plugin.video.xstream/resources/art/sites/einschalten.png', 'sUrl': 'https://einschalten.in/movies?order=added', 'sName': 'Weihnachten im Bramble Haus', 'sThumbnail': '/image/poster/23ZnKIVAOpg8J1YE
Zfc6lKPzEvL.jpg', 'entryUrl': '/movies/479606', 'MovieTitle': 'Weihnachten im Bramble Haus (2017)', 'thumb': 'https://einschalten.in/image/poster/23ZnKIVAOpg8J1YEZfc6lKPzEvL.jpg', 'mediaType': 'movie', '
playMode': 'play'}
2024-11-12 15:19:27.034 T:46602   error <general>: <string>:94: SyntaxWarning: invalid escape sequence '\s'
```
Und vermutlich der/mein Fehler:
2024-11-12 15:20:51.068 T:46625   error <general>: Repository add-on repository.xstream does not have any directory matching 21.90.700 and won't be able to update/serve addons! Please fix the addon.xml definition

Wenn ich das richtig verstehe, würde es vermutlich ausreichen, die addon.xml anzupassen

**Comment by DWH-WFC** [comment]
Nein leider nicht da wir immer erst die Release Versionen testen und dann den jeweiligen Quellcode anpassen müssen. Deswegen wird es das dann erst paar Wochen nach dem Release geben.

**Comment by damnms** [comment]
Verstehe ich. Ich vermute mal, das ist auch nicht möglich den Fehler irgendwie anders auszugeben, weil das von Kodi direkt kommt. Ist einfach bisschen irritierend, weil die Fehlermeldung klingt so, als wäre das Repo irgendwie down oder nicht erreichbar (Netzwerkprobleme). Dabei ist einfach nur die Version inkompatibel.

**Comment by DWH-WFC** [comment]
Deswegen ist es über Versionen deklariert. Und von Kodi 21 ist die letzte maximal Version nun mal die 21.9.700 alles was danach kommt gehört schon zur Version 22
