### ISSUE TITLE
Kinoger Filme/Serien werden nicht abgespielt "('JSONDecodeError"...Fehler Melden

### ISSUE THREAD

**Issue by PippoInzaghi09** [streamxstream/plugin.video.xstream#151]
Ich kann bei Kinoger nichts abspielen, da ich diese Fehlermeldung erhalte:

![IMG_20230526_172709](https://github.com/streamxstream/plugin.video.xstream/assets/134721800/65d5c3ed-f880-4c87-938a-658afa71dbe9)

Beim Auswählen einer Folge / eines Films lädt die Hosterliste kurz ("Übergebe Einträge der Indexseite") bis die Fehlermeldung erscheint.

Kodi 19.4 auf einem Amazon Fire TV Stick 4K. 

xStream 4.05~nightly15 
Aktuellster URLResolver (5.1.98)

**Comment by DWH-WFC** [comment]
Habe jetzt mehrere Filme getestet und eine Serie kann keinen Fehler feststellen. Kannst du bitte mal in Addon_data den Cookies und HTMLCache Ordner löschen. Kodi neustarten und nochmal testen?

**Comment by PippoInzaghi09** [comment]
> Habe jetzt mehrere Filme getestet und eine Serie kann keinen Fehler feststellen. Kannst du bitte mal in Addon_data den Cookies und HTMLCache Ordner löschen. Kodi neustarten und nochmal testen?

Habe ich gemacht, aber habe weiterhin dasselbe Problem. Auf einem zweiten Gerät (selbe Kodi-Version + xStream Updates) habe ich dasselbe Problem. Nur taucht dort statt "python 3.8" eine andere python-Version auf.

**Comment by DWH-WFC** [comment]
Ich werf mal n FireTV Stick an und teste mal da für dich

**Comment by DWH-WFC** [comment]
So ich hab mal n FireTV getestet allerdings habe ich da Kodi 20.1 drauf und da läuft es auch sauber.. Leider kann ich den Fehler nicht nachvollziehen. Update mal bitte dein Kodi auf 19.5 und teste nochmal bitte.

**Comment by Heptamer** [comment]
Wurde mal getestet direkt auf der Webseite einen Stream zu starten?

**Comment by PippoInzaghi09** [comment]
> Wurde mal getestet direkt auf der Webseite einen Stream zu starten?

Ich habe nochmal die Cache-Ordner gelöscht und in den xStream-Einstellungen erneut den HTML Cache gelöscht. Jetzt funktionieren wieder viele Serien, aber eine Serie läuft immer noch nicht.

Auf der Internetseite ist diese aber verfügbar und kann problemlos gestartet werden. Nur über das Addon leider nicht.

**Comment by Heptamer** [comment]
Und welche ist das?

**Comment by PippoInzaghi09** [comment]
> Und welche ist das?

Dexter

**Comment by DWH-WFC** [comment]
Welche von der beiden?
Gibt 2 Einträge.

**Comment by DWH-WFC** [comment]
Ach das jetzt ja beim 2. Eintrag. Das fix ich gleich mit.
