### ISSUE TITLE
AniWorld/SerienStream Kein Eintrag

### ISSUE THREAD

**Issue by UltraInstinct242** [streamxstream/plugin.video.xstream#154]
Hallo Liebe Community,

Ich habe folgenden Xstream Fehler über Kodi (FireTV).

Es geht speziell um Aniworld und SerienStream(s.to), seit ein paar Tagen wird bei mir angezeigt: Es wurde kein Eintrag gefunden.
Ich komme garnicht in die Serienauswahl rein, das Passiert z.B schon wenn ich auf den Reiter Beliebte Serien rein gehe.

Ich benutze kein VPN.

Die Benutzerkontos habe ich mehrmals auf Richtigkeit überprüft, und ich habe auch die neuste Version von XStream geupdatet.

XStream Repository Version 4.0.5
Kodi Version Nexus 20.1

Ich hoffe jemand kann mir hier helfen.

Grüße

**Comment by DWH-WFC** [comment]
Mal die neuste Nightly getestet? DNS richtig?

**Comment by UltraInstinct242** [comment]
Ja die neuste Nightly habe ich gerade getestet. 
Die Domain stimmt auch. 
Weiterhin der selbe Fehler.

**Comment by DWH-WFC** [comment]
Welche DNS Einstellungen hast du im Router und im Endgerät?

**Comment by UltraInstinct242** [comment]
Im Router habe ich die normalen DNS Einstellungen von der Deutschen Glasfaser.
Im Fire TV weiß ich nicht wie ich das nachschauen kann. 
So hat es bisher immer funktioniert.

**Comment by DWH-WFC** [comment]
Dann solltest du im Router und Endgerät deine DNS Einstellungen anpassen. Entweder nutzt du Google, Cloudflare oder Quad9 welcher davon ist dir überlassen.

Ohne DNS Anpassung sind die besagten Seiten und noch weitere nicht erreichbar.

**Comment by UltraInstinct242** [comment]
Habe jetzt sowohl im Router als auch im Endgerät fie DNS geändert auf die von Google.
Leider funktioniert es immer noch nicht. 
Grüße

**Comment by DWH-WFC** [comment]
Fotografiere mal bitte beide DNS Einstellungen von Router und Endgerät und poste sie. Zufällig 1 und 1 als Anbieter?

**Comment by UltraInstinct242** [comment]
Nein mein Anbieter ist Deutsche Glasfaser.
Ich benutze Kodi bzw. Aniworld schon seit Monaten und hat bisher wie gesagt immer funktioniert, seit 1-2 Wochen habe ich diese Probleme. Mal geht es und mal nicht.
Anbei die Fotos.
![20230624_105018](https://github.com/streamxstream/plugin.video.xstream/assets/137075168/11b0f26e-4759-471e-b149-0ce78d23e80e)
![20230624_105001](https://github.com/streamxstream/plugin.video.xstream/assets/137075168/e11c28fa-ae86-493a-ae0e-c96d7fdc313a)
![20230624_104603](https://github.com/streamxstream/plugin.video.xstream/assets/137075168/ed801dec-ffbf-4a1c-9529-25ea8a1bdb1e)

**Comment by UltraInstinct242** [comment]
Hier noch ein Foto vom Fehler. 
![20230624_105425](https://github.com/streamxstream/plugin.video.xstream/assets/137075168/d73c04f5-c574-4ddc-bee8-4ae802b52403)

**Comment by DWH-WFC** [comment]
Benutze mal bitte Cloudflare zum testen. 
DNS 1: 1.1.1.1
DNS 2: 1.0.0.1

Schalte mal bitte IPv6 in der Fritzbox ab. Und nutze nur IPv4 zum testen.

**Comment by DWH-WFC** [comment]
![Uploading IMG_9226.jpeg…]()

**Comment by DWH-WFC** [comment]
![Uploading IMG_9226.jpeg…]()

**Comment by DWH-WFC** [comment]
<img width="492" alt="Unbenannt1" src="https://github.com/streamxstream/plugin.video.xstream/assets/45105289/7010ccdf-3e11-4f5c-b49f-a116469d2fca">

**Comment by UltraInstinct242** [comment]
Leider ging es damit auch nicht. 

Habe aber jetzt rausgefunden, wenn ich z.B auf Aniworld über Laptop raufgehe da überprüft es ob ich ein Mensch bin, nach der bestätigung funktioniert es dann auch für kurze Zeit bei Kodi.
Wie kann man das Problem lösen?

**Comment by mar565** [comment]
Ich kann das Problem bestätigen. Habe bisher einen VPN benutzt. Seitdem die beiden Seiten wegen der Captcha Abfrage nicht mehr funktionieren, war ich ohne VPN unterwegs. Jetzt fangen die Probleme auch ohne VPN an.

**Comment by DWH-WFC** [comment]
Genau deswegen kein VPN benutzen da es sowieso Schwachsinn ist in dieser Situation. Normalerweise wenn Ihr die richtigen DNS Server nutzt sollte es auch funktionieren. In dieser Situation können wir euch leider nicht helfen.

**Comment by Heptamer** [comment]
Und darum ist hier auch jetzt mal zu.
