### ISSUE TITLE
Serienstream Kein Eintrag gefunden

### ISSUE THREAD

**Issue by Riotreimar** [streamxstream/plugin.video.xstream#155]
**Beschreibe den Fehler**

Serienstream gibt häufig die Meldung "Kein Eintrag gefunden" aus. Über das xstream Plugin lassen sich gar keine Inhalte von s.to anzeigen, über den Movie DB Helper kommt nach dem Auswählen des Serienstream Players besagte Meödung. Der Fehler lässt sich nicht gezielt reproduzieren, über die Homepage sind die entsprechenden Streams erreichbar. Wechsel der Domains in den xStream- Einstellungen hilft nicht. Benutzerkonto ist in xstream korrekt eingetragen, aber nur in etwa 1/3 der Fälle lassen sich die Streams auch über Kodi wiedergeben.

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: FireTV Stick lite
 - Kodi Version: Kodi 20.1
 - Xstream Version: 4.0.6-nightly6
 - Resolver Version: 5.1.100-nightly3

**Zusätzliche Informationen**
Füge zusätzliche/ergänzende Informationen zum Fehler hinzu

**Comment by Heptamer** [comment]
Benutzt Du ein VPN?

**Comment by Riotreimar** [comment]
Ja, proton. Habe es zwischenzeitlich aber testweise abgeschaltet, geändert hat es aber nichts.

**Comment by Heptamer** [comment]
Zeitweise nützt nichts, anicloud und Serienstream funktionieren nur noch zuverlässig wenn man kein VPN nutzt. Da dahinter auch noch ein Bot sitzt der die Zugriffe anscheinend loggt einfach mal 24h besagte Seiten nicht nutzen und dann ohne VPN aufrufen.

**Comment by DWH-WFC** [comment]
Da nichts mehr kommt wird’s geschlossen
