### ISSUE TITLE
Globale Suche bleibt hängen

### ISSUE THREAD

**Issue by Moll4ika** [streamxstream/plugin.video.xstream#158]
**Beschreibe den Fehler**
Sobald man über die globale Suche einen Titel sucht, bleibt die Suche im Dialog hängen. Meistena um 50% rum und ein abbrechen ist auch nicht mehr möglich, sodass man die Anwendung killen muss.
In meinem Fall war es z.B. der Titel "from", ist aber bei anderen auch so.
Vor ca. 2 Wochen scheint es noch halbwegs funktioniert zu haben.

Im Log steht leider auch nix aufschlussreiches, da steht einfach nur, dass es Titel X sucht und dabei bleibt es.

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Globale Suche anklicken
2. Nach "from" suchen
3. Suchen lassen bis es hängen bleibt

**Erwartetes Verhalten**
Suche muss abschließen und Ergebnisse angezeigt.

**Screenshots**
![Screenshot 2023-08-24 081348](https://github.com/streamxstream/plugin.video.xstream/assets/143064725/e6918baf-b376-4723-abc7-de19f182b23c)

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: FireTV Stick 4K und auch unter Windows 11 64-bit
![Screenshot 2023-08-24 085257](https://github.com/streamxstream/plugin.video.xstream/assets/143064725/45fe5f1a-3440-410d-a555-db556f6e126e)

**Comment by DWH-WFC** [comment]
Bitte mal das Plugin xCine in den Einstellungen überprüfen.

die Domain sollte xcine.click heißen. 
Mit dem Browser auf dem PC (gleiches Netzwerk) testen ob die Seite sich da öffnen lässt. Vielleicht liegt ein Problem mit deiner Netzwerk Verbindung vor.

Zum Testen das Plugin in den Einstellungen deaktivieren und HTML Cache löschen. Kodi Neustart und nochmals testen.

**Comment by Moll4ika** [comment]
@DWH-WFC 
das hab ich schon alles gemacht, wenn ich den Hoster deaktiviere, bleibt er beim nächsten Suchlauf einfach bei einem anderen hängen.

Folgendes hab ich schon getan:

- In den Einstellungen die Domain aus der Suche genommen
- Cache gecleart
- xStream gelöscht und neuinstalliert
- Kodi gelöscht und neuinstalliert und backup restored

Wenn ich die nicht über die globale Suche gehe, sonden direkt die Suche der Anbieter verwende funktioniert es, nur nicht wenn eine globale ausgeführt wird.

**Comment by DWH-WFC** [comment]
Na denn dann mal deaktivieren und posten welcher als Nächstes kommt. Wenn es Serienstream ist nutzt du bestimmt ein VPN

**Comment by Moll4ika** [comment]
Der nächste ist Streamworld und auch bei 50%... ich hatte es aber tatsächlich auch mal bei 60%.
VPN benutze ich der Zeit nicht

**Comment by Moll4ika** [comment]
Das Nightly funktioniert ohne Probleme und sogar recht schnell, soll ich erstmal beim Nightly belassen bzw. was wurde geändert, dass es wieder bei mir funktioniert ?

**Comment by DWH-WFC** [comment]
Kann ich dir gerade nicht mehr sagen musst du bitte in Chanelog schauen. Einstellungen und Änderungsprotoll anzeigen
