### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by v4mp1** [streamxstream/plugin.video.xstream#162]
Gibt es irgendeine Möglichkeit um xStream dazu zu bekommen, dass der Proxy unter den Kodi Einstellungen benutzt wird?
Weder mein Socks5 Proxy noch mein HTTP/HTTPS Proxy wird berücksichtigt.
Vom PVR Plugin (IPTV Simple Client) wird der Proxy  berücksichtigt, aber Xstream scheint den Proxy beim Streamen nicht zu intressieren. Ich sehe das anhand vom Traffic Monitor auf meinem Pi.

**Comment by Heptamer** [comment]
Zuerst einmal, wir haben ein Template für Fehlermeldungen, bitte dieses benutzen oder die fehlenden Informationen hier nachreichen. Dann schauen wir uns das mal an, vorher nicht.

**Comment by Heptamer** [comment]
Keine Rückmeldung, daher mache ich mal zu.
