### ISSUE TITLE
Fehler MeldenSerienproblematik

### ISSUE THREAD

**Issue by SannyQ** [streamxstream/plugin.video.xstream#163]
**Beschreibung des Fehlers**
Die Probleme mit Serienstream nehmen zu. Nachdem Menüs eingerichtet und Favoriten gespeichert wurden, funktionieren diese plötzlich nicht mehr. Ein direkter Aufruf über xStream scheint jedoch zu funktionieren. Es ist einfach nur noch nervig. Warum könnt ihr das Problem nicht lösen? Oder bietet zumindest eine Möglichkeit an, dies zu beheben.

**Schritte zur Reproduktion**
Folge diesen Schritten, um den Fehler zu reproduzieren:
1. Menüs mit Verknüpfungen zu Serienstream erstellen
2. Favoriten mit Verknüpfungen zu Serienstream erstellen
3. Einige Tage/Wochen alles funktioniert
4. Serienstream findet plötzlich nichts mehr

**Erwartetes Verhalten**
Eigentlich sollte es ausreichen, sich mit dem Handy einzuloggen (DNS etc. ist konfiguriert), aber das funktioniert nicht immer. Auch nach der Verifizierung mit dem Handy sind die Verknüpfungen/Favoriten nicht mehr zugänglich.

**Technische Informationen (bitte vervollständigen):**
- Hardware und Betriebssystem: Nvidia Shield, SmartTV, Chromecast (alle mit demselben Fehler)
- Kodi-Version: Nexus
- xStream-Version: ~nightly1
- Resolver-Version: Aktuell

**Zusätzliche Informationen**
Ich wünsche mir eine Lösung für dieses Problem. Vielleicht könntet ihr euch mit dem Team von [jDownloader](https://jdownloader.org/) in Verbindung setzen und erfragen, wie sie es geschafft haben, dass bei Bedarf eines Captchas/Verifizierung automatisch ein Fenster zur Durchführung der Verifizierung geöffnet wird. Ich kann mir vorstellen, dass etwas Ähnliches auch mit Kodi und xStream möglich sein könnte. Wenn es nicht direkt über die Kodi-Modals funktioniert, dann öffnet im Notfall einen Browser, damit die Verifizierung durchgeführt werden kann. Es sollte doch ausreichen, dass xStream prüft, ob Serienstream ausgewählt ist, nichts findet und dann einen Browser mit der entsprechenden Domain öffnet, um die Verifizierung abzuschließen.

**Comment by DWH-WFC** [comment]
Wird ein VPN genutzt?

**Comment by SannyQ** [comment]
Nein. Lediglich nutze ich die Cloudflare-DNS, aber selbes Problem auch mit den Google-DNS.

**Comment by Heptamer** [comment]
Wenn deine Favoriten oder Menüs nicht mehr funktionieren, der Aufruf über xstream noch funktioniert, dann liegt das Problem an deiner lokalen Installation, und sonst nirgends.

Wenn du was anderes gemeint hast, dann bitte mal richtig erklären.

**Comment by SannyQ** [comment]
Ich bezog mich ausschließlich auf "Serienstream" !

Mit keinem einzigen Wort habe ich Hass ausgesprochen gegenüber Dir oder xStream selbst, du solltest vielleicht an deinem Ego arbeiten. Ich denke, deine Arbeit wäre dort besser aufgehoben.

Wenn das Problem bei meinem System liegt, frage ich mich, warum es immer wieder ausschließlich Serienstream betrifft. Alles andere funktioniert, und entsprechend müssten alle Menüpunkte sowie Favoriten nicht funktionieren, da ich nur xStream nutze.

Ich nutze nur DNS.

Starte ich heute das System (Shield) + Kodi, funktionieren wie angegeben die Menüpunkte sowie Favoriten von Serienstream nicht. Das Verifizieren via s.to wurde durchgeführt via Smartphone, keine Änderung.

An einem anderen Tag funktioniert es dann wieder. Und das muss doch an Serienstream liegen, gegebenenfalls am Plugin und dessen Umsetzung oder generell muss es unmittelbar mit der Verifizierung zu tun haben. Es kommt nicht immer vor, aber doch immer mal wieder.

Ich habe Ideen ausgesprochen, wie man die Verifizierung ohne Smartphone vereinfachen könnte. Eine Idee, ein Anreiz, und du konfrontierst mich hiermit, anstatt vielleicht aus vernünftiger Entwicklerperspektive zu schauen, was das Problem sein könnte, um zu verstehen, wodurch das besagte Phänomen verursacht wird.

**Comment by MartinX3** [comment]
> Mit keinem einzigen Wort habe ich Hass ausgesprochen gegenüber Dir oder xStream selbst, du solltest vielleicht an deinem Ego arbeiten. Ich denke, deine Arbeit wäre dort besser aufgehoben.

Wenn man sich die Issues hier anschaut, ist dieser Entwickler gerne schnell aggressiv/arrogant/beleidigt.
Ob er das selber so wahr nimmt weiß man natürlich nicht, aber schwierig ist dadurch die Fehlerberichterstattung umso mehr.

**Comment by codingPF** [comment]
Also für mich klingt

> Es ist einfach nur noch nervig. Warum könnt ihr das Problem nicht lösen?

schon ziemlich “aggressiv/arrogant/beleidigt”

Zum Thema: bei mir gehen Favoriten auch ab und an kaputt. So ca 1-2 mal im Jahr…
