### ISSUE TITLE
Cineclix Staffel grab Fehler

### ISSUE THREAD

**Issue by TimeLance89** [streamxstream/plugin.video.xstream#164]
Guten Abend, leider gibt es den Fehler bei cineclix das nicht immer alle staffeln angezeigt werden, ich nehme an das das Problem daran liegt das wenn man auf der Webseite sich befindet man auf "mehr anzeigen" klicken muss damit auch alle staffeln angezeigt werden. Kann man das vielleicht beheben? 
Beispielsweise bei "American Horror Story" gibt es 12 staffeln es werden aber leider nicht alle angezeigt via kodi

**Comment by Heptamer** [comment]
Danke für den Hinweis, schauen wir uns an.

**Comment by DWH-WFC** [comment]
hoffe das ich morgen mal Zeit finde danach zu schauen

**Comment by Heptamer** [comment]
Fehler mit nightly5 behoben.
