### ISSUE TITLE
Suchverlauf als neues feature

### ISSUE THREAD

**Issue by sogge777** [streamxstream/plugin.video.xstream#165]
Toll wäre ein Suchverlauf um nicht ständig komplizierte Suchanfragen neu eingeben zu müssen.

Lieben Dank für das tolle Addon!!!

**Comment by Heptamer** [comment]
Hallo, danke für Deine Anregung. Das wurde schon mehrmals angefragt und wir haben gesagt dass fügen wir nicht ein, weil das Feature in der TMdb Suche schon vorhanden ist.

Grüße,
Hep
