### ISSUE TITLE
Suche Filme/Serien nach Streamingdiensten

### ISSUE THREAD

**Issue by Flopsi75** [streamxstream/plugin.video.xstream#166]
Ich würde mich über ein Funktion freuen die es einem ermöglicht nach den Streamingdiensten suchen zu lassen.

Bei TMDB kann man z.B. sich alle Neflixfilme anzeigen lassen.

Suche könnt so aussehen:
Suchanfrage Filme die auf Neflix laufen, das könnte man sich dann in den Favoriten speichern.

**Comment by Heptamer** [comment]
Hallo, wenn du TMDb mit xstream verbindest hast Du doch genau das was du haben möchtest oder habe ich da einen Denkfehler?

Gruß,
Hep

**Comment by Flopsi75** [comment]
Hallo,
das dachte ich auch leider ist dem nicht so. 
Es werde nur Metadaten ersetzt aber es gibt keine Sortierung nach den Streamingdiensten.
Will mir Favoriten erstellen mit entsprechenden Suchanfragen...
Auf der Seite von TMDb werden z.b alle Filme die auf Netflix laufen angezeigt sowas würde ich gerne in Kodi haben....
Gruß

**Comment by DWH-WFC** [comment]
Macht der TMDb Helper doch

**Comment by Heptamer** [comment]
> Macht der TMDb Helper doch

Genau so sehe ich das auch.

**Comment by Flopsi75** [comment]
Super den kannte ich leider nicht ja der macht es :) Danke für den Tip
