### ISSUE TITLE
Add source Fehler keine Verbindung 

### ISSUE THREAD

**Issue by PSYOLOT** [streamxstream/plugin.video.xstream#167]
Kann keine quelle für „https://streamxstream.github.io/xStreamRepoWeb/“ hinzufügen 

neuer fire tv Stick 4k max 2.gen oS 8.1.0.1 

Fehler beim hinzufügen von quellen „https://streamxstream.github.io/xStreamRepoWeb/“ 

keine Verbindung bei hinzufügen von Mediaquellen. 

fire tv auf aktuellem Stand. 
Getestet auf KODi ver. 20  und 19.5  auch andere repos funzen nicht. Allerdings HSK Funktioniert. 
Auf meinem alten stick 4k läuft alles.
stick ist online, dns ist 1.1.1.1
 in kodi intern Aktualisierungen funktioniert (ist also online)

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Gehe zu 'FILE MANAGER'
2. Klicke auf'.Add source'
3.tippe in feld:
https://streamxstream.github.io/xStreamRepoWeb/
4. Klicke okay
5. Gib reponame und klicke okay.
6. siehe Fehler in popup window: couldn't connect to network Server

**
 - Hardware und Betriebssystem: FireOS 8.1.0.1 
 - FIRE TV stick 4K max (2.gen)
 - Kodi Version: 20; 19,5;...

DNS 192.168.8.1
             8.8.8.8

**Comment by Heptamer** [comment]
Hallo, danke für deine Meldung.

Das Problem ist vermutlich hardwareabhängig und zumindest von mir nicht zu prüfen weil ich keine Amazongeräte benutze.

Allgemein mal gefragt, hast du im Stick und in KODi die Installation aus unbekannten Quellen zugelassen?

**Comment by Heptamer** [comment]
Ich mach hier mal zu, der Fehler hat ja nicht ausschließlich mit xstream zu tun.

**Comment by PSYOLOT** [comment]
Ja, leider. Aber ja, danke für den Versuch
