### ISSUE TITLE
XStream in Jellyfin

### ISSUE THREAD

**Issue by 30elias** [streamxstream/plugin.video.xstream#169]
Hallo,
Ich habe leider keinen anderen Weg gefunden jemanden zu Kontaktieren, da der Matrix Chat nicht zu funktionieren scheint.

Jedenfalls versuche ich XStream in Jellyfin bzw Swiftfin auf einem AppleTV zu nutzen. Leider hatte ich keinen Erfolg bis dato. gibt es dazu Ideen?

Oder andere Ideen, wie ich Kodi auf einem AppleTV nutzen kann, ohne diesen zu Jailbreaken?

Vielen Dank für die Rückmeldung!

**Comment by Heptamer** [comment]
Sorry, aber das ist kein xstream typisches Problem sondern liegt an Apple. Von daher bist du hier mit Deiner Anfrage leider falsch und werde daher diese Issue closen.
