### ISSUE TITLE
Neuer Stream Anbieter: xcine.tv

### ISSUE THREAD

**Issue by der-framer** [streamxstream/plugin.video.xstream#17]
Hey,
ich bin vor ein paar Tagen auf die Seite xcine.tv gestoßen, auf welcher man sämtliche Filme und Serien auf Deutsch in FullHD streamen kann. Wäre meiner Meinung nach ganz cool die Page als Anbieter in xStream zu finden...
Beste Grüße,
Luis

**Comment by anis3** [comment]
die Seite xcine.tv kopiert leider nur die links von hdfilme
