### ISSUE TITLE
Frage zu Qualität

### ISSUE THREAD

**Issue by Variant1987** [streamxstream/plugin.video.xstream#171]
Welche Sites unterstützen hier 1080p? Ich habe bis jetzt nur kinoger gesehen. Sorry wenn ich etwas übersehen habe

**Comment by DWH-WFC** [comment]
Cinemathek und Moflix auch sogar 5.1

**Comment by Variant1987** [comment]
Wie komme ich in diesen Chat? Der verlinkte Matrix chat funktioniert nicht

**Comment by DWH-WFC** [comment]
Der Link funktioniert.

https://matrix.to/#/%23streamxstream_xTeam:gitter.im

da mit der App „Element“  unseren Raum betreten.
