### ISSUE TITLE
CineClix Fehler

### ISSUE THREAD

**Issue by TimeLance89** [streamxstream/plugin.video.xstream#174]
Egal welchen Inhalt man anklickt, es gibt immer nur eine Fehler das es nicht gefunden werden kann auf der normalen URL geht alles im Browser.

**Comment by DWH-WFC** [comment]
Also welche xStream Version hast du?
Gerade auf dere aktuellen Nightly getestet da läuft es problemlos.

**Comment by TimeLance89** [comment]
War anscheinend nur Temporär ein Problem vom Anbieter, jetzt läuft alles wieder rund!
