### ISSUE TITLE
Cineclix Fehler Serien

### ISSUE THREAD

**Issue by TimeLance89** [streamxstream/plugin.video.xstream#175]
Wenn man im Bereich Serien beim Anbieter CineClix auf "Neue Serien" navigiert kommt ein Fehler, ebenfalls wenn man auf den Reiter "Top 10 Serien diese Woche" navigiert der selbe Fehler

**Comment by TimeLance89** [comment]
Achso bevor ich es vergesse, ich nutze die Nightly

**Comment by DWH-WFC** [comment]
Danke fürs Feedback aber bitte nutze unser vorgefertigtes Fehler melden Template. Das ist genau dafür gedacht

**Comment by Heptamer** [comment]
Hallo, Danke für Deine Meldung. Ich habe gerade beide Menüpunkte in meiner Linux Entwicklungsumgebung mit Kodi 20.2 getestet, und alles funktioniert einwandfrei.

Ich bräuchte daher genauere Angaben - Betriebssystem, welches Kodi usw.

**Comment by Heptamer** [comment]
> Danke fürs Feedback aber bitte nutze unser vorgefertigtes Fehler melden Template. Das ist genau dafür gedacht

Wollte ich auch erst schreiben, aber die sind nicht mehr da ;)

**Comment by DWH-WFC** [comment]
> > Danke fürs Feedback aber bitte nutze unser vorgefertigtes Fehler melden Template. Das ist genau dafür gedacht
> 
> Wollte ich auch erst schreiben, aber die sind nicht mehr da ;)

Dann bitte ich um Verzeihung 😳

**Comment by DWH-WFC** [comment]
> Ich habe es gerade nochmal auf einem weiteren Gerät probiert und erhalte dort die selbe Fehlermeldung.
> 
> Ich nutze es hauptsächlich auf meinem Amazon Fire TV Cube, das Betriebssystem müsste dort Android sein wenn ich mich nicht täusche. Ich nutze die neueste Version der Nightly.
> 
> Ebenfalls habe ich es gerade auf meinem Windows Rechner versucht und die selbe Fehlermeldung erhalten.

Klicke im Browser mal bitte auf den Link und setze den mal hier rein. Vielleicht ist er anders. Bin leider arbeiten und kann euch da nicht weiterhelfen

**Comment by DWH-WFC** [comment]
Und denkt daran eure HTML Caches zu löschen wenn ihr testet. Nicht das er aus dem Cache liest.

**Comment by TimeLance89** [comment]
![image](https://github.com/streamxstream/plugin.video.xstream/assets/80360241/057bb60b-445a-4b3b-b271-c993dc0f3871)

Diese Fehlermeldung kommt immer wenn ich es versuche. Habe den Cache auch schon gelöscht, leider noch immer das Problem

**Comment by TimeLance89** [comment]
> > Ich habe es gerade nochmal auf einem weiteren Gerät probiert und erhalte dort die selbe Fehlermeldung.
> > Ich nutze es hauptsächlich auf meinem Amazon Fire TV Cube, das Betriebssystem müsste dort Android sein wenn ich mich nicht täusche. Ich nutze die neueste Version der Nightly.
> > Ebenfalls habe ich es gerade auf meinem Windows Rechner versucht und die selbe Fehlermeldung erhalten.
> 
> Klicke im Browser mal bitte auf den Link und setze den mal hier rein. Vielleicht ist er anders. Bin leider arbeiten und kann euch da nicht weiterhelfen

https://cineclix.in/neue-serien

https://cineclix.in/top-10-serien-diese-woche

Um die beiden Links geht es

**Comment by DWH-WFC** [comment]
Ok habe den Fehler bei mir auch mit Kodi 19.5-21.0beta2 getestet. Werde später wenn Zeit ist mal debuggen

**Comment by DWH-WFC** [comment]
In der xStream Version 4.0.9 Nightly8 (die2.) gefixt
