### ISSUE TITLE
Fehler Melden

### ISSUE THREAD

**Issue by Stivan101** [streamxstream/plugin.video.xstream#176]
Filme lassen sich nicht streamen.

Nach dem ich den hoster auswähle lädt der Film aber der Player erscheint nicht.

Oben rechts steht steht zwar der Name des Films mit dem Play Symbol aber mehr passiert nichts.

Ich kann momentan von keiner Website ein  Film streamen 

Bei Manchen Website gibt es keine Einträge wie bei kinoger.com

Kodi 19.1
Fire tv Stick HD
xStream 4.0.8

**Comment by DWH-WFC** [comment]
Moin 

paar konkrete Beispiele wären super.
Kinoger funktioniert derzeit nicht da sitzt Cloudflare davor

**Comment by Stivan101** [comment]
> Moin 
> 
> paar konkrete Beispiele wären super.
> Kinoger funktioniert derzeit nicht da sitzt Cloudflare davor 

Z.b Die Mumie Kehrt zurück auf Filmpalast funktioniert nicht. Gestern hat es aber funktioniert

**Comment by DWH-WFC** [comment]
Laufen alle 3 Links super wäre toll wenn du mal dein HTML Cache aus den xStream Einstellungen löschst. Dann Kodi neu startest. Dann probieren alle 3 Links abzuspielen. Und dann gleich das Kodi.log hier mal anhängst.

**Comment by Stivan101** [comment]
Es funktioniert wieder nachdem ich HTML Cache gelöscht und neugestartet habe

**Comment by DWH-WFC** [comment]
Dann war es vermutlich ein temporäres Problem. Wie schaut es mit dein DNS aus wurde das geändert?

**Comment by Stivan101** [comment]
Welche dns meinen Sie? Meinen Sie meine?

**Comment by DWH-WFC** [comment]
Ja im Router und im Endgerät sollte beide mit IPv4 / 6 geändert sein auf Cloudflare/Google oder Quad9 zum Beispiel.

**Comment by Stivan101** [comment]
Ich habe die dns meines Routers wieder auf standard gesetzt aber das ist etwas länger her. Das kann eigentlich nicht der Grund gewesen sein.

**Comment by DWH-WFC** [comment]
Doch mit Standard DNS wirst du kaum Filme oder Serien finden die sich abspielen lassen. 
Ein DNS Wechsel ist zwingend erforderlich

**Comment by Stivan101** [comment]
> Ein DNS Wechsel ist zwingend erforderlich

Ist es möglich in der kodi app die dns einzustellen ohne meine dns vom Router zu ändern?

**Comment by DWH-WFC** [comment]
Warum ? Um Fehlerfrei zu schauen sollten eigentlich beide geändert werden

**Comment by Stivan101** [comment]
Es auf kodi einzustellen ist einfacher als beim Router. Und ich kenne mich mit IT nicht aus. Und ich finde keine tutorial wie man es einstellt denn es gibt viel mehr zu beachten als die dns Eingabe.

**Comment by DWH-WFC** [comment]
Welchen Router und welches Endgerät benutzt du?

**Comment by Stivan101** [comment]
Ist wegen Datenschutz keine so gute idee

**Comment by Heptamer** [comment]
Ich mach hier mal komplett zu, wenn das alles so geheim ist... 🤣😂
