### ISSUE TITLE
Keine Einträge gefunden bei Suche in Aniworld

### ISSUE THREAD

**Issue by ch4oz4ngel** [streamxstream/plugin.video.xstream#177]
Bei Aniworld wird eine Fehlermeldung ausgegeben wenn eine Suche gestartet wird. Nur manuell über A - Z Reiter lassen sich Anime raussuchen. Sollte die Suche verwendet werden dann werden keine Einträge gefunden. Auch bei den Reiter "Alle Serien" werden keine Einträge gefunden.

**Erwartetes Verhalten**
Eine klare Beschreibung was zu erwarten ist

 - Hardware und Betriebssystem: Windows 10
 - Kodi Version:  20.4.0
 - Xstream Version: v4.0.8
 - Resolver Version: v5.1.127

Logs anbei
[kodi.log](https://github.com/streamxstream/plugin.video.xstream/files/14434920/kodi.log)
[kodi.old.log](https://github.com/streamxstream/plugin.video.xstream/files/14434921/kodi.old.log)

**Comment by Heptamer** [comment]
Hi ich habe gerade die Suche mit Vinland Saga getestet, funktioniert problemlos.
