### ISSUE TITLE
Mobilfunk streamen

### ISSUE THREAD

**Issue by ScottLong77** [streamxstream/plugin.video.xstream#178]
Hallo,

leider kann ich den Fehler nicht zuordnen aber zumindest bei Serienstream kann ich mittels FireTV Plugin und Hotspot über meinen über meinen Mobilfunkanbieter ( mit oder ohne VPN ) nicht sistreamen. Ich erhalte jedes Mal die Meldung, dass ich einen sicheren DNS wählen soll. Alles probiert aber der FireTV und Mobilfunk Hotspot wollen einfach nicht. 

Besteht hier nicht die Möglichkeit die Prüfung als freiwillig anstatt auf verpflichtend zu stellen ? 

Ich bin oft auf Reisen und mit FireTV und Handy unterwegs .. würde dann trotzdem gerne auf meinen TV Serien schauen

**Comment by DWH-WFC** [comment]
Das liegt an deinen DNS Einstellungen wie dir deine Meldung schon sagt. Ändere die DNS Einstellungen in deinem Handy oder installiere die entsprechende App und es wird auch funktionieren.
