### ISSUE TITLE
Streamcloud funktioniert nicht

### ISSUE THREAD

**Issue by polojoe** [streamxstream/plugin.video.xstream#179]
**Beschreibe den Fehler**
Kategorien in Streamcloud sind leer, Suche bringt keine Ergebnisse

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: [rpi4 libreelec 12]
 - Kodi Version: [Kodi 21]
 - Xstream Version: [z.B. 4.0.9~nightly16]

**Comment by DWH-WFC** [comment]
Danke für das Feedback wir werden das überprüfen.

**Comment by DWH-WFC** [comment]
Also ich habe es gerade getestet.
StreamCloud läuft in der aktuellen Nightly ohne Probleme.

Ist dein DNS angepasst? HTML Cache mal gelöscht? Steht die Streamcloud Url auf streamcloud.movie?

**Comment by polojoe** [comment]
Heute funktionierts wieder, vielen Dank!
