### ISSUE TITLE
VidMoly Streams funktionieren nicht auf Cineclix

### ISSUE THREAD

**Issue by TimeLance89** [streamxstream/plugin.video.xstream#180]
Hallo, ergeht es nur mir so oder auch anderen?
Egal welchen Stream ich anwähle VidMoly (der erste Streaming Link vom Inhalt meistens) lässt sich nicht abspielen. Im Browser und mit direkter URL der Webseite alles bestens = kann alles abgespielt werden aber über xStream nicht abspielbar.

**Comment by DWH-WFC** [comment]
Da du keine genauen Angaben gemacht hast und nicht unser Fehler melden Issue genommen hast kann ich dir leider nicht weiterhelfen. Vidmoly funktioniert auf Cinemathek sowie auf Cineclix tadellos.
