### ISSUE TITLE
VidMoly lässt sich in den Abendstunden nicht abspielen auf Cineclix

### ISSUE THREAD

**Issue by TimeLance89** [streamxstream/plugin.video.xstream#182]
**Beschreibe den Fehler**
Am Tag kann man den Hoster von CineClix (VidMoly) einwandfrei abspielen, am Abend zu Stoßzeiten schaltet Vidmoly aber um damit der Traffic korrekt verteilt wird.
Aus dem Grund ist der Hoster nicht mehr anwählbar = Fehlermeldung

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Gehe zum CineClix Addon
2. Klicke auf einen der neuen Filme
3. Versuche den Vidmoly Stream ab 21 Uhr zu öffnen
4. siehe Fehler

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: Amazon Fire TV Cube
 - Kodi Version: Kodi 20
 - Xstream Version: Letzte Nightly Version
 - Resolver Version: Aktuellste (wurde extra nochmal gegengeprüft)

**Comment by DWH-WFC** [comment]
Was den Resolver betrifft haben wir keinen Einfluss darauf dann musst du das dem Resolver Team melden.
[ResolveURL](https://github.com/Gujal00/ResolveURL)
xStream liest nur die Links in den Webseiten aus.

**Comment by DWH-WFC** [comment]
Aber wenn ich seh das der Server garnichts an Content wieder gibt.
https://vidmoly.to/
dann ist klar das auch keine Videos abgespielt werden.

**Comment by DWH-WFC** [comment]
Habe das jetz mal bissl beobachtet ich denke das liegt an Vidmoly auf deren Seite ist es dann tot bzw es wird kein Content sichtbar. Da muss man sich an VidMoly wenden. Ich kann deren Webseite dann nicht mal mehr öffnen, wie als wenn die den Server auf Standby schalten.
