### ISSUE TITLE
Handshake Operation timed out

### ISSUE THREAD

**Issue by duczz** [streamxstream/plugin.video.xstream#185]
**Beschreibe den Fehler**
Beim öffnen eines streams kommt seit ca. einer Woche immer folgender fehler

**Screenshots**
![17151895429321653288537632984710](https://github.com/streamxstream/plugin.video.xstream/assets/25475385/8fd0865c-a9eb-4294-a59e-815d467c29eb)

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: [Android TV 9]
 - Kodi Version: [Kodi 20&21]
 - Xstream Version: [4.0.9]
 - Resolver Version: [z.B. 5.1.133]

**Comment by duczz** [comment]
![17152663514959008034455669748292](https://github.com/streamxstream/plugin.video.xstream/assets/25475385/692bdf24-2193-4666-8243-18a401977e05)

**Comment by duczz** [comment]
A workaround for streamtape is to for example to go before via cellphone to the Website and start than the stream, strange

**Comment by Heptamer** [comment]
Internet Provider ist Telekom? Das Problem besteht mit der aktuellen nightly auch noch?

**Comment by duczz** [comment]
Jup, hab es vorhin auch nochmal komplett neu installiert, leider ohne Erfolg.

**Comment by duczz** [comment]
Dns ist Google und cloudflare

**Comment by Heptamer** [comment]
Scheint ein Problem mit der Telekom und dem SSL Zertifikat bzw Handshake von Streamtape zu sein. Kenn da einen der hatte das Problem auch...

**Comment by duczz** [comment]
Hmm okay, könntest du vllt. genaueres rausfinden?
Sprich was er gemacht hat um es zu lösen oder ob er nur gewartet hat?

**Comment by Heptamer** [comment]
Soweit ich weiß ging es auf einmal wieder. Aber ich denke er wird hier noch was dazu schreiben.

**Comment by DWH-WFC** [comment]
Ja ich hatte das Problem bei mir auch. Der Fehler war mit dem Provider Telekom DSL und ging von alleine wieder weg. Hatte auch vieles probiert aber egal auf welchem Endgerät oder Plattform das war überall das gleiche. Egal ob mit Cloudflare oder Google DNS. Nach ein paar Tagen lief alles wieder komischerweise.

**Comment by duczz** [comment]
Danke an euch zwei.
Scheint wieder zu klappen 👍🏻
