### ISSUE TITLE
Kodi Widget-Fehler > ModuleNotFoundError

### ISSUE THREAD

**Issue by Dokukanal** [streamxstream/plugin.video.xstream#186]
Beim Aufruf erhalte ich direkt folgenden Fehler. Es scheint trotzdem zu funktionieren. Aber den Fehler bzw. die Meldung kann man ja im laufe der Zeit mal beheben.

```
("ModuleNotFoundError: No module named 'serienstream_to'",
'\\plugin.video.xtream\\xtream.py",line 148, in parseURL')
```

Ich habe lediglich xStream als Widget hinzugefügt.
Nutzen tue ich Kodi Omega aktuelle Version.

![photo_2024-05-10_13-49-37](https://github.com/streamxstream/plugin.video.xstream/assets/166512533/90953815-1484-41ea-830e-80483fa1a377)

Ich nutze den Skin: https://forum.kodi.tv/showthread.php?tid=337862

Danke für eure Arbeit!

**Comment by Heptamer** [comment]
Hi, hast Du die Fehlermeldung von Hand abgetippt, weil da steht was von xtream anstatt xstream.

Zum anderen, das scheint ein altes Widget zu sein, bzw. alte Favoriten. Da wir intern was geändert haben musst du da wohl alle Filme/Serien löschen oder die entsprechende XML umschreiben. Wir können da nichts weiter machen.

**Comment by DWH-WFC** [comment]
Das ist doch die alte Leia Version wo haste die denn her?

**Comment by Dokukanal** [comment]
> Hi, hast Du die Fehlermeldung von Hand abgetippt, weil da steht was von xtream anstatt xstream?
> 
> Zum anderen, das scheint ein altes Widget zu sein, bzw. alte Favoriten. Da wir intern was geändert haben musst du da wohl alle Filme/Serien löschen oder die entsprechende XML umschreiben. Wir können da nichts weiter machen.

Ja habe ich extra nochmal abgetipp :S
Wo genau muss ich was ändern? Welche XML von was zu was?



> Das war doch in der alten Leia Version. Veraltetes Widget.

![Screenshot 2024-05-11 112345](https://github.com/streamxstream/plugin.video.xstream/assets/166512533/7e3ff3a3-f7ef-4a9a-8e23-b8817c333d04)
![Screenshot 2024-05-11 112417](https://github.com/streamxstream/plugin.video.xstream/assets/166512533/3e49b239-2637-446a-9d35-a8645d31413e)
