### ISSUE TITLE
Fehler beim Öffnen von Streams

### ISSUE THREAD

**Issue by TermsGithub** [streamxstream/plugin.video.xstream#187]
**Beschreibe den Fehler**
Bei einigen Streams bekomme ich Fehler.
(außerdem gibt es noch Probleme mit TMDB Helper, aber das kann auch damit zu tun haben)

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
xstream -> Filmpalast -> Movies -> IMDB rating -> Film auswählen -> Hoster auswählen -> Fehlermeldung

Veev (1080p) -> `AttributeError: 'Nonetype' object has no attribute "get", if jresp.get('file_status')=='OK':`
Streamtape (1080p) -> broken (passt)
VOE -> geht
Filemoon -> broken (passt)
StreamVid -> `Urlerror: <urlopen error [Errno 7] No address associated with hostname>, File "/data/user/0/org.xbmc.kodi/cache/apk/asses/python3.11/lib/pyt line 1351, in do_open`

Anderer FIlm:
Wolfstream ->` HTTPError: HTTP Error 404: Not Found, File: ""/data/user/0/org.xbmc.kodi/cache/apk/asses/python3.11/lib/pyt  line 643, in http_error_default   `   geht auch nicht online, würde mir ein "broken" erwarten.

Anderer Film:
oodstream -> anstatt "doodstream"

**Erwartetes Verhalten**
Das es den Stream öffnet. Bzw. eine Fehlermeldung ausgibt wenn es den Stream nicht mehr gibt.

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: Fire TV Cube 3rd
 - Kodi Version: 20.5
 - Xstream Version: 4.0.9
 - Resolver Version: 5.1.135
-> mit 4.0.10nightly7 bekomme ich die selben Ergebnisse. Wobei da dann in den Settings, beim Updates Tab (Kodi 21.x) dabei steht.

->In tmdb Helper habe ich als players nur eure Liste verwendet, aber wenn ich da die selben Streams über Filmpalast öffne bekomme ich teilweise ganz andere Streams angeboten. Ist das ein Fehler von euch oder tmdb?

**Comment by DWH-WFC** [comment]
Servus getestet mit Dune Teil 2 aus deiner Sparte.

Veev Fehler kommt vom Resolver und nicht von xStream.
StreamTape läuft
VoE Fehler 404 klar weil keine Datei zum abspielen.
Filemoon Fehler 404 klar weil keine Datei zum abspielen.

xStream kann nichts abspielen wenn nichts da ist zum abspielen

**Comment by DWH-WFC** [comment]
Spiderman no Way Home

Wolfstream läuft
Streamtape Fehler 404 klar weil keine Datei zum abspielen
VoE läuft
Filemoon Fehler vom Filemoon Content
UpStream läuft

**Comment by DWH-WFC** [comment]
Also Veev kann man reparieren lassen vom Resolver Team der Rest müsste bei Filmpalast reuppt werden.

**Comment by DWH-WFC** [comment]
xStream ist eine Suchmaschine für Streams.

xStream bringt doch eine Fehler Meldung rechts oben als Benachrichtigung und wenn nötig als Popup

**Comment by DWH-WFC** [comment]
> Resolver Version: 5.1.135
-> mit 4.0.10nightly7 bekomme ich die selben Ergebnisse. Wobei da dann in den Settings, beim Updates Tab (Kodi 21.x) dabei steht.

Das ist klar wir arbeiten immer nur an der neusten Kodi Release Version. Vor dem Release der xStream Versionen testen wir dann auch die Versionen 19 und 20 von Kodi. Im Regelfall da alle Python 3 nutzen sollte es zwecks der Abwärtskompatibilität eigentlich auch keine Probleme geben

**Comment by DWH-WFC** [comment]
> ->In tmdb Helper habe ich als players nur eure Liste verwendet, aber wenn ich da die selben Streams über Filmpalast öffne bekomme ich teilweise ganz andere Streams angeboten. Ist das ein Fehler von euch oder tmdb?

Nenne mal bitte ein Beispiel denn das kann eigentlich nicht sein da die Player Datei nichts anderes macht wie in xStream in Filmpalst gehen und da in der Suche den entsprechenden Film anfragt. Das ist genause wie wenn du selbst in Filmpalast gehst und auf Suche klickst.

**Comment by TermsGithub** [comment]
Okay, ... dachte nicht dass das hier so schnell geht :)

Das "broken" bedeuted, dass der Stream offline ist, ist mir klar. Hab es nur  der Vollständigkeithalber hergeschrieben.

Da ich/ihr schon knapp acht Stunden darauf wartet:
Gibt es im moment ein Problem mit Filmpalast und anderen Addons? Ich bekomme da seit Mittag nur "no entry" und bei vielen anderen Addons (kinox, kinoger,filmkiste) ebenso. 
Und bei HDFilme bekomme ich: "Cloudflare schutz aktiv:... http error 403 forbidden, file: .... line 643, in http_error_default..


Getestet auf Stick und Cube. 
Ich probier morgen nochmal.

**Comment by Heptamer** [comment]
Ja die Seiten haben Cloudflare Anti-Bot-Schutz aktiv, vermutlich wegen zu vielen Zugriffen. Dann geht's ein paar Stunden bis Tage nicht.

**Comment by TermsGithub** [comment]
Okay, ich habe den tmdb "Fehler" gefunden....
Tmdb ist zwar auf German eingestellt aber einige die FIlme werden trotzdem mit ihrem englischem Titel angeführt. Habe jetzt "The New Empire" von tmdb mit "das neue königreich" von filmpalast online verglichen... Und wenn ich das jetzt mit dem filmpalast player suche gibt es mir ganz korrekt die englische Version zurück.
-> Gibt es eine Möglichkeit dies in Zukunft zu verhindern?
Ich lass meine (falschen) Ergebnisse einfach mal stehen, uA wegen dem VOE Fehler..

> 
> Bezüglich tmdb helper:
> 
> tmdb -> Movies -> Trending this Week -> Godzilla x Kong: new empire:  ->player xstream -> filmpalast -> hoster:
> Veev -> gleicher Fehler wie oben(obviously)
> Streamtape -> broken
> VOE -> `HTTPError: HTTP Error 404: Not Found, File: ""/data/user/0/org.xbmc.kodi/cache/apk/asses/python3.11/lib/pyt  line 643, in http_error_default `
> Streamvid -> total Schrott mit 300p und Werbeeinblendungen. Wird da irgendein Erst-release gescrapt?
> Vidmoly -> broken
> 
> 1.) Wenn ich online nachschaue dann fehlt da: Wolfstream und Filemoon und Vidmoly+Streamvid sind zusätzlich.
> 2.) alle Streams haben den Zusatz [1080p], was bei Streamvid nicht stimmt. Kommt das vom Hoster oder euch?
> 3.) VOE + Streamtape funktionieren online.


Okay, dann danke euch!

**Comment by TermsGithub** [comment]
Ach, doch noch was!

Auf meinem Fire TV Stick habe ich Kodi 19.4 und xstream in 4.0.9 bzw 4.0.10 nightly und kann bei beiden nicht auf die Settings zugreifen.
Wodurch anscheinend auch die Settings von Serienstriem und aniworld gelöscht wurden.

Xstream -> langer klick -> Settings und
xstream -> Settings -> xstream Settings  und
xstream -> Addon Settings
wird ein Window "geöffnet", aber es hat keinerlei Inhalt. Kein Text nichts.

**Comment by TermsGithub** [comment]
Leider muss ich noch was adden. 

xstream -> serienstream -> new series -> dark matter -> s1 -> e1 -> automatische auswahl (geht)
tmdb -> (Default player for episodes: xs_serienstream.json play_episode); play automatical -> TV Shows -> Trending this Week -> Dark Matter -> S1 -> e1 -> 
öffnet xStream Search und bekomme dann ein "Select Item" mit cinemathek, moflix-stream, usw. Was seltsam ist, da es die Folge in serienstream ja gibt. Und wenn ich auf einen Anbieter klicke dann wird so ~2 Sekunden der Player geöffnet, dann wieder geschlossen und dann bin ich bei "Videos/xstream", bei der Staffelauswahl von Dark Matter
-> Ich bekomme das selbe verhalten wenn ich den Default Player rausnehme und dann bei der Player-wahl serienstream aussuche.

tmdb -> TV Shows -> Top Rated -> Breaking Bad -> s1 -> e1 -> Player xstream -> serienstream -> läuft
-> Warum bekomme ich da keine Hosterauswahl?

**Comment by DWH-WFC** [comment]
> Ach, doch noch was!
> 
> Auf meinem Fire TV Stick habe ich Kodi 19.4 und xstream in 4.0.9 bzw 4.0.10 nightly und kann bei beiden nicht auf die Settings zugreifen. Wodurch anscheinend auch die Settings von Serienstriem und aniworld gelöscht wurden.
> 
> Xstream -> langer klick -> Settings und xstream -> Settings -> xstream Settings und xstream -> Addon Settings wird ein Window "geöffnet", aber es hat keinerlei Inhalt. Kein Text nichts.

Dann stimmt irgendetwas mit deiner Settings nicht. gehe bitte mal in den Dateimanager. gehe zu den benutzerdaten und suche nach Addon_data darin gibt es den Ordner plugin.video.xstream und darin eine settings.xml.
Lösche diese und starte neu. Gehe in die xStream Einstellungen und teste.

**Comment by DWH-WFC** [comment]
> Leider muss ich noch was adden.
> 
> xstream -> serienstream -> new series -> dark matter -> s1 -> e1 -> automatische auswahl (geht) tmdb -> (Default player for episodes: xs_serienstream.json play_episode); play automatical -> TV Shows -> Trending this Week -> Dark Matter -> S1 -> e1 -> öffnet xStream Search und bekomme dann ein "Select Item" mit cinemathek, moflix-stream, usw. Was seltsam ist, da es die Folge in serienstream ja gibt. Und wenn ich auf einen Anbieter klicke dann wird so ~2 Sekunden der Player geöffnet, dann wieder geschlossen und dann bin ich bei "Videos/xstream", bei der Staffelauswahl von Dark Matter -> Ich bekomme das selbe verhalten wenn ich den Default Player rausnehme und dann bei der Player-wahl serienstream aussuche.
> 
> tmdb -> TV Shows -> Top Rated -> Breaking Bad -> s1 -> e1 -> Player xstream -> serienstream -> läuft -> Warum bekomme ich da keine Hosterauswahl?

Kann ich nicht nachvollziehen.
Hast du deine Oberfläche in English und zufällig die Sprache in xStream auf English?
Ich bekomme bei Dark Matter sowie bei Breaking Bad je VOE und Streamtape angezeigt.

**Comment by DWH-WFC** [comment]
Bedenke bei Dark Matter in Filmpalast gibt es unterschiedliche Beiträge mit unterschiedlichen Links.

**Comment by DWH-WFC** [comment]
_Anzeigenamen überarbeitet._
_TMDb Helper Dateien aktualisiert._
