### ISSUE TITLE
Cloudflare Schutz aktiv !!!

### ISSUE THREAD

**Issue by biersn** [streamxstream/plugin.video.xstream#188]
**Beschreibe den Fehler**
Cloudflare Schutz aktiv desöfteren bei einigen Seiten wie Filmpalast. 

**Screenshots**
![Zwischenablage01](https://github.com/streamxstream/plugin.video.xstream/assets/170828339/06eb8c09-6d87-4b8a-b17a-a23d7c3bcfbe)

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Kodi Version: [z.B. Kodi 21]
 - Xstream Version: [z.B. 4.0.2~nightly1]
 - Resolver Version: [z.B. 5.1.8.9]

**Comment by Heptamer** [comment]
Das bedeutet das die Seite einen Anti-Bot-Schutz (Cloudflare) aktiviert hat, vermutlich wegen zu vielen Zugriffen. Das kann dann schon mal Stunden bis Tage dauern bis der dann weg ist. Also ab und zu einfach mal probieren.
