### ISSUE TITLE
Upnext addon

### ISSUE THREAD

**Issue by Ghb3245** [streamxstream/plugin.video.xstream#189]
ist es möglich, hinzuzufügen
integrieren Upnext addon 

um die nächste Folge automatisch abspielen

Überprüfen Sie dies, vielleicht kann es helfen

’https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/upnext.py’

**Comment by DWH-WFC** [comment]
Guten Tag

Upnext wollen wir nicht in xStream integrieren. 

Aber:
Sie können diese Funktion durch verschiedene Skins/Themes oder durch den TMDb Helper auch ohne Integration nutzen.
