### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Kaimandura** [streamxstream/plugin.video.xstream#19]
No modul named Kinoger.com/plugin.video.xstream/xstream.py", line 237, in parseUrl.
Wie kann man den Fehler beheben??

**Comment by DWH-WFC** [comment]
Derzeit nur in dem du die alte Seite noch nutzt
https://kinoger.to/plugin.video.xstream/xstream.py
anis3 wird sicher irgendwann ein Fix dazu bereit stellen bis dahin einfach im lib Ordner die Kinoger.py umschreiben und darin Kinoger.com zu Kinoger.to ändern

**Comment by anis3** [comment]
Hallo Kaimandura
also 
Kinoger.com/plugin.video.xstream/xstream.py
kann nicht stimmen wenn so
Kinoger_com/plugin.video.xstream/xstream.py

so wie sich dein fehler anhört
ist bei dir die settings.xml zerschossen
kannst du bitte mal xStream deinstallieren
und neu installieren und bescheid geben ob es
jetzt funktioniert weil ich kann den fehler nur nachstellen
wenn ich die settings.xml beschädige
oder hast du die datei schreibgeschützt???
dann tritt auch die fehlermeldung auf
weil ich habe das siteplugin von
kinoger_com.py in kinoger.py
umbennant weil ich hinzugefügt haben das
man in der seite einstellen kann ob von
kinoger.com oder kinoger.to die daten bezieht
wenn der fehler weiter besteht bitte
kodi version & betriebsystem
brauche ich dann als info
gib bitte bescheid

@DWH-WFC
tritt der fehler auch bei dir auf???
wenn ja dann brauche ich auch
kodi version & betriebsystem
LG Anis

**Comment by Kaimandura** [comment]
Also ich habe jetzt auf kinoger.to umgestellt und es funktioniert

**Comment by DWH-WFC** [comment]
Der Fehler kommt nur wenn in den Settings der Eintrag auf kinoger.com gestellt ist:

**Comment by DWH-WFC** [comment]
Habe ich heute erst nach einer Neuinstallation entdeckt.

**Comment by anis3** [comment]
danke DWH-WFC
dank dir kann ich den fehler jetzt nachstellen
und weiß ich jetzt warum die fehlermeldung kommt
also du hast xStream über repo installiert
dann hast du xStream gestartet
von repo hieß die datei kinoger_com.py
da beim start die liste erstellt wird mit
verweiß auf die datei kinoger_com.py
kommt der fehler weil ich habe die datei
kinoger_com.py in kinoger.py
umbenannt weil ich die .to
domain hinzugefügt habe
und nach den update wo
kommt ist die datei nicht mehr
vorhanden was den fehler
verursacht wenn der fehler kommt
braucht man nicht auf die .to umstellen
sondern nur kodi neu starten
die tage kommt ein repo update
dann ist der fehler behoben
vielen dank 

DWH-WFC & Kaimandura

**Comment by DWH-WFC** [comment]
Habs gerade nochmal als Test frisch installiert und es kommen 2 Fehler
<img width="960" alt="Unbenannt1" src="https://user-images.githubusercontent.com/45105289/75849598-847e8700-5de5-11ea-967e-fcc252b7b6ba.png">


<img width="960" alt="Unbenannt" src="https://user-images.githubusercontent.com/45105289/75849622-9102df80-5de5-11ea-8723-e91c97e488bc.png">

Hab dir die Bilder nochmal angehängt damit du schneller findest.
Grüße DWH

**Comment by DWH-WFC** [comment]
das kommt nach der Installation aus der Repo vor dem Auto Update ;-)

**Comment by DevTeamLast01** [comment]
Der Fehler wird nun nach der Installation aus dem Repo bei einem Neustart von Kodi automatisch korrigiert.

**Comment by DWH-WFC** [comment]
Top dann kann‘s closed 👍

**Comment by DevTeamLast01** [comment]
closed
