### ISSUE TITLE
Episoden suche in suche

### ISSUE THREAD

**Issue by blatorone** [streamxstream/plugin.video.xstream#191]
Ist es möglich eine Episoden suche zu integrieren, Beispiel wenn ich auf aniworld direkt auf der Seite die gesuchte Episode einer Serie eingebe wird diese gefunden, wenn ich über xstream die gesuchte Episode eingebe dann wird diese nicht gefunden sondern nur wenn ich den Titel der Serie eingebe und danach die gesuchte Episode Manuell in der Liste suchen muss

**Comment by Heptamer** [comment]
Nenn bitte mal ein Beispiel von so einer Suche.

**Comment by blatorone** [comment]
Wenn ich als Beispiel one piece eingebe finde ich die Serie natürlich wie gewohnt und kann auch die einzelnen Staffeln auswählen, wenn ich allerdings als Beispiel Staffel 16, folge 23 Eine brennende Leidenschaft - Rebecca gegen Suleiman.
Gebe ich bei aniworld Eine brennende Leidenschaft - Rebecca gegen Suleiman
Ein wird er dieses finden, gebe ich dies allerdings bei der globalen Suche oder aniworld über xstream ein findet er dieses nicht. Aufgefallen ist mir es erst nachdem ich versuche über den Moviedb helper was ausprobiert habe und beim auswählen keine Trakt Funktionen übernehmen konnte da die Serie komplett Manuell neu ausgewählt werden musste

**Comment by Heptamer** [comment]
Also wenn ich das eingebe kommt nirgendwo was. Gib mir bitte den genauen Suchstring, den du eingibst, in einer Zeile.

**Comment by blatorone** [comment]
Ok sorry ein Fehler meinerseits, gebe ich ein 

Eine brennende Leidenschaft - Rebecca gegen Suleiman

Erscheint auch bei aniworld nichts

Gebe ich allerdings alles vor oder nach dem Bindestrich ein, dann erhalte ich die gesuchte Folge bei aniworld auch noch einmal bei xstream getestet dort wird es nicht gefunden 

Also Eingabe 

Eine brennende Leidenschaft - Rebecca gegen Suleiman 

Kein Ergebnis 

Eingabe 

Eine brennende Leidenschaft

Oder 

Rebecca gegen Suleiman 

Dann erhalte ich bei der Suche bei aniworld 

Sorry meinerseits ich hatte glaube ich jetzt ein blödes Beispiel genommen da ich in dieser Folge als letztes war 😅, ich wusste nicht mehr genau mit welcher Folge ich es getestet hatte

**Comment by Heptamer** [comment]
Ah ok, probiere ich morgen mal aus. Sind Ferien, da machen wir nicht viel, Familien gehen vor 😉

**Comment by blatorone** [comment]
Kein Problem 😉 habe ich natürlich Verständnis für und eilt ja auch nicht😜.

**Comment by DWH-WFC** [comment]
Also die Suche nach Episoden mit Name wird nicht unterstützt. Es wird nach Serienname S03 E05 gesucht aber nicht nach dem direkten Episoden Namen.

**Comment by DWH-WFC** [comment]
Das wird weder von Aniworld noch von S.to unterstützt und somit wird in der Suche auch nichts gefunden. Die Suche in Aniworld bringt daher auch kein Eintrag.

**Comment by blatorone** [comment]
Hab mal Screenshots gemacht oder habe ich die falsche Seite 😅 wenn es nicht geht, dann geht's nicht funktionieren tut es ja trotzdem ![image](https://github.com/streamxstream/plugin.video.xstream/assets/129631643/ed5b4bd7-8a04-4d28-942e-90bd29a9acec)

![image](https://github.com/streamxstream/plugin.video.xstream/assets/129631643/df47f0f9-1d71-4f52-a6b6-d7a861b3795e)

Hoffe die Bilder laden auch

**Comment by Heptamer** [comment]
Ach Du hast direkt auf der Seite gesucht... Es gibt zwei Suchen bei Aniworld und s.to die aber überdurchschnittlich arbeiten und auch unterschiedliche Ergebnisse liefern. 

Die Du benutzt ist JSON basiert, dafür hatte ich früher eine Suchroutine Geschehen gehabt, wir haben aber gemerkt dass die JSON Suche nicht immer alles findet bzw. false positive meldet. 
Daher sind wir wieder zurück auf die normale HTML/DB suche zurück, die ist zwar eingeschränkter von den Suchparametern, findet aber alles und ist TMDb konform.

**Comment by blatorone** [comment]
Hatte ich im zweiten Beitrag 😝 suche bei aniworld Seite und suche aniworld xstream, aber ok dann weiß ich Bescheid und danke für die Mühe 😊

**Comment by Heptamer** [comment]
Hab ich bei dem ganzen Text wohl überlesen 😂 Ich mach dann mal zu.
