### ISSUE TITLE
DNS-Lock option

### ISSUE THREAD

**Issue by herrdemo** [streamxstream/plugin.video.xstream#192]
… ist die diese DNS Lösung nicht was für xStream
Kodi Video Plugin for Filmpalast.to with byPass DNS-Lock option
https://github.com/seizu/plugin.video.filmpalast.ex

**Comment by DWH-WFC** [comment]
Dann würden wir ja die User zu einem festen DNS zwingen. In dem Fall was du vorschlägst dann Cloudflare.
Meiner Meinung steht es jedem Frei sein DNS selbst zu wählen. Ich sehe da keinen Mehrwert drin dies zu implementieren.

Und die paar Zahlen in den Router zu schreiben sollte jeder schaffen.

**Comment by herrdemo** [comment]
@Heptamer 
ja habe ich und es funktioniert gut ;-)
@DWH-WFC 
da hast du natürlich recht aber wenn es über die config zuschaltbar ist kann ja jeder selbst entscheiden. ich denke es gibt genug die mit den dns einstellungen in den routern überfordert sind und so wieder zugriff auf einige seiten mehr haben :-) 

... super programm guter support weiter soooo

**Comment by Heptamer** [comment]
OK weil konnte es gestern nicht testen. 

Optional wäre das vielleicht sogar eine Überlegung wert, wir besprechen das mal intern.
