### ISSUE TITLE
Fehler Melden

### ISSUE THREAD

**Issue by leonistlol1** [streamxstream/plugin.video.xstream#2]
Ehm Irgendwie komme ich nicht mehr auf den Addon drauf und ich kann den addon auch nicht aktualisieren 
Kodi 21.0

**Comment by DWH-WFC** [comment]
Bitte die Vorlage vom Protokoll vollständig ausfüllen und Kodi.log Datei dazu anhängen

**Comment by DWH-WFC** [comment]
Da hier nichts mehr kommt mache ich zu.
