### ISSUE TITLE
No complete scrolling for Settings/Index-Sites

### ISSUE THREAD

**Issue by certain2** [streamxstream/plugin.video.xstream#22]
It´s not possible to reach the area in settings/index-sites between Movietown and Streamking, when using keyboard direction buttons or tv-remote.

So, for example, serienstream.to account configuration on an AndroidTV/Shield is not possible with remote.

Only mousewheel scrolling seems to be working.

**Comment by DWH-WFC** [comment]
Thank you for your information. The xStream developer is already aware of this error.

**Comment by DevTeamLast01** [comment]
is done
