### ISSUE TITLE
AlleSerien Fehler

### ISSUE THREAD

**Issue by DWH-WFC** [streamxstream/plugin.video.xstream#26]
Und zwar ist ab und zu bei Alle Serien ein Fehler das man im Reiter Serien z.B. Neustes Release kein Eintrag vorhanden steht. Über die Suche ist aber alles zu finden. Betrifft nur den Reiter Serien.

**Comment by anis3** [comment]
Hallo @DWH-WFC 
das ist mir auch schon aufgefallen das liegt aber an der seite wenn recht
ausgelastet kommt der fehler ist auch bei den hoster von der seite so
da kann man leider nichts machen

also nicht das ich dich falsch verstehe fehlermeldung

xStream Es wurde kein Eintrag gefunden

nach ein paar minuten funktionierts wieder

LG Anis

**Comment by DWH-WFC** [comment]
Richtig

**Comment by DevTeamLast01** [comment]
closed
