### ISSUE TITLE
Metahandler

### ISSUE THREAD

**Issue by DWH-WFC** [streamxstream/plugin.video.xstream#27]
Seit geraumer Zeit gibt es ein Problem zwischen xStream und dem Metahandler. Vielleicht hat auch jemand Zeit sich diesem Problem zu widmen.

<img width="960" alt="Unbenannt" src="https://user-images.githubusercontent.com/45105289/76068338-46be6180-5f91-11ea-848a-76cd3ee7a1d3.png">

Wäre schön wenn dieser wieder funktioniert. Der Fehler tritt auf wenn der Metahandler aktiviert wird und man über xStream in die Einstellungen will.

**Comment by DevTeamLast01** [comment]
metahandler macht bei xstream keinen Sinn. Dazu müsste weit aus mehr umgebaut werden!

**Comment by DevTeamLast01** [comment]
wenn mal ganz viel zeit ist! z.B. im nächste Winter ;-)
closed
