### ISSUE TITLE
service.py verändert Kodi settings

### ISSUE THREAD

**Issue by DWH-WFC** [streamxstream/plugin.video.xstream#28]
Und zwar der Eintrag der service.py verändert in Kodi eine Einstellung. Hab mich heute früh gewundert und mich fast dämlich gesucht. Hab aber den Fehler bzw. den Verursacher gefunden. und zwar in der service.py ist es folgender Eintrag:

```
##ka - remove parent directory (..) in lists
if not 'false' in xbmc.executeJSONRPC('{"jsonrpc":"2.0", "id":1, "method":"Settings.GetSettingValue", "params":{"setting":"filelists.showparentdiritems"}}'):
    xbmc.executeJSONRPC('{"jsonrpc":"2.0","method":"Settings.SetSettingValue","id":1,"params":{"setting":"filelists.showparentdiritems","value":false}}')
    xbmc.executebuiltin("ReloadSkin()")
```
Der Eintrag verursacht das folgende Einstellung zurückgesetzt bzw. ausgeschaltet wird.

<img width="960" alt="Unbenannt" src="https://user-images.githubusercontent.com/45105289/76091876-b0089980-5fbe-11ea-8f7c-ce17db332252.png">

Dies passiert gleich nach dem Reload Skin Befehl.
Bitte dies mal wenn ihr Zeit habt bitte noch beheben.

Danke Jungs 
Grüße DWH-WFC

**Comment by DWH-WFC** [comment]
Also wenn man den Code Teil löscht dann funktioniert es natürlich auch wieder, aber das ist ja nicht Sinn der Sache.

**Comment by kasi45** [comment]
LOL - ich wollte die ".." nicht haben, und habe in den Kodi Einstellungen nicht die Stelle gefunden wo man den Parent ausschalten kann. Und weil ich nun mal den Python Source hatte um dies ....

kann dann wieder raus!

**Comment by DevTeamLast01** [comment]
done
