### ISSUE TITLE
Fehler Plugin Serienstream

### ISSUE THREAD

**Issue by Wichtelchen1973** [streamxstream/plugin.video.xstream#3]
In der Nightly und der Release Version funktioniert das Plugin Serienstream.to nicht mehr.

Die Menüpunkte "alle Serien" , "Neue Folgen" , "Neue Serien" etc. generieren eine Fehlermeldung.

ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.xstream/?function=showAllSeries&sUrl=https%3a%2f%2fs.to%2fserien&site=serienstream&title=Alle%20Serien&trumb=C%3a%2fUsers%2fWichtelchen%2fAppData%2fRoaming%2fKodi%2faddons%2fplugin.video.xstream%2fresources%2fart%2fsites%2fserienstream.png

ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.xstream/?function=showAllSeries&sUrl=https%3a%2f%2fs.to%2fserien&site=serienstream&title=Alle%20Serien&trumb=C%3a%2fUsers%2fUserNaame%2fAppData%2fRoaming%2fKodi%2faddons%2fplugin.video.xstream%2fresources%2fart%2fsites%2fserienstream.png)

**Comment by DWH-WFC** [comment]
Bitte das Fehler Protokoll richtig ausfüllen!

**Comment by Wichtelchen1973** [comment]
Fehler im Pugin Serienstream. 
Alle Münupunkte wie z.B. "Neue Serien", "Neue Episoden" 
führen zu dem Fehler "No entry was found".

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Kodi starten
2. Addon xStream ausführen
3. Scrolle hinunter bis Serienstream
4. Klicke Serienstream
5. Klicke z.B. auf "Alle Serien / All Series"

**Erwartetes Verhalten**
Es wird statt einer Fehletrmeldung eine Auswahl von Folgen oder Serien erwartet.

**Screenshots**
Screenshot ist beigefügt

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: Windows 10, Windows 11 und Android (Waipu Stick)
 - Kodi Version: Kodi 19.3, 19.5, 21.0]
 - Xstream Version: 4.1.1-nightly3 und 4.1.0 (Release)
 - Resolver Version: aktueller Release und Nightly

[kodi.log](https://github.com/user-attachments/files/16518242/kodi.log)
![XSTREAM](https://github.com/user-attachments/assets/76c5b99b-b7c2-4137-ad7f-ab8c1ef9a4ee)

**Comment by DWH-WFC** [comment]
Schalte Kodi bitte aus. Gehe auf S.to mit einem Gerät was sich im gleichen Netzwerk befindet. Melde dich bitte mit dem gleichen Account an. Bestätige falls nötig die Bot Abfrage. Starte danach Kodi und teste. Falls nicht gehe in die xStream Einstellungen auf Indexseiten 2 und Wechsel bei SerienStream bitte die Domain von S.to auf einen der anderen Domains.

**Comment by Prometheusx-git** [comment]
Das sind mir nach einem Tippfehler im Code aus:
trumb statt thumb:
function=showAllSeries&sUrl=https%3a%2f%2fs.to%2fserien&site=serienstream&title=Alle%20Serien&**trumb**=

Ich würde ja selbst in den Code von serienstream.py schauen, aber der zlib komprimierte, base64 codierte Quatsch ist mir zu blöd..

**Comment by Wichtelchen1973** [comment]
Die ersten Schritte (Kodi aus, auf S.to mit Accountdaten anmelden) hatten ausgereicht. Danach hatte Serienstream wieder funktioniert.

**Comment by Wichtelchen1973** [comment]
P.S. Eine Einstellung zum Wechsel der s.to Seite konnte ich weder in der Nightly noch Release finden.

**Comment by DWH-WFC** [comment]
@Prometheusx-git nein das ist derzeit kein Schreib Fehler.

@Wichtelchen1973 
Schön das es wieder läuft. Stelle bitte deine Kodi Einstellungen von Standard auf Experte um da sind die Einstellungen auch sichtbar. Im Regelfall sollten diese aber auch laufen
