### ISSUE TITLE
Bugs in Menülisten

### ISSUE THREAD

**Issue by MartinX3** [streamxstream/plugin.video.xstream#3]
Setup: Raspi 3b, LibreElec 9.0.2, Kodi 18.2, TV mit HDMI-CEC

Beim Scrollen mit der Fernbedienung bleibe ich an Texteingabefeldern oder Pfeileingabefeldern hängen.
In beiden Scrollrichtungen das gleiche Problem.
Vermutlich habe ich dadurch keinen Zugriff auf manche Einstellungen/Resolver.

Vielleicht gibt es interne Pläne die UI zu überarbeiten, dann wäre mein Issue-Ticket obsolet.

PS: Danke, dass Ihr Lastship beerben wollt!

**Comment by anis3** [comment]
@MartinX3 
sorry hatte die tage keine zeit
meinst du den UrlResolver???
sorry daran arbeite ich nicht
oder xStream Einstellungen???
kannst du genau beschreiben wo dein problem ist

ps  Lastship beerben nein xStream ist älter als Lastship

LG Anis3(xStream Entwickler)

**Comment by MartinX3** [comment]
Hey @anis3
Kein problem, wir sind ja alle freiwillig hier

Es geht nur um die Einstellungen in der APP xStream
Ich kann nicht durch alle listen Elemente eines tabs dort
Der bleibt einfach hängen
Entweder an freitext eingabefeldern oder solchen mit 2 Pfeilen zum eingeben des Wertes

Ups
Dachte ich hätte irgendwo, gelesen, dass xstream nach der lastship Beendigung verstärkt als Ersatz in Sachen Ergonomie forciert wird und die lastship Entwickler zu xstream wechselten

**Comment by anis3** [comment]
nein xStream ist aktulle leider bei der enwicklung ein 1 mann projekt
ich gehöre/gehörte nur den Lastship team an habe bei lastship
hier und da mal was gefixt aber ich wollte/will xStream nicht sterben
lassen darum mich auf xStream fokusiert was wie du siehst die
richtige enscheidung war

LG Anis

**Comment by MartinX3** [comment]
Du konntest das Problem lösen? Cool
