### ISSUE TITLE
ResolveURL

### ISSUE THREAD

**Issue by goceti** [streamxstream/plugin.video.xstream#31]
https://github.com/jsergio123/script.module.resolveurl

Das könnte statt URLResolver genutzt. Da wird auch keine Scheiße von TVAddons eingebaut, die wahrscheinlich der Grund für die eigene Version von xStream war.

Ist momentan noch nicht Python 3 kompatibel aber das sollte kein großes Problem sein.

**Comment by sraedler** [comment]
Besser das Repo von Gujal (ist immer der aktuelle jsergio123 stand): https://github.com/Gujal00/smrzips

**Comment by anis3** [comment]
@goceti 
nein den von jsergio123 wird es für xStream in der nächsten zeit nicht geben
weil da ist nicht geplant in naher zukunft py2-3 kompatibilität

du meinst "das sollte kein großes Problem sein."
kommt drauf an gibt mehrere wege nach rom
1. zwei verschidene versionen vorteil keine altlast
2. py23 kompatibel schwer umzusetzen schleicht sich schnell fehler ein aber von kodi empfohlem
3. six benutzen

ich habe mich bis jetzt nicht entschieden wie ich vorgehe
aktuell habe ich ne version py23 aber läuft nicht perfekt(xStream)
ich exprimiere gerade dann muss aber auch der urlresolver angepasst werden
sonst funktionieren die meisten seiten nicht ich versuche es die tag mal mit six
LG Anis

**Comment by goceti** [comment]
Habe in dem anderen issue futurize verlinkt. Das macht das weitestgehend automatisch und dann braucht es nur noch etwas händische Nacharbeit. Das bindet auch automatisch six ein damit es abwärtskompatibel bleibt. 

Du könntest das theoretisch auch über resolveurl laufen lassen und dann einen pull request draus machen.

**Comment by anis3** [comment]
@goceti 
checke mal die aktuelle kodi 19
da kannst du nich mal nen standard addon innstallieren
also heißt es abwarten wie es sich entwickelt
LG Anis

**Comment by goceti** [comment]
Habe mir die Nightly runtergeladen vom 19.04. und alles funktioniert ohne Probleme. Was genau meinst du?

Ich habe auch eine Version von ResolveURL für Python 3 allerdings funktioniert die dann nicht mehr unter Python 2 weil die cookielib dann was aufruft was future nicht patcht.

**Comment by streamxstream** [comment]
ResolveURL von Jsergio und URLResolver von uns sind jetzt Py2 und Py3 tauglich.
Einen eigene Resolver nutzen wir um flexibel und unabhängig zu sein
Daher schliesse ich das Issue mal
