### ISSUE TITLE
Scraping Status

### ISSUE THREAD

**Issue by goceti** [streamxstream/plugin.video.xstream#32]
Letztens hat bei der globalen Suche ein Scraper gehangen und auch nach Minuten ging es nicht weiter. Musste Kodi komplett killen.

Gibt es kein Timeout für die Requests? Wenn doch wie hoch ist das?
Und wäre es möglich in der Box anzuzeigen welche Seiten schon geantwortet haben oder auf welche noch gewartet wird und so? Also ein Fortschritt quasi? Dann könnte man in solchen Fällen das fehlerhafte Plugin erkennen und deaktivieren.

**Comment by anis3** [comment]
Hallo @goceti kannst du in xStream in den einstellungen sehn standard 30 sekunden

**Comment by goceti** [comment]
Ja war auf 30 Sekunden. Ich habe deutlich länger gewartet aber es hat sich nichts mehr getan. Da hat nur noch geholfen kodi neu zu starten. Hat sich wohl bei einem plugin irgendwie aufgehangen
