### ISSUE TITLE
Movie4k funktioniert nicht mehr

### ISSUE THREAD

**Issue by Lial90** [streamxstream/plugin.video.xstream#34]
Nach kurzer Zeit erscheint die Meldung "Fehler beim Abrufen der URL: .../index.php" und unter der Rubrik Genre wird kein Fehler ausgegeben, jedoch werden keine Daten angezeigt.
Auch das ändern URL bringt keine Besserung. Nach einigem herrumklicken kam mal eine Fehlermeldung über einen AttributeError aus der cloudflare.py Zeile 514. Diesen Fehler konnte ich jetzt leider nichtmehr auf die schnelle produzieren

**Comment by anis3** [comment]
ist ein cloudflare problem weiß aber das es nicht immer auftritt deswegen heißt es warten weil ich kann nicht testen wenn es z.B. nur alle 20 mal auf tritt
