### ISSUE TITLE
Anmeldung bei serienstream.sx neu mit E-Mail statt Benutzernamen

### ISSUE THREAD

**Issue by phoberus** [streamxstream/plugin.video.xstream#35]
Die Anmeldung auf serienstream.sx erfolgt nun mit E-Mail und Passwort, vorher war es noch der Benutzername. In xStream steht noch immer Benutzername. Es gibt keine Fehleranzeige, die Videos werden einfach nicht gestartet. Nachdem beim Benutzer die E-Mail eingegeben wurde, klappt alles perfekt. Also wäre es gut, den String Benutzername in E-Mail zu ändern bei diesem Anbieter

**Comment by streamxstream** [comment]
Behoben mit  xStream 3.5.15~nightly2
