### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by Fantasymerlin** [streamxstream/plugin.video.xstream#36]
Bei einigen Indexseiten kommt der Fehler...

UnboundLocalError
Local variable 'url_end' referenced before assignment in... ccloudflare.py line 494.

Tritt zb bei movie4k und bei xcine.tv auf.

Im nightly und auch in nightly version 3.5.15

**Comment by codingPF** [comment]
Macht es sinn sich das anzusehen...das cloudflair Zeug ist schon sehr kompliziert?
Oder kümmert sich jemand darum?

**Comment by anis3** [comment]
aktuell gibt es keine lösung leider
