### ISSUE TITLE
Links menü "gesehen" muss immer neueingestellt werden nach neustart kodi

### ISSUE THREAD

**Issue by ollie2202** [streamxstream/plugin.video.xstream#39]
Servus Anis3,
könntest du vielleicht mal schauen wenn man in xstream drin ist und nach links klickt kommt ein auswahl menü da kann man auswählen "noch nicht gesehen" wenn man das auswählt ist alles ok aber wenn man neustartet ist es wieder raus und man muss es neu auswählen. vielleicht gibt es da einen trick wie man es für immer auswählen kann?! danke dir schon mal fürs bemühen.

Gruss Ollie

**Comment by anis3** [comment]
@ollie2202
das haben wir ja schon über gitter diskutiert ich
mache hier mal zu
