### ISSUE TITLE
Deadlock während globaler suche und während dem abbrechen der Suche

### ISSUE THREAD

**Issue by kloklojul** [streamxstream/plugin.video.xstream#42]
Wenn man derzeitig eine Global Search macht, dann bleibt die Suche zu 80% bei "KinoX returned" stecken. Zu 20% bleibt die Suche bei einem anderen Hoster stecken, aber es bleibt immer zu 100% stecken. Wenn man versucht die Suche abzubrechen, ändert sich nur der Titel des popups zu "Canceling..." und es bleibt weiterhin stecken. Habe in beiden Fälle versucht zu warten, allerdings nach 30 minuten aufgehört. An dieser Stelle hilft nur noch ein Reboot über SSH oder halt Stecker ziehen. Mein benutztes System ist ein Raspi3 mit Libreelec. Ich habe testweise eine frische Installation von libreelec und xStream auf einem Pi0 probiert mit dem selben Ergebniss. Im Error-Log wird nichts hinterlegt.

**Comment by DWH-WFC** [comment]
Schau mal in den XStream Einstellungen unter Hostern nach welche Domain ausgewählt ist. Und prüfe mal bitte ob die im Browser funktioniert ggf. Domain wechseln

**Comment by kloklojul** [comment]
Habe von der standart domain von kinox auf kinox.to gewechselt, jetzt dauert es zwar immernoch lange ( 5min ca.) aber wenigstens bekomme ich ergebnisse, das einzige problem, das ich noch habe ist, dass die meiste Zeit keine Streams funktionieren. 
Hier ein paar mehr Eckdaten, vielleicht hilft es ja. 
Als DNS habe ich 8.8.8.8
die serie, die ich versuche zu schauen ist dr.house season 1
die folgen funktionieren ohne probleme, wenn ich sie über den browser aufrufe (getestet mit kinox und serienstream)

**Comment by kloklojul** [comment]
beim streamkiste kommt auch folgender fehler
https://i.imgur.com/BQAtkIj.png

**Comment by kloklojul** [comment]
Bei kinox bekomme ich auch folgenden error log https://i.imgur.com/YuM7Y3c.png

**Comment by anis3** [comment]
streamkiste fix
