### ISSUE TITLE
HDFilme: Wiedergabe springt

### ISSUE THREAD

**Issue by r2ixuz** [streamxstream/plugin.video.xstream#43]
Während der Wiedergabe springt das Bild und der Ton ein paar Sekunden vor. Dabei bleibt die Zeitleiste von Kodi unverändert.

Das tritt mal mehr mal weniger häufig auf (völlig sporadisch). Egal ob 720p oder 1080p. (RPi4b mit Libreelec 9.2.5)

**Comment by V10lator** [comment]
Same here (CoreELEC 9.2.5 auf einem AML-S905X-CC). Why has this been closed?
