### ISSUE TITLE
python kompatibilität

### ISSUE THREAD

**Issue by damnms** [streamxstream/plugin.video.xstream#45]
ich hab den source mal eben ausgecheckt, weil ich mir dachte ich schau mal rein, vll finde ich den ein oder anderen fehler, weil manchmal das UI hängt. 
da ist mir im pycharm aufgefallen, dass es recht viel meckert wegen 3.9 kompatibilität.
nun stellt sich mir die frage: gibt es einen branch oder ist das thema python 3 noch gar nicht beruecksichtigt? 
auch wegen kodi 19, was ja nur noch python 3 kann.

hab mal eben sonar laufen lassen: https://sonarcloud.io/dashboard?id=damnms_plugin.video.xstream

**Comment by anis3** [comment]
Hallo damnms
xStream ist  Python 2/3 kompatibel &
läuft ohne problem mit der aktuellen Kodi 19 Beta 2 (benutzt Python 3.8.5)

UI hängt?? du meinst beim start von xStream???
das liegt daran weil der alte cache geprüft/gelöscht wird

sonarcloud kannte ich noch garnicht
hilft mir die Code Quality zu erhöhen danke
bitte weiter so

komme gut ins neue Jahr

LG Anis

**Comment by damnms** [comment]
haette genauer schreiben sollen was ich mein mit "ui haengt", my bad ;) 
geht da drum wenn man einen stream versucht zu oeffnen, dann kackt das manchmal ab. ich vermute mal, da kommen fiese codes (400er, 500er, etc.) und kodi oder das plugin koennen damit nicht so wirklich sauber umgehen.
daher dachte ich mir, ich debugge das einfach mal.
hab pycharm professional und hab das plugin da rein geladen aber erhalte einige fehler.
ich nutze fedora, das hat nur python 3.9, nicht 3.8, aber ich glaub die fehler sollten auch im 3.8 erscheinen (bin kein python profi! vll irre ich mich da auch...)

beispiel:
resources/lib/fixetzipfile.py:814
Python version 3.9 does not support this syntax
diese codezeile: 
raise BadZipfile, "File is not a zip file"

**Comment by anis3** [comment]
die fixetzipfile.py wird nur unter android kodi 18 benötigt
und ja der code ist nicht der beste habe aber nichts besseres für das problem

pycharm:
das zeigt aber hauptsächlich PEP 8 fehler
um die zu beseitigen müsste ich XS komplett neuschreiben
damit es PEP 8 coding style entspricht
aber ich werde die Code Quality verbessern
in nächster zeit

LG Anis

**Comment by damnms** [comment]
jo war kein bemängeln oder so ;) 
dachte mir vll kann ich was bei helfen 

ich kenn die warnings und errors von pycharm zu wenig (und auch der fehlende python skill), daher kann ich das nicht genau beurteilen. aber es zeigt halt schon einige an: in der Kategorie General 39 errors (und 31 warnings) und Kategorie Python 52 Errors und viele andere warnings. Aber eben, ich kann das nicht einschätzen, da bist du mir um Längen voraus was das einschätzen angeht.

Andere Frage: wie entwickelst du? Hast du Kodi lokal bei dir installiert und dann debugst du das mit Kodi im Betrieb ?
Oder kann man das Plugin auch irgendwie standalone laufen lassen?
Vom Java her kenne ich das mit test driven, das ist ziemlich geil weil man so kein drum herum benötigt. 
Ich frage mich (angenommen ich würde mich da bisschen einbringen wollen) wie ich vll helfen könnte

**Comment by anis3** [comment]
Debug:
ich schreibe code wenn möglich kodi unabhängig
und debuge ausserhalb wenn nicht möglich nutze ich
Web-PDB
https://kodi.wiki/view/HOW-TO:Debug_Python_Scripts_with_Web-PDB

wie du helfen kannst??
weiß nicht wie deine schreiber künste sind jedenfalls
dein pull requests sind mir schon eine große hilfe
kann ich leider aber nicht so annehmen
weil *fixetzipfile.py* sonst nicht mehr mit kodi18 android
funktioniert ist auch der einzige einsatz der datei
jedenfalls setzte ich die meisten von dir jetzt rein
*vielen dank* wenn du bei gitter bist kannst du mich
auch privat anschreiben 

LG Anis

**Comment by damnms** [comment]
oh ok, dachte der nightly ist wirklich nightly (kodi 19+)

ich bin halt eigentlich java entwickler, nicht python, aber wegen studium dürfen wir nun python lernen (data analysis), von daher helf ich gern wenn ich kann :)

**Comment by anis3** [comment]
das finde ich super von dir z.B. die imports habe ich gedacht die hast du doch schon entfernt
hatte ich natürlich nicht wenn du willst können wir uns über gitter
weiter austauschen bin da auch als Anis3
erreichbar

**Comment by damnms** [comment]
ich hab element/matrix, meinen eigenen homeserver :) 
ich schau mal, scheinbar ist gitter und element kompatibel, werd versuchen dich zu kontaktieren

**Comment by damnms** [comment]
kannst du einen channel erstellen auf gitter.im? private nachrichten gehen scheinbar (noch) nicht zwischen matrix<->gitter
https://gitlab.com/groups/gitterHQ/-/epics/10

**Comment by anis3** [comment]
du kannst dich direkt mit deine github konto
bei gitter.im anmelden da brauchst du keine lästige registrierung
