### ISSUE TITLE
Problem bei SerienStream

### ISSUE THREAD

**Issue by albundycoa** [streamxstream/plugin.video.xstream#5]
**Beschreibe den Fehler**
Das Streamen über SerienStream ist nur noch bedingt möglich. DNS läuft über Cloudflare. Account habe ich bei s.to und ist auch eingetragen es kommt nur die Meldung: Es wurde kein Eintrag gefunden. 

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: [FireTV]
 - Kodi Version: Kodi 21
 - Xstream Version: 4.1

**Comment by DWH-WFC** [comment]
Das Problem liegt bei dir.
DNS richtig einstellen. VPN entfernen.

https://github.com/streamxstream/plugin.video.xstream/issues/3

**Comment by albundycoa** [comment]
am DNS lag es nicht VPN auch nicht ging bis jetzt auch ohne Probleme, warum auch immer der link hat mir geholfen. So wie es ausschaut muss man sich wohl  ab und an via Browser bei s.to anmelden, dann geht es wieder.

Vielen Dank

**Comment by DWH-WFC** [comment]
Kein Problem.
