### ISSUE TITLE
Hdfilme.tv unusable

### ISSUE THREAD

**Issue by michas0602** [streamxstream/plugin.video.xstream#52]
Hdfilme.tv is unusable - all videos have strange jumps!
Furthermore download is broken since months.

Plesse fix instead of new hosters all the time. Many thanks

**Comment by anis3** [comment]
Hi Micha
warum schreibst du englisch bei einen deutschen addon????

kann ich nach aktuellen stand leider nicht fixen
sobald ich den link an kodi übergebe habe ich keine einfluss
ob bzw. wie der stream läuft

LG Anis
