### ISSUE TITLE
Gibt es nun eine Version für Matrix?

### ISSUE THREAD

**Issue by coldspark29** [streamxstream/plugin.video.xstream#57]
Die Repo geht immer noch nicht für Matrix. Habe einen altes Issue gefunden, das geschlossen wurde. Deshalb sollte es ja gehen...

**Comment by anis3** [comment]
xStream unterstützt Kodi 17-19+
installiere es von offiziellen Repo
https://github.com/streamxstream/xStreamRepo/raw/master/repository.xstream/repository.xstream-1.1.5.zip

wenn es nicht bei dir funktioniert???
brauche ich mehr Infos damit ich dein Problem eingrenzen kann

was für Hardware(z.B. Fire stick gen2)
Betriebsystem/version
genaue Kodi Version

oder am besten ein
Kodi Debug log

LG Anis3 (xStream Entwickler)

bitte um Rückmeldung

**Comment by coldspark29** [comment]
Mit deiner Version funktioniert es. Ich hatte wohl einen alten Link. War aber auch 1.1.5. Komisch...
