### ISSUE TITLE
Download DialogProgress for Background?

### ISSUE THREAD

**Issue by harryberlin** [streamxstream/plugin.video.xstream#58]
The aim is, don't block the Kodi App during download.

It's possible to switch Download `DialogProgress()` to `DialogProgressBG()`
and disable the `oDialog.iscanceled()` option in download.py. Did a short successful test. Download was runnin and started a new stream.

But i think we need some futher features 
-to cancel the download (may a new entry on main menu) 
-disbale the used service for new streams 
-disable futher download
during the download event.
These are very tricky parts, because i don't understand how to build the menu and how to handle the used service. store in addon settings?

**Comment by anis3** [comment]
Hallo Harryberlin

warum schreibst du auf englisch bei einen deutschsprachigen Addon????
kannst du mir das bitte beantworten :-)

so jetzt zum Thema

damit die download Funktion so funktioniert wie du sie dir vorstellst
müsste man die funktioniert als Service auslagern

solange xStream gestartet ist wäre es ja kein Problem aber wenn du ein anderes Addon startest beendet Kodi gnadenlos xStream und somit den laufenden Download

da die Funktion sowieso nicht stabil ist würde ich dir raten mal die My.Jdownloader Funktion anzusehen da blockiert nichts & bei Abbruch kannst du ggf. den download fortsetzen

also ich schreibe auch jetzt gleich ganz deutlich wenn es die download Funktionen nicht vor meiner zeit gegeben hätte würden sie heute nicht existieren die haben mich bis jetzt null interessiert deswegen wird von meiner Seite da auch nichts kommen

wenn du es aber schaffst die Funktion als Service auslagern können wir über eine Integration in xStream reden

LG Anis(xStream Entwickler)

**Comment by harryberlin** [comment]
huiii, so wurde ich auch noch nicht auf die sprachwahl hingewiesen.

ist der aufruf für My.Jdownloader schon im code drin, damit man es leichter durchschaut?

hab dennoch grad mal den test gemacht, ein download gestartet und mit netzkino einen film per streaming gestartet.
zumindest mit kodi 18.9 unter windows10 wird da nix gekillt, der download läuft weiter.

![grafik](https://user-images.githubusercontent.com/13656586/124180388-647fd600-dab4-11eb-9b04-b58c4b44e522.png)

**Comment by anis3** [comment]
"hab dennoch grad mal den test gemacht, ein download gestartet und mit netzkino einen film per streaming gestartet.
zumindest mit kodi 18.9 unter windows10 wird da nix gekillt, der download läuft weiter."

ich habe doch geschrieben solange xStream gestartet kein Problem
aber wenn du z.B. das Youtube Addon startest bricht der download ab

"ist der aufruf für My.Jdownloader schon im code drin"

Ja klar muss in den xStream Einstellungen→Downloads
My Jdownloader aktivieren & deine anmelde Daten eintragen

das gleiche bei Jdownloader2 dann hast du direkt den Link im Jdownloader
je nach Hoster kannst du z.B. bei Abbruch fortsetzen oder ggf. schneller downloaden

du benötigst ein kostenloses Konto bei 
https://my.jdownloader.org
dafür kannst du eine Fakeemail benutzen z.B. fakemailgenerator.com

da du sowieso Windows benutzt ist die Funktion optimal oder wenn du
z.B. ein NAS betreibst kannst du da den Link direkt auf dein NAS schicken
und es so einrichten das es direkt die Datei runterläd
oder von z.B. von Android Smartphone/Box direkt den Link schickt usw.

LG Anis

**Comment by harryberlin** [comment]
Ich will nicht unhöflich sein, aber du hast es falsch verstanden. Netzkino habe ich als addon genutzt, nicht aus xstream heraus.
Auch auf Android mit Tele5 addon funktioniert der Download im Hintergrund, so wie ich es oben geändert hab.
Sogar zwei Downloads parallel liefen.
Youtube habe ich noch nicht getestet, weil ich das mit dem key nicht ganz checke.

werde dennoch mal weiterschauen, wie man es lösen kann.
