### ISSUE TITLE
Repo does not work with kodi version 21.90.700

### ISSUE THREAD

**Issue by CarstenG2** [streamxstream/plugin.video.xstream#6]
Repo 1.2.2 does not work with kodi version 21.90.700 (nightly master).

Error in kodi.log:
"Repository add-on repository.xstream does not have any directory matching 21.90.700 and won't be able to update/serve addons! Please fix the addon.xml definition"

The addon.xml includes only a max-version of 21.9.700 but ot 21.90.700.
When fixing that in the in the addon.xml, then the repo shows the lastest xStrea version, but download/update is also failing because of the same version issues.

**Comment by DWH-WFC** [comment]
Welche Version von Kodi hast du? wir sind derzeit bei der Release  Version 21.1

**Comment by CarstenG2** [comment]
Menü „Systeminformationen“ zeigt für die letzte ARM-nightly hier „22.0-Alpha (21.90.700)Von meinem iPad gesendetAm 18.09.2024 um 16:28 schrieb DWH-WFC ***@***.***>:﻿
Welche Version von Kodi hast du? wir sind derzeit bei der Release  Version 21.1

**Comment by DWH-WFC** [comment]
Wir unterstützen keine Alpha und Beta Versionen. Nur veröffentlichte Release Versionen.
