### ISSUE TITLE
Add Index Site Streamkiste.tv

### ISSUE THREAD

**Issue by jonatan2010** [streamxstream/plugin.video.xstream#62]
Hallo, bitte unterstützt die Index Site Streamkiste.tv

Diese Seite hat fast alle Serien und Filme, die es in deutscher Sprache gibt.

**Comment by kasi45** [comment]
![Unbenannt](https://user-images.githubusercontent.com/18262216/139507944-a5485d9e-0ae5-4269-920b-69d2eb55cfd8.jpg)
