### ISSUE TITLE
Hin und wieder funktionert seriensteam nicht z.b. jetzt funktioniert es auch nicht.

### ISSUE THREAD

**Issue by Stivan101** [streamxstream/plugin.video.xstream#66]
Bei serienstream funktioniert jeder Schritt aber so bald man einen hoster auswählt dann öffnet sich kein stream.

**Comment by sKippah** [comment]
Selbes Problem hier.  URL kann nicht aufgelöst werden.  404 Fehler

**Comment by sKippah** [comment]
Fehler gefunden. Xstream hat wohl die IP als Hoster drin die man im Router freigeben müsste
Quote von s.to Domains:
`IP-Proxy des S.to Inhalts
190.115.18.20
Keine DNS-Anpassung notwendig, einfach dauerhaft 190.115.18.20 eingeben.`

Bevor ich ne IP in meinem Router freigebe auf ne Seite die illegale Serien anbietet müsste schon die Hölle zufrieren "RIP s.to"

**Comment by UnbreakCode** [comment]
lässt sich die domain von serienstream nicht mehr in den settings umstellen?

**Comment by sKippah** [comment]
> lässt sich die domain von serienstream nicht mehr in den settings umstellen?

Leider Nein

**Comment by Stivan101** [comment]
Ich bin kein Experte aber wenn meine dns auf 8.8.8.8 ist ist meine IP adresse zusehen oder muss ich was in den Einstellungen was freigeben das sowas passiert?

**Comment by sKippah** [comment]
Keine Ahnung was du gerade meinst...

XStreams als auch XShip haben anstelle der Domains, für Serienstreams, jetzt die IP "190.115.18.20" hinterlegt.
Damit das Addon funktioniert, man also wieder Streams sehen kann, MÜSSTE man die IP im Router freigeben (Such in Google wie das geht) - Weil ich und viele andere wahrscheinlich auch, die IP **nicht** im Router freigegeben haben, gibts in Kodi, wenn man Serienstreams Stream öffnen will einen "404" Fehler.

ABER, eine IP die auf eine "dubiose" Seite, deren Hintermänner man nicht kennt, freizugeben KANN Tür und Tor öffnen für Hackerangriffe. KANN! muss aber nicht - Trotzdem, wer´s macht ist selbst schuld!
Und das man die Domains nicht mehr wechseln kann macht das Ganze nicht besser. 

https://serien.domains/ - Ich würde die Finger davon lassen

**Comment by UnbreakCode** [comment]
Man muss nichts freigeben, dass die IP funktioniert... Das hat damit nichts zutun.

> Ich bin kein Experte aber wenn meine dns auf 8.8.8.8 ist ist meine IP adresse zusehen oder muss ich was in den Einstellungen was freigeben das sowas passiert?

nichts musst du machen

solltest du wirklich ein Probleme damit haben die IP per HTTP anzusprechen, ändere doch einfach die Line https://github.com/streamxstream/plugin.video.xstream/blob/nightly/sites/serienstream_to.py#L16 und trag die Domain ein, die für dich funktioniert. Als zip packen und dann wieder installieren

**Comment by sKippah** [comment]
> solltest du wirklich ein Probleme damit haben die IP per HTTP anzusprechen, ändere doch einfach die Line https://github.com/streamxstream/plugin.video.xstream/blob/nightly/sites/serienstream_to.py#L16 und trag die Domain ein, die für dich funktioniert. Als zip packen und dann wieder installieren

Auf dem Fire TV, ja ne is klar....

**Comment by UnbreakCode** [comment]
> Auf dem Fire TV, ja ne is klar....

ich habe dir doch gerade erklärt was du zutun hast für dein Fire TV.
Du änderst auf deinem PC diese eine Zeile Code mit der Domain, die für dich funktioniert. Dann packst du das zu einer .zip zusammen und installierst diese .zip per Kodi einfach......

> Ich hab jetzt aber auch kein Nerv mehr mich hier noch Std lang im Kreis zu drehen. Es geht nicht Bums und Ende

kann ich nichts dafür, wenn du es leider nicht verstehst :)

**Comment by sKippah** [comment]
> kann ich nichts dafür, wenn du es leider nicht verstehst :)

Digga, sei nicht so ein arrogantes Arschloch.
Wenn Du n wenig Ahnung von der Materie/der Hardware hättest wüsstest du das jeder anständige Router IP-Adressen blockt und ich die freigeben MUSS damit Serienstreams auf Kodi wieder funktioniert.

Und ich kann nicht einfach irgendeine Datei auf dem Fire TV ändern... Aber egal, ich unterstütze deine Engstirnigkeit nicht.
Das Thema wird jetzt ignoriert und du steckst dir mal n Finger in den Popo, riechst mal dran, dann weisste auch was für Arsch Du bist. Ekelhafter Typ

**Comment by kasi45** [comment]
Abgesehen davon das mit Serienstream alles so OK ist und auch funktioniert(mit eigenen Kontendaten),  ist es so wie @UnbreakCode  schon geschrieben hat - man muss auch keine IP im Router freigeben. DNS sollte man anpassen und das wurde schon so oft erklärt wie man dies macht.
Im übrigen kann man auf dem FireTV auch die Dateien direkt editieren - wenn man es weis wie es geht.

Da der Ton hier unterirdisch ist - mach ich jetzt hier dicht
