### ISSUE TITLE
S.to IP nutzen

### ISSUE THREAD

**Issue by ghost** [streamxstream/plugin.video.xstream#68]
Nochmal zum Thema Serienstreams und IP-Adresse.
Ich rolle das Thema deswergen noch mal auf, weil ich mich hier nicht als Deppen hinstellen lasse und das Verhalten mir gegenüber ebenso unmöglich finde. Ich entschuldige mich im Übrigen für nichts!

Zur Klarstellung:
Die Fritz Box und die meisten anderen Router leiten Externe IP-Adressen grundsätzlich, aus Sicherheitsgründen, NICHT weiter.
Will man nun und das scheinen hier 2 Personen nicht zu verstehen, das s.to wieder funktioniert, auf welchem Device auch immer MUSS man die IP von s.to im Router eintragen und freigeben (weiterleiten)
Und GENAU aus diesem Grund funktioniert s.to auch nicht mit dem Fire TV-Stick, WEIL EBEN die IP im Router nicht forwarded wird.
Ist denn das SOOOO schwer zu verstehen ihr sogenannten Cracks???

Zur Verdeutlichung, weil es einige wohl IMMER noch nicht kapieren (wollen)
https://abload.de/img/fritz91kao.png

Und das ich mit "ADB link" und anderen Tools Daten bearbeiten oder APS sideloaden kann, weiß ich ebenfalls

Eure Ignoranz kotzt mich an!

**Comment by harryberlin** [comment]
ein workaround wurde doch genannt.
der code ist open source.
es steht dir frei eine Änderung zu erstellen, die später dann gemerged werden kann.

**Comment by MartinX3** [comment]
Ich verstehe die Problematik hier nicht richtig.
Wenn ich auf eine IP oder einen DNS Namen zugreifen möchte, greife ich in beiden Fällen auf die IP zu. Nur sagt mir der DNS Server vorher, welche IP das ist.
Das klappt bei jedem HeimRouter.
Initialer Verkehr von außen rejected die Firewall, für Verkehr Initial von innen macht die Firewall eine temporäre Ausnahme für die aktuelle Verbindung, damit Antworten von außen auch ankommen.
Natürlich auch bei der Fritzbox.
Sonst könnte man keine Website aufrufen oder Dateien downloaden.

Auf Servern sieht das anders aus, da blockiert der Admin zunächst alles und schaltet dann händisch einzelne Ports frei.
Aber bei Servern soll der Verkehr ja initial von außen kommen.

Kurzum, wenn man die IP von einer Seite im Browser direkt aufruft, bekommt man die Seite auch zu sehen. Daher muss man in Router nichts freischalten.

Natürlich gibt es dann auch so Spezis (Server Admins), die einfach jede Verbindung ablehnen, die den Hostnamen der Seite nicht im Request-HTTP-Header stehen hat und verkaufen das als Sicherheit.

**Comment by harryberlin** [comment]
vllt. mal prüfen welche DNS eingetragen ist?

**Comment by kasi45** [comment]
@ghost alias sKippah

@MartinX3 hat es dir hier alles richtig und fast perfekt erklärt! Du solltest dich mal mit den elementaren Grundlagen (Internet) beschäftigen. Meine Lehrlinge brachte ich diesen Stoff  schon im im ersten Lehrjahr bei und es ist kein Hexenwerk aber Grundlagenwissen um heterogene Netzwerke zu administrieren. 

Zu deinem Umgangston wurde dir ja schon an anderer Stelle etwas gesagt - man könnte meinen du bist gerade erst der Kindergartengruppe entwachsen.

Somit wird nun auch hier geschlossen und ich bitte dich von weiteren, neuen Beiträgen abzusehen.
