### ISSUE TITLE
Anicloud.io ist von s.to und gleich aufgebaut.

### ISSUE THREAD

**Issue by Stivan101** [streamxstream/plugin.video.xstream#69]
Onepiece-tube.com ist auch gut unter >anime streames > Episoden
Findet man alle Folgen.

**Comment by kasi45** [comment]
Und was möchtest du uns hier sagen?

**Comment by Stivan101** [comment]
Ob es hinzugefügt werden könnte zum addon.

**Comment by kasi45** [comment]
An Anime & Co hat die Mehrzahl der Nutzer keine Interesse. Da wird sich niemand die Arbeit machen solche Seiten hinzu zu fügen.

**Comment by nikiibarbaro** [comment]
> Ob es hinzugefügt werden könnte zum addon.

Ist nun im nightly channel verfügbar
