### ISSUE TITLE
Installation auf Xbox Series S und Android nicht möglich

### ISSUE THREAD

**Issue by RiotReimar77** [streamxstream/plugin.video.xstream#7]
**Beschreibe den Fehler**
xStream lässt sich auf der Xbox Series S nicht aus dem Repo installieren. Kodi hängt sich nach der Auswahl des Vidoplugins zur Installation auf und muss beendet werden. Neuinstallation von Kodi hat keine Abhilfe geschaffen.

NACHTRAG:

Installation unter Android funktioniert ebenfalls nicht.

**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Medienquelle hinzugefügt (offizielles Repo)
2. Aus ZIP-Datei installiert
3. Aus Repo installieren -》xStream -》Videoplugins
4. xStream auswählen
5. Kodi friert ein, eine Installation ist nicht möglich

**Erwartetes Verhalten**
Installation des Plugins

**Screenshots**
Wenn möglich füge ein oder mehrere Screenshots hinzu um den Fehler zu erklären

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: Xbox Series S
 - Kodi Version: Kodi 21.1
 - Xstream Version: 4.1.2

**Zusätzliche Informationen**
Füge zusätzliche/ergänzende Informationen zum Fehler hinzu

**Comment by DWH-WFC** [comment]
Ist bekannt hat sich irgendwo ein Fehler eingeschlichen

**Comment by RiotReimar77** [comment]
Danke für die Info, dann warte ich mal ab.

**Comment by DWH-WFC** [comment]
Sollte wieder funktionieren.

**Comment by RiotReimar77** [comment]
Ja, funktioniert wieder.

**Comment by DWH-WFC** [comment]
Was startet denn nicht?Hast du irgendein gekauftes Build am laufen?
Hast du aus der Repository installiert?

**Comment by RiotReimar77** [comment]
Kodi ist die Standardinstallation aus den jeweiligen Stores, xStream habe ich aus der Repository installiert. Sieht so aus:

![IMG-20240918-WA0001](https://github.com/user-attachments/assets/bf522363-9f57-4753-b3db-7fb6f7aa50ca)

Öffne ich xStream, lande ich hier

![IMG-20240918-WA0002](https://github.com/user-attachments/assets/fd03341d-d4f1-4bcc-82eb-b000951504fd)

Beim klicken auf das Plugin passiert nichts weiter. Ähnlich auch bei der Suche über TMDB.

![IMG-20240918-WA0003](https://github.com/user-attachments/assets/c73fd2cd-88a1-4e48-8069-2bf5a7a217bc)

Wähle ich dann einen Eintrag, lande ich wieder ganz am Anfang.

![IMG-20240918-WA0004](https://github.com/user-attachments/assets/8e3104ed-5bcc-401a-b67d-fe5c02979952)

Daraus wird dann eine Endlosschleife. Die bestehenden Installationen laufen dagegen problemlos, allerdings updaten die auch nicht automatisch.

**Comment by DWH-WFC** [comment]
Poste mal bitte dein Kodi.log

**Comment by RiotReimar77** [comment]
https://paste.kodi.tv/gadetutebu

Leider habe ich aktuell keinen Direktzugriff auf's Log bei dem Gerät, ich hoffe, so geht es auch.

**Comment by stgeisler** [comment]
Ich habe das gleiche Problem – xStream lässt sich in meiner frischen Kodi-Installation nicht öffnen. Hier sind die Warnungen und Fehler aus meinem Log:

warning <general>: JSONRPC: Could not parse type "Setting.Details.SettingList"
error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.xstream/
error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.xstream/) failed

**Comment by DWH-WFC** [comment]
Fehler wurde in der[ xStream Repository 1.2.3](https://github.com/streamxstream/xStreamRepo) behoben.
