### ISSUE TITLE
Anicloud.io trotz eingegebene Accountdaten kein stream möglich.

### ISSUE THREAD

**Issue by Stivan101** [streamxstream/plugin.video.xstream#71]

**Comment by nikiibarbaro** [comment]
Ohne genauere Details kann ich nicht helfen. Bei mir läuft alles einwandfrei.

**Comment by Stivan101** [comment]
> Ohne genauere Details kann ich nicht helfen. Bei mir läuft alles einwandfrei. 

Die hoster werden angezeigt und wenn ich eine auswähle dan steht da: kein hoster verfügbar oder hoster link fehlerhaft.

**Comment by nikiibarbaro** [comment]
> > Ohne genauere Details kann ich nicht helfen. Bei mir läuft alles einwandfrei.
> 
> Die hoster werden angezeigt und wenn ich eine auswähle dan steht da: kein hoster verfügbar oder hoster link fehlerhaft.

Dann versuche bitte mal entsprechend, die Folge im Browser abzuspielen und gebe gerne Rückmeldung, normalerweise ist das der Fehler den du bekommst, wenn eine Folge offline ist.

**Comment by Stivan101** [comment]
> > > Ohne genauere Details kann ich nicht helfen. Bei mir läuft alles einwandfrei.
> > 
> > Die hoster werden angezeigt und wenn ich eine auswähle dan steht da: kein hoster verfügbar oder hoster link fehlerhaft.
> 
> Dann versuche bitte mal entsprechend, die Folge im Browser abzuspielen und gebe gerne Rückmeldung, normalerweise ist das der Fehler den du bekommst, wenn eine Folge offline ist. 

Im Browser funktioniert der stream. Habe es gerade getestet. Ist die gleiche Folge. Gleicher hoster.

**Comment by nikiibarbaro** [comment]
Dann liegt es nicht an der Seite sondern am resolver für den dementsprechenden Hoster, gestern Nacht wurde etwas geändert, kann sein, dass es damit zusammenhängt.

**Comment by Stivan101** [comment]
Anicloud gab es auch schon lange bei xship aber da ging es auch nicht.
S.to funktioniert bei beiden addons.
Kann es daran liegen das ich bei s.to und anicloud den gleichen E-mail benutze?
Habe schon für anicloud passwort geändert.

**Comment by nikiibarbaro** [comment]
> Anicloud gab es auch schon lange bei xship aber da ging es auch nicht. S.to funktioniert bei beiden addons. Kann es daran liegen das ich bei s.to und anicloud den gleichen E-mail benutze? Habe schon für anicloud passwort geändert.

Nein eigentlich nicht. Welcher Hoster ist das, bei dem es nicht geht?

**Comment by Stivan101** [comment]
Voe sd funktioniert nicht. Aber kann sein das du recht hast. Ein paar hoster funktionieren anscheinend.

**Comment by nikiibarbaro** [comment]
> Voe sd funktioniert nicht. Aber kann sein das du recht hast. Ein paar hoster funktionieren anscheinend.

Dann liegt es sehr wahrscheinlich am Resolver.
