### ISSUE TITLE
Xstream startet nicht 

### ISSUE THREAD

**Issue by mosisimo** [streamxstream/plugin.video.xstream#8]
**Beschreibe den Fehler**
Sehr eigenartig, seit gestern startet xstream auf  dem Galaxy S 24 und Lenovo Tablet nicht mehr. Xstream Repository 1.2.2, xstream 4.1.2 sind installiert. Wenn man das xstream startet dann erscheinen die streaming Seiten nicht. Ich sehe da nur drei Ordner "Datei, Wiedergabeliste und Video- Addons".  Da ist keine "globale suche" oder "Kinoger"  alle streaming Seiten fehlen Einstellungen sind auch nicht vorhanden. 
 
**Zum Reproduzieren**
Schritte um den Fehler nachzustellen:
1. Gehe zu '...'
2. Klicke auf '....'
3. Scrolle hinunter bis '....'
4. siehe Fehler

**Erwartetes Verhalten**
Eine klare Beschreibung was zu erwarten ist

**Screenshots**
Wenn möglich füge ein oder mehrere Screenshots hinzu um den Fehler zu erklären

**Technische Informationen (Bitte die folgenden Infos vervollständigen):**
 - Hardware und Betriebssystem: [z.B. Nvidia Shield, Android TV 11]
 - Kodi Version: [z.B. Kodi 20]
 - Xstream Version: [z.B. 4.0.2~nightly1]
 - Resolver Version: [z.B. 5.1.8.9]

**Zusätzliche Informationen**
Füge zusätzliche/ergänzende Informationen zum Fehler hinzu

**Comment by DWH-WFC** [comment]
Bitte Fehlerprotokoll ordnungsgemäß ausfüllen und Kodi.log anhängen

**Comment by mosisimo** [comment]
Habe xstream über HKS Repo installiert,  das hat funktioniert
