### ISSUE TITLE
Settings.xml Kinox

### ISSUE THREAD

**Issue by Lod3355** [streamxstream/plugin.video.xstream#83]
Moin, könntet ihr die Settings.xml aktualisieren? Neue Kinox URL: www12.kinox.to / www.12.kinos.to und die auch als default nutzen. Sonst geht Kinox nicht mehr :(

**Comment by DWH-WFC** [comment]
Servus 
also bei www.12.kinos.to konnte ich keinen Content verzeichnen. Die andere Adresse wurde mit aufgenommen.

**Comment by Lod3355** [comment]
Sorry, www12.kinos.to

DWH-WFC ***@***.***> schrieb am Mo., 28. März 2022, 17:05:

**Comment by Lod3355** [comment]
Genau wie www12.kinoz.to
