### ISSUE TITLE
[Feature Request] Empfehlungen

### ISSUE THREAD

**Issue by Nagirah90** [streamxstream/plugin.video.xstream#87]
Ein Feature welches mir zur vollen Zufriedenheit noch fehlen würde, wäre eine Auflistung von Empfehlungen anhand der letzten (10?) gesehenen Filme/Serien. 

Die [Anbindung](https://forum.kodi.tv/showthread.php?tid=279131) scheint es zu geben und die Empfehlungen lassen sich ja über TMDB abrufen. Von daher würde ich mir das gerne von euch wünschen.

Dankeschön!

**Comment by streamxstream** [comment]
Vielen Dank für Deine Anfrage
Leider ist es aus zeitlichen Gründen momentan nicht möglich sich die Sache genauer anzuschauen
Wir lassen den Beitrag hier mal stehen und eventuell ist später mal Zeit

**Comment by Bender2403** [comment]
Die Funktion gibt es beim addon themoviedb helper aber über trakt.tv nur mal als Info am Rande 😉

**Comment by Heptamer** [comment]
Ja kenn ich, hab ich mal als Einbindung in einen Skin genutzt.
Für die Empfehlungen braucht man aber einen TMDB Account, und wir müssen ja auch melden was sich angeschaut wurde damit die Vorschläge überhaupt kommen. Ist nicht mal ebenso gemacht.

**Comment by Bender2403** [comment]
Du verstehst mich da falsch ich meinte eigentlich nicht zu viel einbauen besser auf das wesentliche konzentrieren die meisten anderen Funktionen kannst du mit existieren addons nachrüsten 😉

**Comment by Bender2403** [comment]
Zum Beispiel für die Seiten, netzkino, Pluto tv, joyn gibt es ja sehr gute addons ich denke es ist einfacher für die addons ein Script zu schreiben als für die Seite

**Comment by DWH-WFC** [comment]
Also ich persönlich würde auch davon abraten. xStream sollte eine Suchmaschine für Streams bleiben. Alle zusätzlichen Funktionen kann man mit ein 2 Plugins ergänzen. 

Ich bin der Meinung xStream sollte so schnell wie es ist auch bleiben. Und nichts überflüssiges (in meinen Augen) rein bekommen was es nur ausbremst.

**Comment by Bender2403** [comment]
Sehe ich genauso besser auf das wesentliche konzentrieren und an der Performance arbeiten alles andere kann man wie gesagt mit addons nachrüsten

**Comment by Heptamer** [comment]
Ich mach hier jetzt mal zu. Empfehlungen etc. lassen sich über entsprechende Addons nachrüsten. Xstream bleibt in seiner Funktion eher eine Suchmaschine für Filme, da wird auch noch was dran verbessert was die Einbindung von TMDb helper Playern betrifft, aber ansonsten war es das. Bringt nichts das Rad immer wieder neu zu erfinden.
