### ISSUE TITLE
Kinox Fix 

### ISSUE THREAD

**Issue by Lod3355** [streamxstream/plugin.video.xstream#89]
Moin, habe mal nen KinoX Fix hoch geladen.. 

https://files.fm/u/qwhh2xt34

Dank ans Team für eure Arbeit ;)

**Comment by Heptamer** [comment]
Besten Dank, schauen wir uns morgen einmal an.

**Comment by TitanME** [comment]
Kann eigentlich umgesetzt werden...keine utf-8-Fehlermeldungen mehr ;-)

**Comment by Heptamer** [comment]
Dafür Tausende kaputte Hosterlinks. Wird auch gerade noch einiges andere geändert von unserer Seite an dem Scraper.

Ich lass das aber noch mal stehen, falls jemand diese Version so lange haben möchte.

**Comment by TitanME** [comment]
Du bist der Coder und kannst das sicher besser beurteilen, als ich. Aus simpler User-Sicht sind das 2-3 Klicks und alles läuft

Nutze ich bis dahin sehr gerne.

**Comment by Heptamer** [comment]
Kinox fix ist raus, ich mach dann hier mal zu.
