### ISSUE TITLE
Fehler in der serienstream_to.py

### ISSUE THREAD

**Issue by TitanME** [streamxstream/plugin.video.xstream#91]
Der Fehler tritt nur auf bei:
- Alle Serien
- Suche

alle anderen Kategorien funktionieren

_(LOG anbei)_

[kodi.log](https://github.com/streamxstream/plugin.video.xstream/files/8575691/kodi.log)

**Comment by Heptamer** [comment]
Besten Dank für die Info, werden wir uns anschauen.

**Comment by dxsdev0** [comment]
Das scheint der Proxy zu sein. 
Die HTML Seite (im Browser) ist auch kaputt und hört einfach mittendrin auf auf.
Wenn man über die original url geht (z.B. s.to) dann klappt alles.

**Comment by TitanME** [comment]
Also bei mir funktioniert die Funktion auf der Website

http://190.115.18.20/serien

**Comment by dxsdev0** [comment]
zu "Alle Serien":
Scroll auf der Webseite ganz nach unten. Dort fehlt dann z.B. die Fußzeile. Die Seite wird nicht vollständig vom Server geliefert.
Zu "Suche":
Die Suche in XS ist "selbstgebaut" und basiert auf den Daten oben.

**Comment by TitanME** [comment]
Dann müsste man es eben wieder so machen => https://gitter.im/Lastship_Chat/xStream?at=626bda2214df4e44f200320d

**Comment by Heptamer** [comment]
Ich habe jetzt in den Einstellungen die Domains hinzugefügt, wenn der Proxy 190.115.18.20 ausgewählt wird, wird der Menüeintrag "Alle Serien" ausgeblendet da der Proxy eine Exception ausliefert, wie weiter oben schon erwähnt. Bei den normalen Domains bleibt der Menüpunkt erhalten. 

Einen ExceptionHandler werde ich dafür nicht schreiben, weil das eine ziemliche Last auf dem Server auslöst.
