### ISSUE TITLE
[Feature Request] Alle Seiten

### ISSUE THREAD

**Issue by Nagirah90** [streamxstream/plugin.video.xstream#94]
Ein Feature welches in meinen Augen die Benutzbarkeit des Plugins deutlich erhöhen würde, wäre ein weiterer Menüpunkt auf der Hauptseite, der alle verfügbaren Seiten enthält anstatt wie bisher alles einfach auf die Hauptseite zu packen. Je nachdem was man sucht ist das manchmal ganz schön lästig sich durch die lange Liste zu scrollen.

Zusätzlich sollte man über die Einstellungen das so machen können, dass die paar Seiten die man regelmäßig nutzt stattdessen auf der Hauptseite angezeigt werden. Also so eine Art Beschränkung auf ein paar Favoriten und den Rest kann man dann über "Alle Seiten" (oder wie der Eintrag später heißt) anzeigen lassen.

Ich für meinen Teil nutze eigentlich immer nur eine Hand voll von Seiten und den Rest dann höchstens über die "Globale Suche" wenn ich etwas bestimmtes finden möchte. Ich bin aber glaube auch nicht der Einzige dem es so geht.
Von daher würde ich mir das gerne von euch wünschen.

Dankeschön!

**Comment by DWH-WFC** [comment]
XStream ist als Suchmaschine aufgebaut, deswegen denke ich eher nicht. 
Ein Favorisierung darüber könnte man  mal in der Gruppe sprechen ob dies ein Mehrwert der Gruppe bevorzugt

**Comment by Nagirah90** [comment]
Auch eine Suchmaschine kann durchdach4 und benutzerfreundlich sein

**Comment by MartinX3** [comment]
Meiner Meinung und der von ein paar anderen privat war, dass `LastShip` nutzerfreundlicher war.
Ich wäre froh, wenn ein Ehrenamtler in der Richtung ein PR einreicht. :)

**Comment by Bender2403** [comment]
Lastship und xstream gehen ja unterschiedliche Wege und mit dem themoviedb helper kann man sich eine Art Lastship zusammenstellen mit dem Player Dateien

**Comment by MartinX3** [comment]
Oh, als Endnutzer wusste ich das nicht. Ich hab nur die UI verglichen und den Zeitwaufwand einen Film/ eine Serie bei beiden aufzurufen.

**Comment by Heptamer** [comment]
Man kann doch die Seiten die man benötigt oder auch die Globale Suche in die Kodi-Favoriten packen. Mit Super Favorites könnte man dann sogar noch einen eigenen Xstream Ordner machen wo man die Seiten die man regelmässig nutzt ablegt.  Die Funktion ist also schon vorhanden. Danke auf jeden Fall für Deine Anregung, aber da es Systemseitig schon was gibt macht es keinen Sinn das noch mal in XStream zu duplizieren.
