### ISSUE TITLE
HTTPError 403 bei IP-Domain-Nutzung von Serienstream

### ISSUE THREAD

**Issue by TitanME** [streamxstream/plugin.video.xstream#96]
Der Fehler hier tauchte gestern schon in FB auf...heute wieder vermehrt...und ich kann den reproduzieren & bestätigen 😕

- Serienstream-Einstellung auf IP-Domain
- Getestet auf Windows & Android
- Keine einzige Kategorie der Startseite lässt sich öffnen

![A2](https://user-images.githubusercontent.com/65415236/167263434-88a96634-8de1-48ba-bba8-1cbdd418c5ab.jpg)

[kodi.log](https://github.com/streamxstream/plugin.video.xstream/files/8645578/kodi.log)

**Comment by Heptamer** [comment]
Wurde von mir getestet, keine Fehlermeldung wenn ich den Proxy auswähle. Wenn dann war es ein temporäres Problem oder der Proxy war gesperrt (Fehler 403 forbidden).
