### ISSUE TITLE
Python2/3 ParameterHandler

### ISSUE THREAD

**Issue by dxsdev0** [streamxstream/plugin.video.xstream#98]
Hi,
mir ist beim drüber schauen noch etwas aufgefallen...
Wenn man mit Kodi18 auf Kinokiste > Serien > Serien (aktualisiert) geht, bekommt man eine Unicode-Fehlermeldung.
`UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 15: ordinal not in range(128)`
Das liegt soweit ich das sehen kann am Parameterhandler.
`paramValue =  str(paramValue)`
Da gibt es jetzt viele Möglichkeiten...die einfachste (nicht die schönste) ist ein py2/3 Behandlung im ParameterHandler.
Der Code unten klappt für mich auf Kodi18 & Kodi19...kann eigentlich nicht viel kaputt gehen :-)
```
    def setParam(self, paramName, paramValue):
        # set the value of the parameter with the name "paramName" to "paramValue"
        # if there is no such parameter, the parameter is created
        # if no value is given "paramValue" is set "None"
        if sys.version_info[0] == 2 and isinstance(paramValue, unicode):
            paramValue = paramValue.encode('UTF-8')
        else:
            paramValue =  str(paramValue)
        self.__params.update({paramName: paramValue}) 

    def addParams(self, paramDict):
        # adds a whole dictionary {key1:value1,...,keyN:valueN} of parameters to the ParameterHandler
        # existing parameters are updated
        for key, value in paramDict.items():
            vvalue = value
            if sys.version_info[0] == 2 and isinstance(value, unicode):
                vvalue = value.encode('UTF-8')
            else: 
                vvalue =  str(value)
            self.__params.update({key: vvalue})
```

**Comment by DWH-WFC** [comment]
Vielen Dank für deine Info.

**Comment by Heptamer** [comment]
Wir haben darüber im Team gesprochen und entschieden dass wir für KODi 18 bzw. Python2 xstream nicht mehr weiter pflegen.

Zum einen hat keiner von uns mehr eine Kodi18 Testumgebung, zum anderen wird KODi 18 offiziell auch nicht mehr supported und bis Kodi 20 ist es nicht mehr so weit. Dann drei Versionen zu pflegen mit zwei unterschiedlichen Codebases ist etwas viel Aufwand, vor allem da wir nicht wissen wie viele wirklich noch xstream unter KODi18 am laufen haben.

Danke für deine Mühe das zu analysieren, hoffe du verstehst aber unsere Beweggründe das nicht umzusetzen.

**Comment by harryberlin** [comment]
könnt ihr es dann bitte so machen, dass die letzte py2 version verfügbar bleibt, nur sich nicht mehr updated?

**Comment by MartinX3** [comment]
Eine alte xStream-Version die langsam weg stirbt und nur unter Kodi v18 installierbar ist, würde manchen sicherlich gefallen
Für meinen Raspi3 Kodi 19 port musste ich auch ein Jahr oder so warten
Andere vielleicht länger

**Comment by Heptamer** [comment]
> könnt ihr es dann bitte so machen, dass die letzte py2 version verfügbar bleibt, nur sich nicht mehr updated?

Der Code bleibt so wie er ist, das heißt xstream ist weiterhin mit Kodi 18 kompatibel - nur wird wenn es irgendwo Probleme gibt nichts mehr gefixt, das hatte ich aber auch so geschrieben.
