### ISSUE TITLE
[Feature Request] Einstellungen Exportieren

### ISSUE THREAD

**Issue by Nagirah90** [streamxstream/plugin.video.xstream#99]
Ein Feature welches in meinen Augen eine erhebliche Erleichterung beim Einrichten des Plugins wäre, wären zwei zusätzliche Menüpunkte zum exportieren/importieren von (witchtigen) Einstellungen auf z.B. einen USB Stick. Zugangsdaten vielen mir hier spontan ein. Dann müsste man die Einrichtung lediglich ein Mal machen und könnte anschließend einfach die Datei wieder importieren ohne manuell im Dateisystem herumfummeln zu müssen. Wäre zumindest auf Android/FireTV eine große Erleichterung! Von daher würde ich mir das gerne von euch wünschen.

Dankeschön!

**Comment by DWH-WFC** [comment]
Also eine Import/Export der settings.xml?

**Comment by Nagirah90** [comment]
Nicht unbedingt die ganze aber so wichtige Punkte wie Account-Daten wäre schon hilfreich. So wie ich das gesehen habe, fehlten hier zuletzt die Eingabemasken weswegen ich diese manuell in die settings.xml eintragen musste. Das war unter Android mindestens umständlich (auch wegen der je nach Gerat begrenzten Zeichen auf der Tastatur)

**Comment by Bender2403** [comment]
Wieso nutzt du dann nicht das Backup addon da werden auch gleich sämtliche settings der installierten addons gesichert?

**Comment by Heptamer** [comment]
> Nicht unbedingt die ganze aber so wichtige Punkte wie Account-Daten wäre schon hilfreich. So wie ich das gesehen habe, fehlten hier zuletzt die Eingabemasken weswegen ich diese manuell in die settings.xml eintragen musste. Das war unter Android mindestens umständlich (auch wegen der je nach Gerät begrenzten Zeichen auf der Tastatur)

Nein da fehlte keine, Eingabemaske man hätte nur mal weiter nach unten scrollen müssen auf der linken Seite, dann kommt auch der Menüpunkt Konten in den Settings.

**Comment by Heptamer** [comment]
Auch hier werde ich zumachen, die drei Konten die man maximal eingeben kann und die paar Einstellungen kann man auch von Hand machen. Alternativ nutzt man das KODi Backup, oder bei den elec Versionen das full Backup.

Dazu kommt: den Backup von Android Boxen oder generell auch von TVs etc. vernünftig wegzuspeichern dürfte für die meisten User schon fast ein unlösbares Problem darstellen, weil das Backup nutzt einem nichts wenn es auf dem Gerät liegt was neu installiert wird, weil ist nach Neuinstallation dann gelöscht.
